// cloudpdf/website/src/samples/snippets/viewing/link-analytics.react.tsx
import { LinkLayer, useLinkEvent } from '@embedpdf/react/link';
import { RenderLayer } from '@embedpdf/react/render';
import { Stage } from '@embedpdf/react/stage';
import { analytics } from './analytics';

export function Reader() {
  useLinkEvent(
    (link) => link.onActivated,
    ({ target }) => analytics.track('link_followed', { kind: target.kind }),
  );

  return (
    <Stage>
      {() => (
        <>
          <RenderLayer />
          <LinkLayer />
        </>
      )}
    </Stage>
  );
}

// website/src/samples/snippets/viewing/link-analytics.svelte.svelte
<script lang="ts">
  import { LinkLayer, useLinkEvent } from '@embedpdf/svelte/link';
  import { RenderLayer } from '@embedpdf/svelte/render';
  import { Stage } from '@embedpdf/svelte/stage';
  import { analytics } from './analytics';

  useLinkEvent(
    (link) => link.onActivated,
    ({ target }) => analytics.track('link_followed', { kind: target.kind }),
  );
</script>

<Stage>
  <RenderLayer />
  <LinkLayer />
</Stage>
