// examples/vue-quasar/src/components/Application.vue
<script setup lang="ts">
import { usePdfiumEngine } from '@embedpdf/engines/vue';
import { EmbedPDF } from '@embedpdf/core/vue';
import { createPluginRegistration, PluginRegistry } from '@embedpdf/core';
import { LoaderPluginPackage } from '@embedpdf/plugin-loader/vue';
import { Viewport, ViewportPluginPackage } from '@embedpdf/plugin-viewport/vue';
import { Scroller, ScrollPluginPackage, ScrollStrategy } from '@embedpdf/plugin-scroll/vue';
import { RenderLayer, RenderPluginPackage } from '@embedpdf/plugin-render/vue';
import { TilingLayer, TilingPluginPackage } from '@embedpdf/plugin-tiling/vue';
import { SelectionLayer, SelectionPluginPackage } from '@embedpdf/plugin-selection/vue';
import {
  InteractionManagerPluginPackage,
  GlobalPointerProvider,
  PagePointerProvider,
} from '@embedpdf/plugin-interaction-manager/vue';
import { RotatePluginPackage } from '@embedpdf/plugin-rotate/vue';
import { Rotate } from '@embedpdf/plugin-rotate/vue';
import { FullscreenPluginPackage } from '@embedpdf/plugin-fullscreen/vue';
import { ZoomMode, ZoomPluginPackage, MarqueeZoom } from '@embedpdf/plugin-zoom/vue';
import { PanPluginPackage } from '@embedpdf/plugin-pan/vue';
import { ExportPluginPackage } from '@embedpdf/plugin-export/vue';
import { SpreadPluginPackage } from '@embedpdf/plugin-spread/vue';
import { PrintPluginPackage } from '@embedpdf/plugin-print/vue';
import { SearchPluginPackage, SearchLayer } from '@embedpdf/plugin-search/vue';
import { ThumbnailPluginPackage } from '@embedpdf/plugin-thumbnail/vue';
import { RedactionPluginPackage, RedactionLayer } from '@embedpdf/plugin-redaction/vue';
import {
  AnnotationLayer,
  AnnotationPluginPackage,
  AnnotationPlugin,
} from '@embedpdf/plugin-annotation/vue';
import type { AnnotationTool } from '@embedpdf/plugin-annotation/vue';
import { PdfAnnotationSubtype } from '@embedpdf/models';
import type { PdfStampAnnoObject } from '@embedpdf/models';

import Toolbar from './Toolbar.vue';
import DrawerProvider from './drawer-system/DrawerProvider.vue';
import Drawer from './drawer-system/Drawer.vue';
import Search from './Search.vue';
import Sidebar from './Sidebar.vue';
import PageControls from './PageControls.vue';
import RedactionSelectionMenu from './RedactionSelectionMenu.vue';
import AnnotationSelectionMenu from './AnnotationSelectionMenu.vue';

// Define drawer components
const drawerComponents = [
  {
    id: 'search',
    component: Search,
    icon: 'mdi-magnify',
    label: 'Search',
    position: 'right' as const,
  },
  {
    id: 'sidebar',
    component: Sidebar,
    icon: 'mdi-dock-left',
    label: 'Sidebar',
    position: 'left' as const,
  },
];

const { engine, isLoading: engineLoading, error: engineError } = usePdfiumEngine();

const handleInitialized = async (registry: PluginRegistry) => {
  const annotation = registry.getPlugin<AnnotationPlugin>('annotation')?.provides();
  annotation?.addTool<AnnotationTool<PdfStampAnnoObject>>({
    id: 'stampApproved',
    name: 'Stamp Approved',
    interaction: {
      exclusive: false,
      cursor: 'crosshair',
    },
    matchScore: () => 0,
    defaults: {
      type: PdfAnnotationSubtype.STAMP,
      imageSrc:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Eo_circle_green_checkmark.svg/512px-Eo_circle_green_checkmark.svg.png',
      imageSize: { width: 20, height: 20 },
    },
  });
};
</script>

<template>
  <div class="application fit">
    <!-- Loading state -->
    <div v-if="engineLoading" class="state-container column items-center justify-center">
      <q-spinner size="64px" color="primary" />
      <div class="text-subtitle1 text-grey-7 q-mt-md">Loading PDF engine...</div>
    </div>

    <!-- Error state -->
    <div v-else-if="engineError" class="state-container column items-center justify-center">
      <q-banner class="q-ma-md" rounded dense color="negative" text-color="white">
        <div class="text-subtitle1 text-weight-medium">Error</div>
        <div class="text-body2 q-mt-xs">{{ engineError.message }}</div>
      </q-banner>
    </div>

    <!-- Main application -->
    <div v-else-if="engine" class="fit">
      <EmbedPDF
        :engine="engine"
        :on-initialized="handleInitialized"
        :plugins="[
          createPluginRegistration(LoaderPluginPackage, {
            loadingOptions: {
              type: 'url',
              pdfFile: {
                id: 'sample-pdf',
                name: 'embedpdf-ebook.pdf',
                url: 'https://snippet.embedpdf.com/ebook.pdf',
              },
            },
          }),
          createPluginRegistration(ViewportPluginPackage, {
            viewportGap: 10,
          }),
          createPluginRegistration(ScrollPluginPackage, {
            strategy: ScrollStrategy.Vertical,
            pageGap: 10,
          }),
          createPluginRegistration(RenderPluginPackage),
          createPluginRegistration(TilingPluginPackage, {
            tileSize: 768,
            overlapPx: 2.5,
            extraRings: 0,
          }),
          createPluginRegistration(InteractionManagerPluginPackage),
          createPluginRegistration(SelectionPluginPackage),
          createPluginRegistration(RotatePluginPackage),
          createPluginRegistration(FullscreenPluginPackage),
          createPluginRegistration(ZoomPluginPackage, {
            defaultZoomLevel: ZoomMode.FitPage,
          }),
          createPluginRegistration(PanPluginPackage),
          createPluginRegistration(ExportPluginPackage),
          createPluginRegistration(SpreadPluginPackage),
          createPluginRegistration(PrintPluginPackage),
          createPluginRegistration(ThumbnailPluginPackage, {
            imagePadding: 10,
            labelHeight: 25,
          }),
          createPluginRegistration(SearchPluginPackage, {
            flags: [],
            showAllResults: true,
          }),
          createPluginRegistration(RedactionPluginPackage),
          createPluginRegistration(AnnotationPluginPackage),
        ]"
      >
        <template #default="{ pluginsReady }">
          <DrawerProvider :components="drawerComponents">
            <q-layout view="hHh Lpr fFf" class="application__layout">
              <Toolbar />

              <Drawer position="left" />

              <q-page-container class="application__page-container">
                <q-page class="application__page q-pa-none">
                  <GlobalPointerProvider>
                    <Viewport class="application__viewport">
                      <div
                        v-if="!pluginsReady"
                        class="state-container column items-center justify-center"
                      >
                        <q-spinner size="48px" color="primary" />
                        <div class="text-body2 text-grey-7 q-mt-sm">Loading plugins...</div>
                      </div>

                      <Scroller v-else>
                        <template #default="{ page }">
                          <Rotate
                            :key="page.document?.id"
                            :page-size="{ width: page.width, height: page.height }"
                          >
                            <PagePointerProvider
                              :page-index="page.pageIndex"
                              :page-width="page.width"
                              :page-height="page.height"
                              :rotation="page.rotation"
                              :scale="page.scale"
                              class="page-layer"
                            >
                              <RenderLayer
                                :page-index="page.pageIndex"
                                class="layer"
                                style="pointer-events: none"
                              />
                              <TilingLayer
                                :page-index="page.pageIndex"
                                :scale="page.scale"
                                class="layer"
                                style="pointer-events: none"
                              />
                              <MarqueeZoom :page-index="page.pageIndex" :scale="page.scale" />
                              <SearchLayer :page-index="page.pageIndex" :scale="page.scale" />
                              <AnnotationLayer
                                :page-index="page.pageIndex"
                                :scale="page.scale"
                                :page-width="page.width"
                                :page-height="page.height"
                                :rotation="page.rotation"
                              >
                                <template
                                  #selection-menu="{ annotation, selected, menuWrapperProps, rect }"
                                >
                                  <AnnotationSelectionMenu
                                    v-if="selected"
                                    :annotation="annotation"
                                    :menu-wrapper-props="menuWrapperProps"
                                    :rect="rect"
                                  />
                                </template>
                              </AnnotationLayer>
                              <RedactionLayer
                                :page-index="page.pageIndex"
                                :scale="page.scale"
                                :rotation="page.rotation"
                              >
                                <template #selection-menu="{ item, selected, menuWrapperProps, rect }">
                                  <RedactionSelectionMenu
                                    v-if="selected"
                                    :item="item"
                                    :menu-wrapper-props="menuWrapperProps"
                                    :rect="rect"
                                  />
                                </template>
                              </RedactionLayer>
                              <SelectionLayer :page-index="page.pageIndex" :scale="page.scale" />
                            </PagePointerProvider>
                          </Rotate>
                        </template>
                      </Scroller>

                      <PageControls />
                    </Viewport>
                  </GlobalPointerProvider>
                </q-page>
              </q-page-container>

              <Drawer position="right" />
            </q-layout>
          </DrawerProvider>
        </template>
      </EmbedPDF>
    </div>

    <!-- Engine not ready state -->
    <div v-else class="state-container column items-center justify-center">
      <div class="text-body1 text-grey-7 text-center">Engine not ready</div>
    </div>
  </div>
</template>

<style scoped>
.application {
  user-select: none;
}

.application__layout {
  background-color: #f5f5f5;
}

.application__page-container,
.application__page {
  height: 100%;
}

.application__viewport {
  height: 100%;
  background-color: #f5f5f5;
  overflow: auto;
  position: relative;
}

.layer {
  pointer-events: none;
}

.page-layer {
  position: absolute;
  top: 0;
  left: 0;
}

.state-container {
  height: 100%;
  display: flex;
}
</style>

// examples/react-mui/src/application.tsx
import { createPluginRegistration } from '@embedpdf/core';
import { EmbedPDF } from '@embedpdf/core/react';
import { usePdfiumEngine } from '@embedpdf/engines/react';
import { ConsoleLogger, PdfAnnotationSubtype, PdfStampAnnoObject } from '@embedpdf/models';
import { Viewport, ViewportPluginPackage } from '@embedpdf/plugin-viewport/react';
import { Scroller, ScrollPluginPackage, ScrollStrategy } from '@embedpdf/plugin-scroll/react';
import { LoaderPluginPackage } from '@embedpdf/plugin-loader/react';
import { RenderLayer, RenderPluginPackage } from '@embedpdf/plugin-render/react';
import { TilingLayer, TilingPluginPackage } from '@embedpdf/plugin-tiling/react';
import { MarqueeZoom, ZoomMode, ZoomPluginPackage } from '@embedpdf/plugin-zoom/react';
import { SearchLayer, SearchPluginPackage } from '@embedpdf/plugin-search/react';
import {
  GlobalPointerProvider,
  PagePointerProvider,
  InteractionManagerPluginPackage,
} from '@embedpdf/plugin-interaction-manager/react';
import { PanPluginPackage } from '@embedpdf/plugin-pan/react';
import { Rotate, RotatePluginPackage } from '@embedpdf/plugin-rotate/react';
import { SpreadPluginPackage } from '@embedpdf/plugin-spread/react';
import { FullscreenPluginPackage } from '@embedpdf/plugin-fullscreen/react';
import { ExportPluginPackage } from '@embedpdf/plugin-export/react';
import { RedactionLayer, RedactionPluginPackage } from '@embedpdf/plugin-redaction/react';
import { ThumbnailPluginPackage } from '@embedpdf/plugin-thumbnail/react';
import { SelectionPluginPackage } from '@embedpdf/plugin-selection/react';
import { SelectionLayer } from '@embedpdf/plugin-selection/react';
import {
  AnnotationLayer,
  AnnotationPlugin,
  AnnotationPluginPackage,
  AnnotationTool,
} from '@embedpdf/plugin-annotation/react';

import { CircularProgress, Box, Alert } from '@mui/material';
import SearchOutlinedIcon from '@mui/icons-material/SearchOutlined';
import { useMemo, useRef } from 'react';

import { PageControls } from './components/page-controls';
import { Search } from './components/search';
import { Drawer, DrawerComponent, DrawerProvider } from './components/drawer-system';
import { Sidebar } from './components/sidebar';
import { Toolbar } from './components/toolbar';
import { ViewSidebarReverseIcon } from './icons';
import { AnnotationSelectionMenu } from './components/annotation-selection-menu';
import { RedactionSelectionMenu } from './components/redaction-selection-menu';

const plugins = [
  createPluginRegistration(LoaderPluginPackage, {
    loadingOptions: {
      type: 'url',
      pdfFile: {
        id: 'pdf',
        url: 'https://snippet.embedpdf.com/ebook.pdf',
      },
    },
  }),
  createPluginRegistration(ViewportPluginPackage, {
    viewportGap: 10,
  }),
  createPluginRegistration(ScrollPluginPackage, {
    strategy: ScrollStrategy.Vertical,
  }),
  createPluginRegistration(RenderPluginPackage),
  createPluginRegistration(TilingPluginPackage, {
    tileSize: 768,
    overlapPx: 2.5,
    extraRings: 0,
  }),
  createPluginRegistration(ZoomPluginPackage, {
    defaultZoomLevel: ZoomMode.FitPage,
  }),
  createPluginRegistration(SearchPluginPackage),
  createPluginRegistration(InteractionManagerPluginPackage),
  createPluginRegistration(PanPluginPackage),
  createPluginRegistration(RotatePluginPackage),
  createPluginRegistration(SpreadPluginPackage),
  createPluginRegistration(FullscreenPluginPackage),
  createPluginRegistration(ExportPluginPackage),
  createPluginRegistration(ThumbnailPluginPackage, {
    paddingY: 10,
  }),
  createPluginRegistration(SelectionPluginPackage),
  createPluginRegistration(AnnotationPluginPackage),
  createPluginRegistration(RedactionPluginPackage),
];

const drawerComponents: DrawerComponent[] = [
  {
    id: 'search',
    component: Search,
    icon: SearchOutlinedIcon,
    label: 'Search',
    position: 'right',
  },
  {
    id: 'sidebar',
    component: Sidebar,
    icon: ViewSidebarReverseIcon,
    label: 'Sidebar',
    position: 'left',
  },
];

const consoleLogger = new ConsoleLogger();

function App() {
  const isDev = useMemo(
    () => new URLSearchParams(window.location.search).get('dev') === 'true',
    [],
  );

  const { engine, isLoading, error } = usePdfiumEngine(isDev ? { logger: consoleLogger } : {});
  const popperContainerRef = useRef<HTMLDivElement>(null);

  if (error) {
    return (
      <Box
        sx={{
          height: '100%',
          width: '100%',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <Alert severity="error">Failed to initialize PDF viewer:</Alert>
      </Box>
    );
  }

  if (isLoading || !engine) {
    return (
      <Box
        sx={{
          height: '100%',
          width: '100%',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <CircularProgress size={48} />
      </Box>
    );
  }

  return (
    <DrawerProvider components={drawerComponents}>
      <EmbedPDF
        engine={engine}
        plugins={plugins}
        onInitialized={async (registry) => {
          const annotation = registry.getPlugin<AnnotationPlugin>('annotation')?.provides();
          annotation?.addTool<AnnotationTool<PdfStampAnnoObject>>({
            id: 'stampApproved',
            name: 'Stamp Approved',
            interaction: {
              exclusive: false,
              cursor: 'crosshair',
            },
            matchScore: () => 0,
            defaults: {
              type: PdfAnnotationSubtype.STAMP,
              imageSrc:
                'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Eo_circle_green_checkmark.svg/512px-Eo_circle_green_checkmark.svg.png',              imageSize: { width: 300, height: 120 },
            },
          });
        }}
      >
        {({ pluginsReady }) => (
          <Box
            sx={{
              height: '100%',
              width: '100%',
              display: 'flex',
              flexDirection: 'column',
              position: 'relative',
              userSelect: 'none',
            }}
          >
            <Toolbar />

            {/* Main content area with sidebars */}
            <Box sx={{ display: 'flex', flexGrow: 1, overflow: 'hidden' }}>
              {/* Left Sidebar */}
              <Drawer position="left" />

              {/* Main Viewport */}
              <Box
                ref={popperContainerRef}
                sx={{
                  flex: '1 1 0', // grow / shrink, flex-basis 0
                  minWidth: 0, // allow shrinking inside flex row
                  display: 'flex',
                  flexDirection: 'column',
                  position: 'relative',
                }}
              >
                <GlobalPointerProvider>
                  <Viewport
                    style={{
                      width: '100%',
                      height: '100%',
                      flexGrow: 1,
                      backgroundColor: '#f1f3f5',
                      overflow: 'auto',
                    }}
                  >
                    {!pluginsReady && (
                      <Box
                        sx={{
                          display: 'flex',
                          justifyContent: 'center',
                          alignItems: 'center',
                          height: '100%',
                          width: '100%',
                        }}
                      >
                        <CircularProgress size={48} />
                      </Box>
                    )}
                    {pluginsReady && (
                      <Scroller
                        renderPage={({ document, width, height, pageIndex, scale, rotation }) => (
                          <Rotate key={document?.id} pageSize={{ width, height }}>
                            <PagePointerProvider
                              pageIndex={pageIndex}
                              pageWidth={width}
                              pageHeight={height}
                              rotation={rotation}
                              scale={scale}
                            >
                              <RenderLayer
                                pageIndex={pageIndex}
                                style={{ pointerEvents: 'none' }}
                              />
                              <TilingLayer
                                pageIndex={pageIndex}
                                scale={scale}
                                style={{ pointerEvents: 'none' }}
                              />
                              <SearchLayer
                                pageIndex={pageIndex}
                                scale={scale}
                                style={{ pointerEvents: 'none' }}
                              />
                              <MarqueeZoom pageIndex={pageIndex} scale={scale} />
                              <SelectionLayer pageIndex={pageIndex} scale={scale} />
                              <RedactionLayer
                                pageIndex={pageIndex}
                                scale={scale}
                                rotation={rotation}
                                selectionMenu={({ menuWrapperProps, selected, item }) => (
                                  <>
                                    {selected ? (
                                      <RedactionSelectionMenu
                                        menuWrapperProps={menuWrapperProps}
                                        selected={item}
                                        container={popperContainerRef.current}
                                      />
                                    ) : null}
                                  </>
                                )}
                              />
                              <AnnotationLayer
                                pageIndex={pageIndex}
                                scale={scale}
                                pageWidth={width}
                                pageHeight={height}
                                rotation={rotation}
                                selectionMenu={({ menuWrapperProps, selected, annotation }) => (
                                  <>
                                    {selected ? (
                                      <AnnotationSelectionMenu
                                        menuWrapperProps={menuWrapperProps}
                                        selected={annotation}
                                        container={popperContainerRef.current}
                                      />
                                    ) : null}
                                  </>
                                )}
                              />
                            </PagePointerProvider>
                          </Rotate>
                        )}
                      />
                    )}
                    <PageControls />
                  </Viewport>
                </GlobalPointerProvider>
              </Box>

              {/* Right Sidebar */}
              <Drawer position="right" />
            </Box>
          </Box>
        )}
      </EmbedPDF>
    </DrawerProvider>
  );
}

export default App;
