// docs/content/snippets/documents/unsaved-warning.svelte.svelte
<script lang="ts">
  import { useDocument } from '@embedpdf/svelte/runtime';

  const doc = useDocument();

  $effect(() => {
    if (!doc.hasUnsavedChanges) return;
    const warn = (event: BeforeUnloadEvent) => event.preventDefault();
    window.addEventListener('beforeunload', warn);
    return () => window.removeEventListener('beforeunload', warn);
  });
</script>

{#if doc.hasUnsavedChanges}
  <span>Unsaved changes</span>
{/if}

// website/src/samples/snippets/documents/unsaved-warning.react.tsx
import { useEffect } from 'react';
import { useDocument } from '@embedpdf/react/runtime';

export function UnsavedWarning() {
  const { hasUnsavedChanges } = useDocument();

  useEffect(() => {
    if (!hasUnsavedChanges) return;
    const warn = (event: BeforeUnloadEvent) => event.preventDefault();
    window.addEventListener('beforeunload', warn);
    return () => window.removeEventListener('beforeunload', warn);
  }, [hasUnsavedChanges]);

  return hasUnsavedChanges ? <span>Unsaved changes</span> : null;
}
