// cloudpdf/website/src/samples/snippets/ui/stage-overlay.react.tsx
import { Anchored } from '@embedpdf/react/anchored';
import { RenderLayer } from '@embedpdf/react/render';
import type { SearchHit } from '@embedpdf/react/search';
import { Stage } from '@embedpdf/react/stage';
import { highlight } from './highlight';

export function Pages({ hit }: { hit: SearchHit }) {
  return (
    <Stage
      overlay={
        <Anchored anchor={{ page: hit.page, bounds: hit.bounds }} placement="bottom">
          <button onClick={() => highlight(hit)}>Highlight</button>
        </Anchored>
      }
    >
      {() => <RenderLayer />}
    </Stage>
  );
}

// cloudpdf/website/src/samples/snippets/ui/stage-overlay.svelte.svelte
<script lang="ts">
  import { Anchored } from '@embedpdf/svelte/anchored';
  import { RenderLayer } from '@embedpdf/svelte/render';
  import type { SearchHit } from '@embedpdf/svelte/search';
  import { Stage } from '@embedpdf/svelte/stage';
  import { highlight } from './highlight';

  let { hit }: { hit: SearchHit } = $props();
</script>

<Stage>
  <RenderLayer />
  {#snippet overlay()}
    <Anchored anchor={{ page: hit.page, bounds: hit.bounds }} placement="bottom">
      <button onclick={() => highlight(hit)}>Highlight</button>
    </Anchored>
  {/snippet}
</Stage>
