// examples/vue-tailwind/src/components/AnnotationSelectionMenu.vue
<template>
  <div v-bind="menuWrapperProps">
    <div :style="menuStyle" class="rounded-lg border border-gray-200 bg-white shadow-lg">
      <div class="flex items-center gap-1 px-2 py-1">
        <button
          @click="handleDelete"
          class="flex items-center justify-center rounded p-1.5 text-gray-600 transition-colors hover:bg-gray-100 hover:text-red-600"
          aria-label="Delete annotation"
          title="Delete annotation"
        >
          <TrashIcon class="h-4 w-4" />
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, type CSSProperties } from 'vue';
import type { Rect } from '@embedpdf/models';
import type {
  AnnotationSelectionContext,
  AnnotationSelectionMenuProps,
} from '@embedpdf/plugin-annotation/vue';
import { useAnnotationCapability } from '@embedpdf/plugin-annotation/vue';
import TrashIcon from './icons/TrashIcon.vue';

const props = defineProps<{
  documentId: string;
  context: AnnotationSelectionContext;
  selected: boolean;
  rect: Rect;
  placement: AnnotationSelectionMenuProps['placement'];
  menuWrapperProps: AnnotationSelectionMenuProps['menuWrapperProps'];
}>();

const { provides: annotationCapability } = useAnnotationCapability();

const menuStyle = computed<CSSProperties>(() => ({
  position: 'absolute',
  pointerEvents: 'auto',
  cursor: 'default',
  top: `${props.rect.size.height + 8}px`,
}));

const handleDelete = () => {
  const annotationScope = annotationCapability.value?.forDocument(props.documentId);
  if (!annotationScope) return;

  const { pageIndex, id } = props.context.annotation.object;
  annotationScope.deleteAnnotation(pageIndex, id);
};
</script>

// examples/svelte-tailwind/src/lib/components/AnnotationSelectionMenu.svelte
<script lang="ts">
  import type { TrackedAnnotation } from '@embedpdf/plugin-annotation';
  import { useAnnotationCapability } from '@embedpdf/plugin-annotation/svelte';
  import { type MenuWrapperProps } from '@embedpdf/utils/svelte';
  import type { Rect } from '@embedpdf/models';
  import { Trash2 } from 'lucide-svelte';

  interface AnnotationSelectionMenuProps {
    selected: boolean;
    menuWrapperProps: MenuWrapperProps;
    annotation: TrackedAnnotation;
    rect: Rect;
  }

  let { menuWrapperProps, annotation, rect, selected }: AnnotationSelectionMenuProps = $props();

  const annotationCapability = useAnnotationCapability();

  function handleDelete() {
    if (!annotationCapability.provides) return;
    const { pageIndex, id } = annotation.object;
    annotationCapability.provides.deleteAnnotation(pageIndex, id);
  }
</script>

<span style={menuWrapperProps.style} use:menuWrapperProps.action>
  {#if selected}
    <div
      class="pointer-events-auto flex items-center gap-1 rounded-lg border border-gray-200 bg-white px-2 py-1 shadow-lg dark:border-gray-700 dark:bg-gray-800"
      style:position="absolute"
      style:top="{rect.size.height + 8}px"
      style:left="50%"
      style:transform="translateX(-50%)"
      style:z-index="1000"
      style:cursor="default"
    >
      <button
        onclick={handleDelete}
        class="flex items-center justify-center rounded p-1.5 text-gray-700 transition-colors hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-700"
        aria-label="Delete annotation"
      >
        <Trash2 size={18} />
      </button>
    </div>
  {/if}
</span>
