// examples/vue-tailwind/src/components/PageSettingsMenu.vue
<template>
  <div v-if="rotate && spread" class="relative">
    <ToolbarButton
      :onClick="() => (isOpen = !isOpen)"
      :isActive="isOpen"
      aria-label="Page Settings"
      title="Page Settings"
    >
      <SettingsIcon class="h-4 w-4" />
    </ToolbarButton>

    <DropdownMenu :isOpen="isOpen" :onClose="() => (isOpen = false)" className="w-56">
      <DropdownSection title="Page Orientation">
        <DropdownItem
          :onClick="
            () => {
              rotate?.rotateForward();
              isOpen = false;
            }
          "
        >
          <template #icon>
            <RotateRightIcon class="h-4 w-4" title="Rotate Clockwise" />
          </template>
          Rotate Clockwise
        </DropdownItem>
        <DropdownItem
          :onClick="
            () => {
              rotate?.rotateBackward();
              isOpen = false;
            }
          "
        >
          <template #icon>
            <RotateLeftIcon class="h-4 w-4" title="Rotate Counter-clockwise" />
          </template>
          Rotate Counter-clockwise
        </DropdownItem>
      </DropdownSection>

      <DropdownDivider />

      <DropdownSection title="Page Layout">
        <DropdownItem
          :onClick="
            () => {
              spread?.setSpreadMode(SpreadMode.None);
              isOpen = false;
            }
          "
          :isActive="spreadMode === SpreadMode.None"
        >
          <template #icon>
            <SinglePageIcon class="h-4 w-4" title="Single Page" />
          </template>
          Single Page
        </DropdownItem>
        <DropdownItem
          :onClick="
            () => {
              spread?.setSpreadMode(SpreadMode.Odd);
              isOpen = false;
            }
          "
          :isActive="spreadMode === SpreadMode.Odd"
        >
          <template #icon>
            <BookOpenIcon class="h-4 w-4" title="Odd Pages" />
          </template>
          Odd Pages
        </DropdownItem>
        <DropdownItem
          :onClick="
            () => {
              spread?.setSpreadMode(SpreadMode.Even);
              isOpen = false;
            }
          "
          :isActive="spreadMode === SpreadMode.Even"
        >
          <template #icon>
            <BookOpenIcon class="h-4 w-4" title="Even Pages" />
          </template>
          Even Pages
        </DropdownItem>
      </DropdownSection>
    </DropdownMenu>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useRotate } from '@embedpdf/plugin-rotate/vue';
import { useSpread, SpreadMode } from '@embedpdf/plugin-spread/vue';
import {
  SettingsIcon,
  RotateRightIcon,
  RotateLeftIcon,
  SinglePageIcon,
  BookOpenIcon,
} from './icons';
import { ToolbarButton, DropdownMenu, DropdownSection, DropdownItem, DropdownDivider } from './ui';

const props = defineProps<{
  documentId: string;
}>();

const { provides: rotate } = useRotate(() => props.documentId);
const { spreadMode, provides: spread } = useSpread(() => props.documentId);
const isOpen = ref(false);
</script>

// examples/react-tailwind/src/components/page-settings-menu.tsx
import { useState } from 'react';
import { useRotate } from '@embedpdf/plugin-rotate/react';
import { useSpread } from '@embedpdf/plugin-spread/react';
import { SpreadMode } from '@embedpdf/plugin-spread';
import {
  SettingsIcon,
  RotateRightIcon,
  RotateLeftIcon,
  SinglePageIcon,
  BookOpenIcon,
} from './icons';
import { ToolbarButton, DropdownMenu, DropdownSection, DropdownItem, DropdownDivider } from './ui';

type PageSettingsMenuProps = {
  documentId: string;
};

export function PageSettingsMenu({ documentId }: PageSettingsMenuProps) {
  const { provides: rotate } = useRotate(documentId);
  const { spreadMode, provides: spread } = useSpread(documentId);
  const [isOpen, setIsOpen] = useState(false);

  if (!rotate || !spread) return null;

  return (
    <div className="relative">
      <ToolbarButton
        onClick={() => setIsOpen(!isOpen)}
        isActive={isOpen}
        aria-label="Page Settings"
        title="Page Settings"
      >
        <SettingsIcon className="h-4 w-4" />
      </ToolbarButton>

      <DropdownMenu isOpen={isOpen} onClose={() => setIsOpen(false)} className="w-56">
        <DropdownSection title="Page Orientation">
          <DropdownItem
            onClick={() => {
              rotate.rotateForward();
              setIsOpen(false);
            }}
            icon={<RotateRightIcon className="h-4 w-4" title="Rotate Clockwise" />}
          >
            Rotate Clockwise
          </DropdownItem>
          <DropdownItem
            onClick={() => {
              rotate.rotateBackward();
              setIsOpen(false);
            }}
            icon={<RotateLeftIcon className="h-4 w-4" title="Rotate Counter-clockwise" />}
          >
            Rotate Counter-clockwise
          </DropdownItem>
        </DropdownSection>

        <DropdownDivider />

        <DropdownSection title="Page Layout">
          <DropdownItem
            onClick={() => {
              spread.setSpreadMode(SpreadMode.None);
              setIsOpen(false);
            }}
            icon={<SinglePageIcon className="h-4 w-4" title="Single Page" />}
            isActive={spreadMode === SpreadMode.None}
          >
            Single Page
          </DropdownItem>
          <DropdownItem
            onClick={() => {
              spread.setSpreadMode(SpreadMode.Odd);
              setIsOpen(false);
            }}
            icon={<BookOpenIcon className="h-4 w-4" title="Odd Pages" />}
            isActive={spreadMode === SpreadMode.Odd}
          >
            Odd Pages
          </DropdownItem>
          <DropdownItem
            onClick={() => {
              spread.setSpreadMode(SpreadMode.Even);
              setIsOpen(false);
            }}
            icon={<BookOpenIcon className="h-4 w-4" title="Even Pages" />}
            isActive={spreadMode === SpreadMode.Even}
          >
            Even Pages
          </DropdownItem>
        </DropdownSection>
      </DropdownMenu>
    </div>
  );
}
