// packages/core/src/vue/components/embed-pdf.vue
<script setup lang="ts">
import { ref, provide, onMounted, onBeforeUnmount, shallowRef, computed } from 'vue';
import {
  PluginRegistry,
  PluginBatchRegistrations,
  PluginRegistryConfig,
  CoreState,
  DocumentState,
} from '@embedpdf/core';
import { Logger, PdfEngine } from '@embedpdf/models';
import { pdfKey, PDFContextState } from '../context';
import AutoMount from './auto-mount.vue';

export type { PluginBatchRegistrations };

const props = withDefaults(
  defineProps<{
    engine: PdfEngine;
    /** Registry configuration including logger, permissions, and defaults. */
    config?: PluginRegistryConfig;
    /** @deprecated Use config.logger instead. Will be removed in next major version. */
    logger?: Logger;
    plugins: PluginBatchRegistrations;
    onInitialized?: (registry: PluginRegistry) => Promise<void>;
    autoMountDomElements?: boolean;
  }>(),
  {
    autoMountDomElements: true,
  },
);

/* reactive state */
const registry = shallowRef<PluginRegistry | null>(null);
const coreState = ref<CoreState | null>(null);
const isInit = ref(true);
const pluginsOk = ref(false);

// Compute convenience accessors
const activeDocumentId = computed(() => coreState.value?.activeDocumentId ?? null);
const documents = computed(() => coreState.value?.documents ?? {});
const documentOrder = computed(() => coreState.value?.documentOrder ?? []);

const activeDocument = computed(() => {
  const docId = activeDocumentId.value;
  const docs = documents.value;
  return docId && docs[docId] ? docs[docId] : null;
});

const documentStates = computed(() => {
  const docs = documents.value;
  const order = documentOrder.value;
  return order
    .map((docId) => docs[docId])
    .filter((doc): doc is DocumentState => doc !== null && doc !== undefined);
});

/* expose to children */
provide<PDFContextState>(pdfKey, {
  registry,
  coreState,
  isInitializing: isInit,
  pluginsReady: pluginsOk,
  activeDocumentId,
  activeDocument,
  documents,
  documentStates,
});

let unsubscribe: () => void | undefined;
onMounted(async () => {
  // Merge deprecated logger prop into config (config.logger takes precedence)
  const finalConfig: PluginRegistryConfig = {
    ...props.config,
    logger: props.config?.logger ?? props.logger,
  };
  const reg = new PluginRegistry(props.engine, finalConfig);
  reg.registerPluginBatch(props.plugins);
  await reg.initialize();

  if (reg.isDestroyed()) {
    return;
  }

  const store = reg.getStore();
  coreState.value = store.getState().core;

  unsubscribe = store.subscribe((action, newState, oldState) => {
    // Only update if it's a core action and the core state changed
    if (store.isCoreAction(action) && newState.core !== oldState.core) {
      coreState.value = newState.core;
    }
  });

  await props.onInitialized?.(reg);

  if (reg.isDestroyed()) {
    unsubscribe();
    return;
  }

  registry.value = reg;
  isInit.value = false;

  reg.pluginsReady().then(() => {
    if (!reg.isDestroyed()) {
      pluginsOk.value = true;
    }
  });
});

onBeforeUnmount(() => {
  unsubscribe?.();
  registry.value?.destroy();
});

</script>

<template>
  <AutoMount v-if="pluginsOk && autoMountDomElements" :plugins="plugins">
    <!-- scoped slot keeps API parity with React version -->
    <slot
      :registry="registry"
      :coreState="coreState"
      :isInitializing="isInit"
      :pluginsReady="pluginsOk"
      :activeDocumentId="activeDocumentId"
      :activeDocument="activeDocument"
      :documents="documents"
      :documentStates="documentStates"
    />
  </AutoMount>

  <!-- No auto-mount or not ready yet -->
  <slot
    v-else
    :registry="registry"
    :coreState="coreState"
    :isInitializing="isInit"
    :pluginsReady="pluginsOk"
    :activeDocumentId="activeDocumentId"
    :activeDocument="activeDocument"
    :documents="documents"
    :documentStates="documentStates"
  />
</template>

// packages/core/src/svelte/components/EmbedPDF.svelte
<script lang="ts">
  import type { Logger, PdfEngine } from '@embedpdf/models';
  import {
    type IPlugin,
    type PluginBatchRegistrations,
    type PluginRegistryConfig,
    PluginRegistry,
  } from '@embedpdf/core';
  import { type Snippet } from 'svelte';
  import AutoMount from './AutoMount.svelte';
  import { createPdfContext, setPdfContext, type PDFContextState } from '../hooks';

  export type { PluginBatchRegistrations };

  interface EmbedPDFProps {
    /**
     * The PDF engine to use for the PDF viewer.
     */
    engine: PdfEngine;
    /**
     * Registry configuration including logger, permissions, and defaults.
     */
    config?: PluginRegistryConfig;
    /**
     * @deprecated Use config.logger instead. Will be removed in next major version.
     */
    logger?: Logger;
    /**
     * The callback to call when the PDF viewer is initialized.
     */
    onInitialized?: (registry: PluginRegistry) => Promise<void>;
    /**
     * The plugins to use for the PDF viewer.
     */
    plugins: PluginBatchRegistrations;
    /**
     * The children to render for the PDF viewer.
     */
    children: Snippet<[PDFContextState]>;
    /**
     * Whether to auto-mount specific non-visual DOM elements from plugins.
     * @default true
     */
    autoMountDomElements?: boolean;
  }

  let {
    engine,
    config,
    logger,
    onInitialized,
    plugins,
    children,
    autoMountDomElements = true,
  }: EmbedPDFProps = $props();

  // This instance's own context. Publishing it here means everything rendered
  // below resolves this registry, so sibling <EmbedPDF> instances stay isolated.
  const pdfContext = createPdfContext();
  setPdfContext(pdfContext);

  let latestInit = onInitialized;

  $effect(() => {
    if (onInitialized) {
      latestInit = onInitialized;
    }
  });

  $effect(() => {
    if (engine || (engine && plugins)) {
      // Merge deprecated logger prop into config (config.logger takes precedence)
      const finalConfig: PluginRegistryConfig = {
        ...config,
        logger: config?.logger ?? logger,
      };
      const reg = new PluginRegistry(engine, finalConfig);
      reg.registerPluginBatch(plugins);

      const initialize = async () => {
        await reg.initialize();

        // if the registry is destroyed, don't do anything
        if (reg.isDestroyed()) {
          return;
        }

        const store = reg.getStore();
        pdfContext.coreState = store.getState().core;

        const unsubscribe = store.subscribe((action, newState, oldState) => {
          // Only update if it's a core action and the core state changed
          if (store.isCoreAction(action) && newState.core !== oldState.core) {
            pdfContext.coreState = newState.core;

            // Update convenience accessors
            const activeDocumentId = newState.core.activeDocumentId ?? null;
            const documents = newState.core.documents ?? {};
            const documentOrder = newState.core.documentOrder ?? [];

            pdfContext.activeDocumentId = activeDocumentId;
            pdfContext.activeDocument =
              activeDocumentId && documents[activeDocumentId] ? documents[activeDocumentId] : null;
            pdfContext.documents = documents;
            pdfContext.documentStates = documentOrder
              .map((docId) => documents[docId])
              .filter(
                (doc): doc is import('@embedpdf/core').DocumentState =>
                  doc !== null && doc !== undefined,
              );
          }
        });

        /* always call the *latest* callback */
        await latestInit?.(reg);

        // if the registry is destroyed, don't do anything
        if (reg.isDestroyed()) {
          unsubscribe();
          return;
        }

        reg.pluginsReady().then(() => {
          if (!reg.isDestroyed()) {
            pdfContext.pluginsReady = true;
          }
        });

        // Provide the registry to children via context
        pdfContext.registry = reg;
        pdfContext.isInitializing = false;

        return unsubscribe;
      };

      let cleanup: (() => void) | undefined;
      initialize()
        .then((unsub) => {
          cleanup = unsub;
        })
        .catch(console.error);

      return () => {
        cleanup?.();
        reg.destroy();
        pdfContext.registry = null;
        pdfContext.coreState = null;
        pdfContext.isInitializing = true;
        pdfContext.pluginsReady = false;
        pdfContext.activeDocumentId = null;
        pdfContext.activeDocument = null;
        pdfContext.documents = {};
        pdfContext.documentStates = [];
      };
    }
  });
</script>

{#if pdfContext.pluginsReady && autoMountDomElements}
  <AutoMount {plugins}>{@render children(pdfContext)}</AutoMount>
{:else}
  {@render children(pdfContext)}
{/if}
