// website/src/samples/snippets/annotations/selecting-style-panel.react.tsx
import { useAnnotation, useSelectionFields } from '@embedpdf/react/annotation';
import { Control } from './control'; // your own control

export function StylePanel() {
  const annotation = useAnnotation();
  const { fields, values, mixed } = useSelectionFields();

  return fields.map((field) => (
    <Control
      key={field.key}
      field={field}
      value={values[field.key]}
      mixed={mixed.includes(field.key)}
      onChange={(value) => annotation.selection.update({ [field.key]: value })}
    />
  ));
}

// docs/content/snippets/annotations/selecting-style-panel.svelte.svelte
<script lang="ts">
  import { useAnnotation, useSelectionFields } from '@embedpdf/svelte/annotation';
  import Control from './Control.svelte'; // your own control

  const annotation = useAnnotation();
  const panel = useSelectionFields(); // panel.current: { fields, values, mixed }
</script>

{#each panel.current.fields as field (field.key)}
  <Control
    {field}
    value={panel.current.values[field.key]}
    mixed={panel.current.mixed.includes(field.key)}
    onchange={(value) => annotation.selection.update({ [field.key]: value })}
  />
{/each}
