// examples/angular-tailwind/src/examples/viewer/spread-example.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  computed,
  inject,
  signal,
} from '@angular/core';
import {
  PDFViewer,
  type PluginRegistry,
  SpreadMode,
  type SpreadPlugin,
  type SpreadScope,
} from '@embedpdf/angular-pdf-viewer';

import {
  DEMO_DOCUMENT_URL,
  createThemeConfig,
  createThemePreferenceSignal,
} from '../../example-support';

export const selector = 'spread-example';

@Component({
  selector,
  imports: [PDFViewer],
  template: `
    <div class="flex flex-col gap-4">
      <div
        class="flex flex-wrap items-center gap-2 rounded-lg border border-gray-200 bg-gray-50 p-2 dark:border-gray-700 dark:bg-gray-800"
      >
        <span class="px-2 text-sm font-medium text-gray-600 dark:text-gray-300">
          Layout Mode:
        </span>
        <div class="flex gap-1">
          @for (option of options; track option.mode) {
            <button
              type="button"
              class="flex items-center gap-2 rounded px-3 py-1.5 text-sm font-medium transition-colors"
              [class.bg-white]="currentMode() === option.mode"
              [class.text-blue-600]="currentMode() === option.mode"
              [class.shadow-sm]="currentMode() === option.mode"
              [class.dark:bg-gray-700]="currentMode() === option.mode"
              [class.dark:text-blue-400]="currentMode() === option.mode"
              [class.text-gray-600]="currentMode() !== option.mode"
              [class.hover:bg-gray-200]="currentMode() !== option.mode"
              [class.dark:text-gray-400]="currentMode() !== option.mode"
              [class.dark:hover:bg-gray-700]="currentMode() !== option.mode"
              (click)="setMode(option.mode)"
            >
              {{ option.label }}
            </button>
          }
        </div>
      </div>

      <div
        class="h-[600px] w-full overflow-hidden rounded-xl border border-gray-300 shadow-lg dark:border-gray-600"
      >
        <embedpdf-viewer
          class="block h-full w-full"
          [config]="viewerConfig()"
          (ready)="onReady($event)"
        />
      </div>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export default class SpreadExample {
  private readonly destroyRef = inject(DestroyRef);
  readonly themePreference = createThemePreferenceSignal();
  readonly theme = createThemeConfig(this.themePreference);
  readonly docSpread = signal<SpreadScope | null>(null);
  readonly currentMode = signal<SpreadMode>(SpreadMode.None);
  readonly options = [
    { mode: SpreadMode.None, label: 'Single Page' },
    { mode: SpreadMode.Odd, label: 'Two-Page (Odd)' },
    { mode: SpreadMode.Even, label: 'Two-Page (Even)' },
  ] as const;
  readonly viewerConfig = computed(() => ({
    theme: this.theme(),
    spread: {
      defaultSpreadMode: SpreadMode.None,
    },
    documentManager: {
      initialDocuments: [
        {
          url: DEMO_DOCUMENT_URL,
          documentId: 'spread-doc',
        },
      ],
    },
  }));

  onReady(registry: PluginRegistry) {
    const spreadScope = registry
      .getPlugin<SpreadPlugin>('spread')
      ?.provides()
      ?.forDocument('spread-doc');
    if (!spreadScope) return;

    this.docSpread.set(spreadScope);
    this.currentMode.set(spreadScope.getSpreadMode());

    const cleanup = spreadScope.onSpreadChange((mode) => {
      this.currentMode.set(mode);
    });
    this.destroyRef.onDestroy(cleanup);
  }

  setMode(mode: SpreadMode) {
    this.docSpread()?.setSpreadMode(mode);
  }
}

// examples/svelte-tailwind/src/examples/viewer/spread-example.svelte
<script lang="ts">
  import {
    PDFViewer,
    type EmbedPdfContainer,
    type PluginRegistry,
    type SpreadPlugin,
    type SpreadScope,
    SpreadMode,
  } from '@embedpdf/svelte-pdf-viewer';
  import { File, BookOpen, Book } from 'lucide-svelte';

  interface Props {
    themePreference?: 'light' | 'dark';
  }

  let { themePreference = 'light' }: Props = $props();

  let container = $state<EmbedPdfContainer | null>(null);
  let docSpread = $state<SpreadScope | null>(null);
  let currentMode = $state<SpreadMode>(SpreadMode.None);

  const handleInit = (c: EmbedPdfContainer) => {
    container = c;
  };

  const handleReady = (registry: PluginRegistry) => {
    const spreadPlugin = registry.getPlugin<SpreadPlugin>('spread')?.provides();
    if (spreadPlugin) {
      docSpread = spreadPlugin.forDocument('spread-doc');
    }
  };

  $effect(() => {
    container?.setTheme({ preference: themePreference });
  });

  const setSpreadMode = (mode: SpreadMode) => {
    docSpread?.setSpreadMode(mode);
    currentMode = mode;
  };
</script>

<div class="flex flex-col gap-4">
  <!-- External Controls -->
  <div
    class="flex flex-wrap items-center gap-2 rounded-lg border border-gray-200 bg-gray-50 p-2 dark:border-gray-700 dark:bg-gray-800"
  >
    <span class="px-2 text-sm font-medium text-gray-600 dark:text-gray-300"> Layout Mode: </span>
    <div class="flex gap-1">
      <button
        type="button"
        onclick={() => setSpreadMode(SpreadMode.None)}
        class="flex items-center gap-2 rounded px-3 py-1.5 text-sm font-medium transition-colors {currentMode ===
        SpreadMode.None
          ? 'bg-white text-blue-600 shadow-sm dark:bg-gray-700 dark:text-blue-400'
          : 'text-gray-600 hover:bg-gray-200 dark:text-gray-400 dark:hover:bg-gray-700'}"
      >
        <File size={16} />
        Single Page
      </button>
      <button
        type="button"
        onclick={() => setSpreadMode(SpreadMode.Odd)}
        class="flex items-center gap-2 rounded px-3 py-1.5 text-sm font-medium transition-colors {currentMode ===
        SpreadMode.Odd
          ? 'bg-white text-blue-600 shadow-sm dark:bg-gray-700 dark:text-blue-400'
          : 'text-gray-600 hover:bg-gray-200 dark:text-gray-400 dark:hover:bg-gray-700'}"
      >
        <BookOpen size={16} />
        Two-Page (Odd)
      </button>
      <button
        type="button"
        onclick={() => setSpreadMode(SpreadMode.Even)}
        class="flex items-center gap-2 rounded px-3 py-1.5 text-sm font-medium transition-colors {currentMode ===
        SpreadMode.Even
          ? 'bg-white text-blue-600 shadow-sm dark:bg-gray-700 dark:text-blue-400'
          : 'text-gray-600 hover:bg-gray-200 dark:text-gray-400 dark:hover:bg-gray-700'}"
      >
        <Book size={16} />
        Two-Page (Even)
      </button>
    </div>
  </div>

  <!-- Viewer -->
  <div
    class="h-[500px] w-full overflow-hidden rounded-xl border border-gray-300 shadow-lg dark:border-gray-600"
  >
    <PDFViewer
      oninit={handleInit}
      onready={handleReady}
      config={{
        theme: { preference: themePreference },
        spread: {
          defaultSpreadMode: SpreadMode.None,
        },
        documentManager: {
          initialDocuments: [
            {
              url: 'https://snippet.embedpdf.com/ebook.pdf',
              documentId: 'spread-doc',
            },
          ],
        },
      }}
      style="width: 100%; height: 100%;"
    />
  </div>
</div>
