// cloudpdf/website/src/samples/snippets/annotations/redaction/pending.vue.vue
<script setup lang="ts">
import { annotationKey } from '@embedpdf/vue/annotation';
import { usePendingRedactions, useRedaction } from '@embedpdf/vue/redaction';
import { useStage } from '@embedpdf/vue/stage';

const stage = useStage();
const redaction = useRedaction();
const marks = usePendingRedactions();
</script>

<template>
  <ul>
    <li v-for="mark in marks" :key="annotationKey(mark.ref)">
      <button @click="stage.reveal(mark.page, { rect: mark.bounds })">
        Page {{ mark.pageIndex + 1 }}: {{ mark.kind === 'text' ? 'text' : 'area' }}
      </button>
      <button @click="redaction.unmark([mark.ref])">Remove</button>
    </li>
  </ul>
</template>

// docs/content/snippets/annotations/redaction/pending.react.tsx
import { annotationKey } from '@embedpdf/react/annotation';
import { usePendingRedactions, useRedaction } from '@embedpdf/react/redaction';
import { useStage } from '@embedpdf/react/stage';

export function Pending() {
  const stage = useStage();
  const redaction = useRedaction();
  const marks = usePendingRedactions();

  return (
    <ul>
      {marks.map((mark) => (
        <li key={annotationKey(mark.ref)}>
          <button onClick={() => stage.reveal(mark.page, { rect: mark.bounds })}>
            Page {mark.pageIndex + 1}: {mark.kind === 'text' ? 'text' : 'area'}
          </button>
          <button onClick={() => redaction.unmark([mark.ref])}>Remove</button>
        </li>
      ))}
    </ul>
  );
}
