// packages/plugin-i18n/src/shared/components/translate.tsx
import { ReactNode } from '@framework';
import { useTranslation } from '../hooks';

interface TranslateProps {
  k: string; // translation key
  params?: Record<string, string | number>;
  children?: (translation: string) => ReactNode;
}

/**
 * Component for inline translation
 * @example <Translate k="commands.zoom.in" />
 * @example <Translate k="commands.zoom.level" params={{ level: 150 }} />
 */
export function Translate({ k, params, children }: TranslateProps) {
  const translation = useTranslation(k, params);

  if (children) {
    return children(translation);
  }

  return translation;
}

// packages/plugin-i18n/src/svelte/components/Translate.svelte
<script lang="ts">
  import { useTranslation } from '../hooks/use-i18n.svelte';

  interface TranslateProps {
    k: string;
    params?: Record<string, string | number>;
  }

  let { k, params }: TranslateProps = $props();

  const translation = useTranslation(
    () => k,
    () => params,
  );
</script>

{translation.current}
