// packages/framework/svelte/src/toolbar/DefaultOverflowMenu.svelte
<!--
  The default "More" menu: a minimal popover under its button, one section after another. A row
  that opens a submenu keeps the menu open; every other row closes it after running.
-->
<script lang="ts">
  import type { OverflowRow } from '@embedpdf/core-ui';
  import { observeOutsidePress } from '@embedpdf/web';
  import type { OverflowMenuView } from './views';
  import { BORDER, SURFACE } from './paint';

  let { view }: { view: OverflowMenuView } = $props();
  let menu = $state<HTMLElement | null>(null);

  $effect(() => {
    // The menu's parent holds its button too: a press on it is the button's own toggle.
    const container = menu?.parentElement ?? menu;
    if (!view.isOpen || !container) return;
    return observeOutsidePress(container, () => view.close());
  });

  function choose(row: OverflowRow) {
    view.execute(row.command);
    if (row.type !== 'submenu') view.close();
  }
</script>

{#if view.isOpen}
  <!-- A press anywhere outside the menu closes it; Escape is the app's to add. -->
  <div
    bind:this={menu}
    role="menu"
    style:position="absolute"
    style:right="0"
    style:top="100%"
    style:z-index="41"
    style:min-width="200px"
    style:padding="4px"
    style:background={SURFACE}
    style:border="1px solid {BORDER}"
    style:border-radius="6px"
    style:box-shadow="0 4px 16px rgba(0,0,0,0.15)"
  >
    {#each view.sections as section, index (index)}
      {#if index > 0}
        <div style:height="1px" style:background={BORDER} style:margin="4px 0"></div>
      {/if}
      {#each section.rows as row (row.command)}
        {@const command = view.resolve(row.command)}
        {#if command}
          <button
            type="button"
            role={section.role === 'radio' ? 'menuitemradio' : 'menuitem'}
            aria-checked={section.role === 'radio' ? command.active : undefined}
            disabled={!command.enabled}
            onclick={() => choose(row)}
            style:display="flex"
            style:width="100%"
            style:align-items="center"
            style:justify-content="space-between"
            style:gap="16px"
            style:padding="6px 8px"
            style:border="none"
            style:color="inherit"
            style:font="inherit"
            style:background="transparent"
            style:cursor={command.enabled ? 'pointer' : 'default'}
            style:opacity={command.enabled ? 1 : 0.4}
            style:white-space="nowrap"
          >
            <span>{command.active && section.role === 'radio' ? '• ' : ''}{command.label}</span>
            {#if row.type === 'submenu'}<span>▸</span>{/if}
          </button>
        {/if}
      {/each}
    {/each}
  </div>
{/if}

// packages/framework/vue/src/toolbar/DefaultOverflowMenu.vue
<!--
  The default "More" menu: a minimal popover under its button, which a press
  anywhere outside it closes. A row that opens a submenu stays open; every
  other row closes the menu after it runs.
-->
<script setup lang="ts">
import { computed, ref, watchEffect } from 'vue';
import type { OverflowRow } from '@embedpdf/core-ui';
import { observeOutsidePress } from '@embedpdf/web';
import type { OverflowMenuView } from './views';
import { BORDER, SURFACE } from './paint';

const props = defineProps<{ view: OverflowMenuView }>();

const menu = ref<HTMLElement | null>(null);
watchEffect(
  (onCleanup) => {
    // The menu's parent holds its button too: a press on it is the button's own toggle.
    const container = menu.value?.parentElement ?? menu.value;
    if (!props.view.isOpen || !container) return;
    onCleanup(observeOutsidePress(container, () => props.view.close()));
  },
  { flush: 'post' },
);

// Each row with its command resolved; a row whose command is unknown isn't drawn.
const sections = computed(() =>
  props.view.sections.map((section) => ({
    radio: section.role === 'radio',
    rows: section.rows.flatMap((row) => {
      const command = props.view.resolve(row.command);
      return command ? [{ row, command }] : [];
    }),
  })),
);

function choose(row: OverflowRow) {
  props.view.execute(row.command);
  if (row.type !== 'submenu') props.view.close();
}
</script>

<template>
  <div
    v-if="view.isOpen"
    ref="menu"
    role="menu"
    :style="{
      position: 'absolute',
      right: 0,
      top: '100%',
      zIndex: 41,
      minWidth: '200px',
      padding: '4px',
      background: SURFACE,
      border: `1px solid ${BORDER}`,
      borderRadius: '6px',
      boxShadow: '0 4px 16px rgba(0,0,0,0.15)',
    }"
  >
    <template v-for="(section, index) in sections" :key="index">
      <div v-if="index > 0" :style="{ height: '1px', background: BORDER, margin: '4px 0' }" />
      <button
        v-for="{ row, command } in section.rows"
        :key="row.command"
        type="button"
        :role="section.radio ? 'menuitemradio' : 'menuitem'"
        :aria-checked="section.radio ? command.active : undefined"
        :disabled="!command.enabled"
        :style="{
          display: 'flex',
          width: '100%',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: '16px',
          padding: '6px 8px',
          border: 'none',
          color: 'inherit',
          font: 'inherit',
          background: 'transparent',
          cursor: command.enabled ? 'pointer' : 'default',
          opacity: command.enabled ? 1 : 0.4,
          whiteSpace: 'nowrap',
        }"
        @click="choose(row)"
      >
        <span>{{ command.active && section.radio ? '• ' : '' }}{{ command.label }}</span>
        <span v-if="row.type === 'submenu'">▸</span>
      </button>
    </template>
  </div>
</template>
