// packages/plugin-redaction/src/vue/components/redaction-layer.vue
<template>
  <PendingRedactions
    :document-id="documentId"
    :page-index="pageIndex"
    :scale="actualScale"
    :rotation="actualRotation"
    :bbox-stroke="bboxStroke"
    :selection-menu="selectionMenu"
  >
    <template #selection-menu="slotProps">
      <slot name="selection-menu" v-bind="slotProps" />
    </template>
  </PendingRedactions>
  <MarqueeRedact :document-id="documentId" :page-index="pageIndex" :scale="actualScale" />
  <SelectionRedact :document-id="documentId" :page-index="pageIndex" :scale="actualScale" />
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useDocumentState } from '@embedpdf/core/vue';
import { Rotation } from '@embedpdf/models';
import PendingRedactions from './pending-redactions.vue';
import MarqueeRedact from './marquee-redact.vue';
import SelectionRedact from './selection-redact.vue';
import { RedactionSelectionMenuRenderFn } from './types';

interface RedactionLayerProps {
  /** The ID of the document this layer belongs to */
  documentId: string;
  /** Index of the page this layer lives on */
  pageIndex: number;
  /** Current render scale for this page */
  scale?: number;
  /** Page rotation (for counter-rotating menus, etc.) */
  rotation?: Rotation;
  /** Optional bbox stroke color */
  bboxStroke?: string;
  /** Optional menu renderer for a selected redaction */
  selectionMenu?: RedactionSelectionMenuRenderFn;
}

const props = withDefaults(defineProps<RedactionLayerProps>(), {
  bboxStroke: 'rgba(0,0,0,0.8)',
});

const documentState = useDocumentState(() => props.documentId);

const actualScale = computed(() => {
  if (props.scale !== undefined) return props.scale;
  return documentState.value?.scale ?? 1;
});

const actualRotation = computed(() => {
  if (props.rotation !== undefined) return props.rotation;
  return documentState.value?.rotation ?? Rotation.Degree0;
});
</script>

// packages/plugin-redaction/src/shared/components/redaction-layer.tsx
import { Fragment, useMemo } from '@framework';
import { useDocumentState } from '@embedpdf/core/@framework';
import { MarqueeRedact } from './marquee-redact';
import { SelectionRedact } from './selection-redact';
import { PendingRedactions } from './pending-redactions';
import { Rotation } from '@embedpdf/models';
import { RedactionSelectionMenuRenderFn } from './types';

interface RedactionLayerProps {
  /** The ID of the document this layer belongs to */
  documentId: string;
  /** Index of the page this layer lives on */
  pageIndex: number;
  /** Current render scale for this page */
  scale?: number;
  /** Page rotation (for counter-rotating menus, etc.) */
  rotation?: Rotation;
  /** Optional menu renderer for a selected redaction */
  selectionMenu?: RedactionSelectionMenuRenderFn;
}

export const RedactionLayer = ({
  documentId,
  pageIndex,
  scale,
  rotation,
  selectionMenu,
}: RedactionLayerProps) => {
  const documentState = useDocumentState(documentId);

  const actualScale = useMemo(() => {
    if (scale !== undefined) return scale;
    return documentState?.scale ?? 1;
  }, [scale, documentState?.scale]);

  const actualRotation = useMemo(() => {
    if (rotation !== undefined) return rotation;
    return documentState?.rotation ?? Rotation.Degree0;
  }, [rotation, documentState?.rotation]);

  return (
    <Fragment>
      <PendingRedactions
        documentId={documentId}
        pageIndex={pageIndex}
        scale={actualScale}
        rotation={actualRotation}
        selectionMenu={selectionMenu}
      />
      <MarqueeRedact documentId={documentId} pageIndex={pageIndex} scale={actualScale} />
      <SelectionRedact documentId={documentId} pageIndex={pageIndex} scale={actualScale} />
    </Fragment>
  );
};
