// packages/framework/vue/src/annotation/AnnotationChrome.vue
<!--
  The selection's chrome on one page: its outline, handles, rotation handle,
  snapping guides, the lines of a turn in progress and the box dragged to
  select. The plugin lists the nodes and sizes the screen-constant parts for
  the page's zoom; `@embedpdf/web` puts them in pixels and paints them through
  their `--epdf-annotation-*` variables. The layer draws them as SVG; a
  `#handle` or `#rotation-handle` slot draws its handles as HTML over the page
  instead. The viewer still decides where a handle can be grabbed, so what a
  slot draws can't break dragging.
-->
<script setup lang="ts">
import { computed } from 'vue';
import type { CSSProperties } from 'vue';
import { shallowEqual } from '@embedpdf/core';
import type { ChromeNode } from '@embedpdf/core-annotation';
import { AnnotationToken as AnnotationHostToken } from '@embedpdf/plugin-annotation/contract/host';
import { annotationChromePaint, chromeInPixels } from '@embedpdf/web';
import { useOptionalSelector } from '../runtime/capabilities';
import { useViewerSettings } from '../runtime/documents';
import type { PageContextValue } from '../runtime/page';
import { useAnnotationSettings } from './state';
import type { HandleProps, RotationHandleProps } from './types';

const props = defineProps<{ page: PageContextValue }>();

const slots = defineSlots<{
  /** One handle, drawn your way. */
  handle?(props: HandleProps): unknown;
  /** The rotation handle, drawn your way. */
  'rotation-handle'?(props: RotationHandleProps): unknown;
}>();

const NO_NODES: readonly ChromeNode[] = Object.freeze([]);

// The page's view scale converts the screen-pixel chrome settings into
// content units inside the plugin (the rotation handle's offset, grab zones):
// screen-constant at every zoom. What this draws is in screen pixels already.
const nodes = useOptionalSelector(
  AnnotationHostToken,
  (host) => {
    const { transform, ref } = props.page;
    return host.listChromeNodes(ref, transform.viewScale, transform.rotation, transform.zoom);
  },
  NO_NODES,
  shallowEqual,
);
const chrome = useAnnotationSettings((settings) => settings.chrome);
const accent = useViewerSettings((settings) => settings.accent);
/**
 * The chrome settings, painted, as each part's `style`: follows the settings
 * and the viewer's accent live. Paint goes in `style`, never in SVG
 * attributes, which don't read the `var(--epdf-…)` the paint starts with.
 */
const painted = computed(() => {
  const paint = annotationChromePaint(chrome.value, accent.value);
  const style = (part: object): CSSProperties => ({ ...part });
  return {
    outline: style(paint.outline),
    handle: style(paint.handle),
    rotationHandle: style(paint.rotationHandle),
    rotationStalk: style({ stroke: paint.rotationHandle.stroke }),
    guide: style(paint.guide),
    rotationGuide: style(paint.rotationGuide),
    marquee: style(paint.marquee),
  };
});
const pixels = computed(() => chromeInPixels(nodes.value, props.page.transform));

/** Whether there are handles a slot could draw: the slots' own element exists only then. */
const hasHandles = computed(() =>
  pixels.value.some((node) => node.kind === 'handle' || node.kind === 'rotation-handle'),
);
</script>

<template>
  <svg :style="{ position: 'absolute', inset: 0, overflow: 'visible', pointerEvents: 'none' }">
    <template v-for="(node, index) in pixels" :key="index">
      <template v-if="node.kind === 'handle'">
        <template v-if="!slots.handle">
          <circle
            v-if="chrome.handles.shape === 'circle'"
            :cx="node.at.x"
            :cy="node.at.y"
            :r="chrome.handles.size / 2"
            stroke-width="1.5"
            :style="painted.handle"
          />
          <!-- The square rides a turned box's orientation (it spins about itself). -->
          <rect
            v-else
            :x="node.at.x - chrome.handles.size / 2"
            :y="node.at.y - chrome.handles.size / 2"
            :width="chrome.handles.size"
            :height="chrome.handles.size"
            stroke-width="1.5"
            :style="painted.handle"
            :transform="node.rotation ? `rotate(${node.rotation} ${node.at.x} ${node.at.y})` : undefined"
          />
        </template>
      </template>
      <line
        v-else-if="node.kind === 'guide'"
        :x1="node.from.x"
        :y1="node.from.y"
        :x2="node.to.x"
        :y2="node.to.y"
        shape-rendering="crispEdges"
        :style="painted.guide"
      />
      <polygon
        v-else-if="node.kind === 'turned-outline'"
        :points="node.points"
        fill="none"
        :style="painted.outline"
      />
      <g v-else-if="node.kind === 'rotation-guides'">
        <line
          v-for="(line, lineIndex) in node.lines"
          :key="lineIndex"
          :x1="line.from.x"
          :y1="line.from.y"
          :x2="line.to.x"
          :y2="line.to.y"
          :opacity="line.opacity"
          :style="painted.rotationGuide"
        />
      </g>
      <template v-else-if="node.kind === 'rotation-handle'">
        <g v-if="!slots['rotation-handle']">
          <line
            v-if="chrome.rotationHandle.stalk"
            :x1="node.from.x"
            :y1="node.from.y"
            :x2="node.at.x"
            :y2="node.at.y"
            stroke-width="1"
            :style="painted.rotationStalk"
          />
          <circle
            :cx="node.at.x"
            :cy="node.at.y"
            :r="chrome.rotationHandle.size / 2"
            stroke-width="1.5"
            :style="painted.rotationHandle"
          />
        </g>
      </template>
      <!-- The box dragged to select keeps its own look (a see-through accent
           fill, always dashed); the selection outline follows the settings. -->
      <rect
        v-else-if="node.kind === 'marquee'"
        :x="node.box.left"
        :y="node.box.top"
        :width="node.box.width"
        :height="node.box.height"
        stroke-width="1"
        stroke-dasharray="4 3"
        :style="painted.marquee"
      />
      <rect
        v-else-if="node.kind === 'outline'"
        :x="node.box.left"
        :y="node.box.top"
        :width="node.box.width"
        :height="node.box.height"
        fill="none"
        :style="painted.outline"
      />
    </template>
  </svg>
  <div
    v-if="hasHandles && (slots.handle || slots['rotation-handle'])"
    :style="{ position: 'absolute', inset: 0, pointerEvents: 'none' }"
  >
    <template v-for="(node, index) in pixels" :key="index">
      <slot
        v-if="node.kind === 'handle' && slots.handle"
        name="handle"
        :at="node.at"
        :size="chrome.handles.size"
        :rotation="node.rotation"
        :kind="node.role"
        :active="node.active"
      />
      <slot
        v-else-if="node.kind === 'rotation-handle' && slots['rotation-handle']"
        name="rotation-handle"
        :at="node.at"
        :from="node.from"
        :size="chrome.rotationHandle.size"
        :rotation="0"
        :active="false"
      />
    </template>
  </div>
</template>

// packages/framework/svelte/src/annotation/AnnotationChrome.svelte
<!--
  The selection's chrome on one page: its outline (turned with a turned selection), the resize
  and point handles, the rotation handle, a snapped move's guides, a turn's guides and the box
  dragged to select. The plugin lists the parts in page points; `@embedpdf/web` puts them in
  pixels and paints them, so their `--epdf-annotation-*` CSS variables win. The layer's handles
  are SVG; your `handle` and `rotationHandle` snippets draw as HTML over the page instead.
-->
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { ChromeNode } from '@embedpdf/core-annotation';
  // The chrome is a host read (the same runtime token, typed wider).
  import { AnnotationToken as AnnotationHostToken } from '@embedpdf/plugin-annotation/contract/host';
  import { chromeInPixels } from '@embedpdf/web';
  import type { PageContextValue } from '../runtime/page';
  import { shallowArray, useOptionalSelector } from '../runtime/readers.svelte';
  import { useChromePaint } from './chrome-paint.svelte';
  import type { HandleProps, RotationHandleProps } from './props';

  let {
    page,
    handle,
    rotationHandle,
  }: {
    page: PageContextValue;
    handle?: Snippet<[handle: HandleProps]>;
    rotationHandle?: Snippet<[handle: RotationHandleProps]>;
  } = $props();

  const NO_NODES: readonly ChromeNode[] = Object.freeze([]);

  // The page's view scale turns the screen-pixel chrome settings into page units inside the
  // plugin (the rotation handle's offset, the grab zones): constant on screen at every zoom.
  // What this draws is in screen pixels already.
  const nodes = useOptionalSelector(
    AnnotationHostToken,
    (annotation) =>
      annotation.listChromeNodes(
        page.ref,
        page.transform.viewScale,
        page.transform.rotation,
        page.transform.zoom,
      ),
    NO_NODES,
    shallowArray,
  );
  const paint = useChromePaint();
  const parts = $derived(chromeInPixels(nodes.current, page.transform));
  const yours = $derived(
    parts.filter(
      (part) =>
        (part.kind === 'handle' && handle) || (part.kind === 'rotation-handle' && rotationHandle),
    ),
  );
</script>

<svg style="position: absolute; inset: 0; overflow: visible; pointer-events: none">
  {#each parts as part, index (index)}
    {#if part.kind === 'handle' && !handle}
      {@const size = paint.chrome.handles.size}
      {#if paint.chrome.handles.shape === 'circle'}
        <circle
          cx={part.at.x}
          cy={part.at.y}
          r={size / 2}
          stroke-width="1.5"
          style={paint.css.handle}
        />
      {:else}
        <!-- The square rides a turned box's orientation (it spins about itself). -->
        <rect
          x={part.at.x - size / 2}
          y={part.at.y - size / 2}
          width={size}
          height={size}
          stroke-width="1.5"
          style={paint.css.handle}
          transform={part.rotation
            ? `rotate(${part.rotation} ${part.at.x} ${part.at.y})`
            : undefined}
        />
      {/if}
    {:else if part.kind === 'guide'}
      <line
        x1={part.from.x}
        y1={part.from.y}
        x2={part.to.x}
        y2={part.to.y}
        shape-rendering="crispEdges"
        style={paint.css.guide}
      />
    {:else if part.kind === 'turned-outline'}
      <polygon points={part.points} fill="none" style={paint.css.outline} />
    {:else if part.kind === 'rotation-guides'}
      <g>
        {#each part.lines as line, lineIndex (lineIndex)}
          <line
            x1={line.from.x}
            y1={line.from.y}
            x2={line.to.x}
            y2={line.to.y}
            opacity={line.opacity}
            style={paint.css.rotationGuide}
          />
        {/each}
      </g>
    {:else if part.kind === 'rotation-handle' && !rotationHandle}
      <g>
        {#if paint.chrome.rotationHandle.stalk}
          <line
            x1={part.from.x}
            y1={part.from.y}
            x2={part.at.x}
            y2={part.at.y}
            stroke-width="1"
            style={paint.css.rotationStalk}
          />
        {/if}
        <circle
          cx={part.at.x}
          cy={part.at.y}
          r={paint.chrome.rotationHandle.size / 2}
          stroke-width="1.5"
          style={paint.css.rotationHandle}
        />
      </g>
    {:else if part.kind === 'marquee'}
      <!-- The box dragged to select keeps its own look (a see-through accent fill, always
           dashed); the selection outline follows the settings. -->
      <rect
        x={part.box.left}
        y={part.box.top}
        width={part.box.width}
        height={part.box.height}
        stroke-width="1"
        stroke-dasharray="4 3"
        style={paint.css.marquee}
      />
    {:else if part.kind === 'outline'}
      <rect
        x={part.box.left}
        y={part.box.top}
        width={part.box.width}
        height={part.box.height}
        fill="none"
        style={paint.css.outline}
      />
    {/if}
  {/each}
</svg>
{#if yours.length > 0}
  <div style="position: absolute; inset: 0; pointer-events: none">
    {#each yours as part, index (index)}
      {#if part.kind === 'handle'}
        {@render handle?.({
          at: part.at,
          size: paint.chrome.handles.size,
          rotation: part.rotation,
          kind: part.role,
          active: part.active,
        })}
      {:else if part.kind === 'rotation-handle'}
        <!-- Your rotation handle stands still while it's dragged: the badge shows the angle. -->
        {@render rotationHandle?.({
          at: part.at,
          from: part.from,
          size: paint.chrome.rotationHandle.size,
          rotation: 0,
          active: false,
        })}
      {/if}
    {/each}
  </div>
{/if}
