// website/src/samples/coordinates/pass-through.vue/Hits.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useSearch, useSearchHits } from '@embedpdf/vue/search';
import { useStage } from '@embedpdf/vue/stage';

// A search hit says where it is in page coordinates; the Stage takes them as they are.
const search = useSearch();
const stage = useStage();
const hits = useSearchHits();
// The first eight that have a place on the page.
const shown = computed(() =>
  hits.value.slice(0, 8).flatMap((hit) => (hit.bounds ? [{ hit, bounds: hit.bounds }] : [])),
);

void search.search({ text: 'PDF' });
</script>

<template>
  <ol class="hits">
    <li v-for="{ hit, bounds } in shown" :key="`${hit.page.objectNumber}:${hit.start}`">
      <button
        type="button"
        class="hit"
        @click="stage.reveal(hit.page, { rect: bounds, anchor: { y: 0.35 } })"
      >
        <span class="where">page {{ hit.pageIndex + 1 }}</span>
        <code class="rect">x {{ Math.round(bounds.x) }}, y {{ Math.round(bounds.y) }}</code>
      </button>
    </li>
  </ol>
</template>

// cloudpdf/website/src/samples/coordinates/pass-through.svelte/Hits.svelte
<!-- A search hit says where it is in page coordinates; the Stage takes them as they are. -->
<script lang="ts">
  import { useSearch, useSearchHits } from '@embedpdf/svelte/search';
  import { useStage } from '@embedpdf/svelte/stage';

  const search = useSearch();
  const stage = useStage();
  const hits = useSearchHits();

  $effect(() => {
    void search.search({ text: 'PDF' });
  });
</script>

<ol class="hits">
  {#each hits.current.slice(0, 8) as hit (`${hit.page.objectNumber}:${hit.start}`)}
    {@const bounds = hit.bounds}
    {#if bounds}
      <li>
        <button
          type="button"
          class="hit"
          onclick={() => stage.reveal(hit.page, { rect: bounds, anchor: { y: 0.35 } })}
        >
          <span class="where">page {hit.pageIndex + 1}</span>
          <code class="rect">x {Math.round(bounds.x)}, y {Math.round(bounds.y)}</code>
        </button>
      </li>
    {/if}
  {/each}
</ol>
