// packages/plugin-annotation/src/shared/components/annotation-layer.tsx
import { HTMLAttributes, CSSProperties, useMemo } from '@framework';
import { useDocumentState } from '@embedpdf/core/@framework';
import { Annotations } from './annotations';
import { TextMarkup } from './text-markup';
import { SelectionMenu, ResizeHandleUI, VertexHandleUI, CustomAnnotationRenderer } from './types';
import { AnnotationPaintLayer } from './annotation-paint-layer';
import { PdfAnnotationObject, Rotation } from '@embedpdf/models';

type AnnotationLayerProps = Omit<HTMLAttributes<HTMLDivElement>, 'style'> & {
  /** The ID of the document that this layer displays annotations for */
  documentId: string;
  pageIndex: number;
  scale?: number;
  rotation?: number;
  /** Customize selection menu across all annotations on this layer */
  selectionMenu?: SelectionMenu;
  style?: CSSProperties;
  /** Customize resize handles */
  resizeUI?: ResizeHandleUI;
  /** Customize vertex handles */
  vertexUI?: VertexHandleUI;
  /** Customize selection outline color */
  selectionOutlineColor?: string;
  /** Customize annotation renderer */
  customAnnotationRenderer?: CustomAnnotationRenderer<PdfAnnotationObject>;
};

export function AnnotationLayer({
  style,
  documentId,
  pageIndex,
  scale: overrideScale,
  rotation: overrideRotation,
  selectionMenu,
  resizeUI,
  vertexUI,
  selectionOutlineColor,
  customAnnotationRenderer,
  ...props
}: AnnotationLayerProps) {
  const documentState = useDocumentState(documentId);
  const page = documentState?.document?.pages?.[pageIndex];
  const width = page?.size?.width ?? 0;
  const height = page?.size?.height ?? 0;

  const actualScale = useMemo(() => {
    if (overrideScale !== undefined) return overrideScale;
    return documentState?.scale ?? 1;
  }, [overrideScale, documentState?.scale]);

  const actualRotation = useMemo(() => {
    if (overrideRotation !== undefined) return overrideRotation;
    return documentState?.rotation ?? Rotation.Degree0;
  }, [overrideRotation, documentState?.rotation]);

  return (
    <div
      style={{
        ...style,
      }}
      {...props}
    >
      <Annotations
        documentId={documentId}
        selectionMenu={selectionMenu}
        pageIndex={pageIndex}
        scale={actualScale}
        rotation={actualRotation}
        pageWidth={width}
        pageHeight={height}
        resizeUI={resizeUI}
        vertexUI={vertexUI}
        selectionOutlineColor={selectionOutlineColor}
        customAnnotationRenderer={customAnnotationRenderer}
      />
      <TextMarkup documentId={documentId} pageIndex={pageIndex} scale={actualScale} />
      <AnnotationPaintLayer documentId={documentId} pageIndex={pageIndex} scale={actualScale} />
    </div>
  );
}

// packages/plugin-annotation/src/vue/components/annotation-layer.vue
<template>
  <div>
    <Annotations
      :documentId="documentId"
      :pageIndex="pageIndex"
      :scale="actualScale"
      :rotation="actualRotation"
      :pageWidth="pageWidth"
      :pageHeight="pageHeight"
      :resizeUI="resizeUI"
      :vertexUI="vertexUI"
      :selectionOutlineColor="selectionOutlineColor"
    >
      <template #selection-menu="slotProps">
        <slot name="selection-menu" v-bind="slotProps"></slot>
      </template>
      <template #resize-handle="slotProps">
        <slot name="resize-handle" v-bind="slotProps"></slot>
      </template>
      <template #vertex-handle="slotProps">
        <slot name="vertex-handle" v-bind="slotProps"></slot>
      </template>
    </Annotations>
    <TextMarkup :documentId="documentId" :pageIndex="pageIndex" :scale="actualScale" />
    <AnnotationPaintLayer :documentId="documentId" :pageIndex="pageIndex" :scale="actualScale" />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useDocumentState } from '@embedpdf/core/vue';
import { Rotation } from '@embedpdf/models';
import Annotations from './annotations.vue';
import TextMarkup from './text-markup.vue';
import AnnotationPaintLayer from './annotation-paint-layer.vue';
import { ResizeHandleUI, VertexHandleUI } from '../types';

const props = defineProps<{
  /** The ID of the document that this layer displays annotations for */
  documentId: string;
  pageIndex: number;
  scale?: number;
  rotation?: number;
  /** Customize resize handles */
  resizeUI?: ResizeHandleUI;
  /** Customize vertex handles */
  vertexUI?: VertexHandleUI;
  /** Customize selection outline color */
  selectionOutlineColor?: string;
}>();

const documentState = useDocumentState(() => props.documentId);
const page = computed(() => documentState.value?.document?.pages?.[props.pageIndex]);
const pageWidth = computed(() => page.value?.size?.width ?? 0);
const pageHeight = computed(() => page.value?.size?.height ?? 0);

const actualScale = computed(() => {
  if (props.scale !== undefined) return props.scale;
  return documentState.value?.scale ?? 1;
});

const actualRotation = computed(() => {
  if (props.rotation !== undefined) return props.rotation;
  return documentState.value?.rotation ?? Rotation.Degree0;
});
</script>
