// packages/plugin-document-manager/src/vue/components/document-context.vue
<script setup lang="ts">
import { useOpenDocuments, useActiveDocument, useDocumentManagerCapability } from '../hooks';
import type { DocumentState } from '@embedpdf/core';

export interface TabActions {
  select: (documentId: string) => void;
  close: (documentId: string) => void;
  move: (documentId: string, toIndex: number) => void;
}

export interface DocumentContextRenderProps {
  documentStates: DocumentState[];
  activeDocumentId: string | null;
  actions: TabActions;
}

const documentStates = useOpenDocuments();
const { activeDocumentId } = useActiveDocument();
const { provides } = useDocumentManagerCapability();

const actions: TabActions = {
  select: (documentId: string) => {
    provides.value?.setActiveDocument(documentId);
  },
  close: (documentId: string) => {
    provides.value?.closeDocument(documentId);
  },
  move: (documentId: string, toIndex: number) => {
    provides.value?.moveDocument(documentId, toIndex);
  },
};
</script>

<template>
  <!--
    Headless component for managing document tabs
    Provides all state and actions, completely UI-agnostic
    
    @example
    <DocumentContext>
      <template #default="{ documentStates, activeDocumentId, actions }">
        <div class="tabs">
          <button
            v-for="doc in documentStates"
            :key="doc.id"
            @click="actions.select(doc.id)"
            :class="{ active: doc.id === activeDocumentId }"
          >
            {{ doc.name }}
            <button @click.stop="actions.close(doc.id)">×</button>
          </button>
        </div>
      </template>
    </DocumentContext>
  -->
  <slot :documentStates="documentStates" :activeDocumentId="activeDocumentId" :actions="actions" />
</template>

// packages/plugin-document-manager/src/shared/components/document-context.tsx
import { ReactNode, useCallback } from '@framework';
import { useOpenDocuments, useActiveDocument, useDocumentManagerCapability } from '../hooks';
import { DocumentState } from '@embedpdf/core';

export interface TabActions {
  select: (documentId: string) => void;
  close: (documentId: string) => void;
  move: (documentId: string, toIndex: number) => void;
}

export interface DocumentContextRenderProps {
  documentStates: DocumentState[];
  activeDocumentId: string | null;
  actions: TabActions;
}

interface DocumentContextProps {
  children: (props: DocumentContextRenderProps) => ReactNode;
}

/**
 * Headless component for managing document tabs
 * Provides all state and actions, completely UI-agnostic
 *
 * @example
 * <DocumentContext>
 *   {({ documents, activeDocumentId, actions }) => (
 *     <div className="tabs">
 *       {documents.map((doc) => (
 *         <button
 *           key={doc.id}
 *           onClick={() => actions.select(doc.id)}
 *           className={doc.id === activeDocumentId ? 'active' : ''}
 *         >
 *           {doc.name}
 *           <button onClick={(e) => {
 *             e.stopPropagation();
 *             actions.close(doc.id);
 *           }}>×</button>
 *         </button>
 *       ))}
 *     </div>
 *   )}
 * </DocumentContext>
 */
export function DocumentContext({ children }: DocumentContextProps) {
  const documentStates = useOpenDocuments();
  const { activeDocumentId } = useActiveDocument();
  const { provides } = useDocumentManagerCapability();

  const select = useCallback(
    (documentId: string) => {
      provides?.setActiveDocument(documentId);
    },
    [provides],
  );

  const close = useCallback(
    (documentId: string) => {
      provides?.closeDocument(documentId);
    },
    [provides],
  );

  const move = useCallback(
    (documentId: string, toIndex: number) => {
      provides?.moveDocument(documentId, toIndex);
    },
    [provides],
  );

  const actions: TabActions = {
    select,
    close,
    move,
  };

  return <>{children({ documentStates, activeDocumentId, actions })}</>;
}
