// examples/react-tailwind/src/components/document-menu.tsx
import { useState } from 'react';
import { useExport } from '@embedpdf/plugin-export/react';
import { useCapture } from '@embedpdf/plugin-capture/react';
import { useFullscreen } from '@embedpdf/plugin-fullscreen/react';
import {
  MenuIcon,
  PrintIcon,
  DownloadIcon,
  ScreenshotIcon,
  FullscreenIcon,
  FullscreenExitIcon,
} from './icons';
import { PrintDialog } from './print-dialog';
import { CaptureDialog } from './capture-dialog';
import { ToolbarButton, DropdownMenu, DropdownItem } from './ui';

type DocumentMenuProps = {
  documentId: string;
};

export function DocumentMenu({ documentId }: DocumentMenuProps) {
  const { provides: exportProvider } = useExport(documentId);
  const { provides: captureProvider, state: captureState } = useCapture(documentId);
  const { provides: fullscreenProvider, state: fullscreenState } = useFullscreen();
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isPrintDialogOpen, setIsPrintDialogOpen] = useState(false);

  if (!exportProvider) return null;

  const handleDownload = () => {
    exportProvider.download();
    setIsMenuOpen(false);
  };

  const handlePrint = () => {
    setIsMenuOpen(false);
    setIsPrintDialogOpen(true);
  };

  const handleScreenshot = () => {
    if (captureProvider) {
      captureProvider.toggleMarqueeCapture();
    }
    setIsMenuOpen(false);
  };

  const handleFullscreen = () => {
    fullscreenProvider?.toggleFullscreen(`#${documentId}`);
    setIsMenuOpen(false);
  };

  return (
    <>
      <div className="relative">
        <ToolbarButton
          onClick={() => setIsMenuOpen(!isMenuOpen)}
          isActive={isMenuOpen}
          aria-label="Document Menu"
          title="Document Menu"
        >
          <MenuIcon className="h-4 w-4" />
        </ToolbarButton>

        <DropdownMenu isOpen={isMenuOpen} onClose={() => setIsMenuOpen(false)} className="w-48">
          <DropdownItem
            isActive={captureState.isMarqueeCaptureActive}
            onClick={handleScreenshot}
            icon={<ScreenshotIcon className="h-4 w-4" title="Capture Area" />}
          >
            Capture Area
          </DropdownItem>
          <DropdownItem
            onClick={handlePrint}
            icon={<PrintIcon className="h-4 w-4" title="Print" />}
          >
            Print
          </DropdownItem>
          <DropdownItem
            onClick={handleDownload}
            icon={<DownloadIcon className="h-4 w-4" title="Download" />}
          >
            Download
          </DropdownItem>
          <DropdownItem
            onClick={handleFullscreen}
            icon={
              fullscreenState.isFullscreen ? (
                <FullscreenExitIcon className="h-4 w-4" title="Exit Fullscreen" />
              ) : (
                <FullscreenIcon className="h-4 w-4" title="Fullscreen" />
              )
            }
          >
            {fullscreenState.isFullscreen ? 'Exit Fullscreen' : 'Fullscreen'}
          </DropdownItem>
        </DropdownMenu>
      </div>

      {/* Print Dialog */}
      <PrintDialog
        documentId={documentId}
        isOpen={isPrintDialogOpen}
        onClose={() => setIsPrintDialogOpen(false)}
      />

      {/* Capture Dialog */}
      <CaptureDialog documentId={documentId} />
    </>
  );
}

// examples/vue-tailwind/src/components/DocumentMenu.vue
<template>
  <div v-if="exportProvider" class="relative">
    <ToolbarButton
      :onClick="() => (isMenuOpen = !isMenuOpen)"
      :isActive="isMenuOpen"
      aria-label="Document Menu"
      title="Document Menu"
    >
      <MenuIcon class="h-4 w-4" />
    </ToolbarButton>

    <DropdownMenu :isOpen="isMenuOpen" :onClose="() => (isMenuOpen = false)" className="w-48">
      <DropdownItem :isActive="captureState.isMarqueeCaptureActive" :onClick="handleScreenshot">
        <template #icon>
          <ScreenshotIcon class="h-4 w-4" title="Capture Area" />
        </template>
        Capture Area
      </DropdownItem>
      <DropdownItem :onClick="handlePrint">
        <template #icon>
          <PrintIcon class="h-4 w-4" title="Print" />
        </template>
        Print
      </DropdownItem>
      <DropdownItem :onClick="handleDownload">
        <template #icon>
          <DownloadIcon class="h-4 w-4" title="Download" />
        </template>
        Download
      </DropdownItem>
      <DropdownItem :onClick="handleFullscreen">
        <template #icon>
          <FullscreenExitIcon
            v-if="fullscreenState.isFullscreen"
            class="h-4 w-4"
            title="Exit Fullscreen"
          />
          <FullscreenIcon v-else class="h-4 w-4" title="Fullscreen" />
        </template>
        {{ fullscreenState.isFullscreen ? 'Exit Fullscreen' : 'Fullscreen' }}
      </DropdownItem>
    </DropdownMenu>
  </div>

  <!-- Print Dialog -->
  <PrintDialog
    :documentId="props.documentId"
    :isOpen="isPrintDialogOpen"
    :onClose="() => (isPrintDialogOpen = false)"
  />

  <!-- Capture Dialog -->
  <CaptureDialog :documentId="props.documentId" />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useExport } from '@embedpdf/plugin-export/vue';
import { useCapture } from '@embedpdf/plugin-capture/vue';
import { useFullscreen } from '@embedpdf/plugin-fullscreen/vue';
import {
  MenuIcon,
  PrintIcon,
  DownloadIcon,
  ScreenshotIcon,
  FullscreenIcon,
  FullscreenExitIcon,
} from './Icons.vue';
import { ToolbarButton, DropdownMenu, DropdownItem } from './ui';
import PrintDialog from './PrintDialog.vue';
import CaptureDialog from './CaptureDialog.vue';

const props = defineProps<{
  documentId: string;
}>();

const { provides: exportProvider } = useExport(() => props.documentId);
const { provides: captureProvider, state: captureState } = useCapture(() => props.documentId);
const { provides: fullscreenProvider, state: fullscreenState } = useFullscreen();
const isMenuOpen = ref(false);
const isPrintDialogOpen = ref(false);

const handleDownload = () => {
  exportProvider.value?.download();
  isMenuOpen.value = false;
};

const handlePrint = () => {
  isMenuOpen.value = false;
  isPrintDialogOpen.value = true;
};

const handleScreenshot = () => {
  captureProvider.value?.toggleMarqueeCapture();
  isMenuOpen.value = false;
};

const handleFullscreen = () => {
  fullscreenProvider.value?.toggleFullscreen(`#${props.documentId}`);
  isMenuOpen.value = false;
};
</script>
