// snippet/src/components/search-sidebar.tsx
import { h } from 'preact';
import { useState, useRef, useEffect } from 'preact/hooks';
import { useSearch } from '@embedpdf/plugin-search/preact';
import { useScrollCapability } from '@embedpdf/plugin-scroll/preact';
import { MatchFlag, SearchResult } from '@embedpdf/models';
import { useTranslations } from '@embedpdf/plugin-i18n/preact';
import { useDebounce } from '../hooks/use-debounce';
import { Checkbox } from './ui/checkbox';
import { Button } from './ui/button';
import { XIcon } from './icons/x';
import { ChevronRightIcon } from './icons/chevron-right';
import { ChevronLeftIcon } from './icons/chevron-left';
import { SearchIcon } from './icons/search';

const HitLine = ({
  hit,
  onClick,
  active,
}: {
  hit: SearchResult;
  onClick: () => void;
  active: boolean;
}) => {
  const ref = useRef<HTMLButtonElement>(null);

  useEffect(() => {
    if (active && ref.current) {
      ref.current.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    }
  }, [active]);

  return (
    <button
      ref={ref}
      onClick={onClick}
      className={`w-full rounded border p-2 text-left text-sm transition-colors ${
        active
          ? 'border-blue-500 bg-blue-50 text-blue-900'
          : 'border-gray-200 bg-white text-gray-700 hover:bg-gray-50'
      }`}
    >
      <span>
        {hit.context.truncatedLeft && '… '}
        {hit.context.before}
        <span className="font-bold text-blue-600">{hit.context.match}</span>
        {hit.context.after}
        {hit.context.truncatedRight && ' …'}
      </span>
    </button>
  );
};

type SearchSidebarProps = {
  documentId: string;
  onClose?: () => void;
};

export function SearchSidebar({ documentId, onClose }: SearchSidebarProps) {
  const { state, provides } = useSearch(documentId);
  const { provides: scroll } = useScrollCapability();
  const { translate } = useTranslations(documentId);
  const inputRef = useRef<HTMLInputElement>(null);
  const [inputValue, setInputValue] = useState('');

  // Sync inputValue with persisted state.query when state loads
  useEffect(() => {
    if (state.query && !inputValue) {
      setInputValue(state.query);
    }
  }, [state.query]);

  const debouncedValue = useDebounce(inputValue, 300);

  useEffect(() => {
    if (debouncedValue !== state.query) {
      provides?.searchAllPages(debouncedValue);
    }
  }, [debouncedValue, provides, state.query]);

  const handleInputChange = (e: Event) => {
    const target = e.target as HTMLInputElement;
    setInputValue(target.value);
  };

  const handleFlagChange = (flag: MatchFlag, checked: boolean) => {
    if (checked) {
      provides?.setFlags([...state.flags, flag]);
    } else {
      provides?.setFlags(state.flags.filter((f) => f !== flag));
    }
  };

  const scrollToItem = (index: number) => {
    const item = state.results[index];
    if (!item) return;

    const minCoordinates = item.rects.reduce(
      (min, rect) => ({
        x: Math.min(min.x, rect.origin.x),
        y: Math.min(min.y, rect.origin.y),
      }),
      { x: Infinity, y: Infinity },
    );

    scroll?.scrollToPage({
      pageNumber: item.pageIndex + 1,
      pageCoordinates: minCoordinates,
      center: true,
    });
  };

  const clearInput = () => {
    setInputValue('');
    if (inputRef.current) {
      inputRef.current.focus();
    }
  };

  const groupByPage = (
    results: SearchResult[],
  ): Record<number, { hit: SearchResult; index: number }[]> => {
    const grouped: Record<number, { hit: SearchResult; index: number }[]> = {};
    results.forEach((hit, index) => {
      if (!grouped[hit.pageIndex]) {
        grouped[hit.pageIndex] = [];
      }
      grouped[hit.pageIndex].push({ hit, index });
    });
    return grouped;
  };

  const grouped = groupByPage(state.results);

  return (
    <div className="flex h-full flex-col bg-white">
      <div className="p-4">
        <div className="relative">
          <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-2">
            <SearchIcon className="h-4 w-4 text-gray-500" />
          </div>
          <input
            ref={inputRef}
            type="text"
            placeholder={translate('search.placeholder') || 'Search'}
            autoFocus
            value={inputValue}
            onInput={handleInputChange}
            className="w-full rounded-md border border-gray-300 py-1 pl-8 pr-9 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
          />
          {inputValue && (
            <div
              className="absolute inset-y-0 right-0 flex cursor-pointer items-center pr-3"
              onClick={clearInput}
            >
              <XIcon className="h-4 w-4 text-gray-500 hover:text-gray-700" />
            </div>
          )}
        </div>
        <div className="mt-3 flex flex-row gap-4">
          <Checkbox
            label="Case sensitive"
            checked={state.flags.includes(MatchFlag.MatchCase)}
            onChange={(checked) => handleFlagChange(MatchFlag.MatchCase, checked)}
          />
          <Checkbox
            label="Whole word"
            checked={state.flags.includes(MatchFlag.MatchWholeWord)}
            onChange={(checked) => handleFlagChange(MatchFlag.MatchWholeWord, checked)}
          />
        </div>
        <hr className="mb-2 mt-5 border-gray-200" />
        {state.active && (
          <div className="flex h-[32px] flex-row items-center justify-between">
            <div className="text-xs text-gray-500">{state.total} results found</div>
            {state.total > 1 && (
              <div className="flex flex-row">
                <Button
                  onClick={() => {
                    provides?.previousResult();
                  }}
                >
                  <ChevronLeftIcon className="h-4 w-4" />
                </Button>
                <Button
                  onClick={() => {
                    provides?.nextResult();
                  }}
                >
                  <ChevronRightIcon className="h-4 w-4" />
                </Button>
              </div>
            )}
          </div>
        )}
      </div>
      <div className="flex min-h-0 flex-1 flex-col gap-2 overflow-y-auto px-4">
        {Object.entries(grouped).map(([page, hits]) => (
          <div key={page} className="mt-2 first:mt-0">
            <div className="bg-white/80 py-2 text-xs text-gray-500 backdrop-blur">
              Page {Number(page) + 1}
            </div>

            <div className="flex flex-col gap-2">
              {hits.map(({ hit, index }) => (
                <HitLine
                  key={index}
                  hit={hit}
                  active={index === state.activeResultIndex}
                  onClick={() => {
                    provides?.goToResult(index);
                  }}
                />
              ))}
            </div>
          </div>
        ))}
        <div />
      </div>
    </div>
  );
}

// examples/vue-tailwind/src/components/SearchSidebar.vue
<template>
  <div class="flex h-full flex-col bg-white">
    <!-- Search Input -->
    <div class="border-b border-gray-200 p-4">
      <div class="relative">
        <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
          <SearchIcon class="h-5 w-5 text-gray-400" />
        </div>
        <input
          ref="inputRef"
          v-model="inputValue"
          type="text"
          placeholder="Search"
          class="w-full rounded-lg border border-gray-300 py-2 pl-10 pr-10 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
        />
        <button
          v-if="inputValue"
          @click="clearInput"
          class="absolute inset-y-0 right-0 flex items-center pr-3"
        >
          <CloseIcon class="h-4 w-4 text-gray-400 hover:text-gray-600" />
        </button>
      </div>

      <!-- Options -->
      <div class="mt-3 space-y-2">
        <label class="flex items-center text-sm text-gray-700">
          <input
            :checked="isMatchCaseChecked"
            @change="
              (e) => handleFlagChange(MatchFlag.MatchCase, (e.target as HTMLInputElement).checked)
            "
            type="checkbox"
            class="mr-2 h-4 w-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500"
          />
          Case sensitive
        </label>
        <label class="flex items-center text-sm text-gray-700">
          <input
            :checked="isWholeWordChecked"
            @change="
              (e) =>
                handleFlagChange(MatchFlag.MatchWholeWord, (e.target as HTMLInputElement).checked)
            "
            type="checkbox"
            class="mr-2 h-4 w-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500"
          />
          Whole word
        </label>
      </div>

      <!-- Results count and navigation -->
      <div
        v-if="state.active && !state.loading && state.total > 0"
        class="mt-3 flex items-center justify-between"
      >
        <span class="text-sm text-gray-600">{{ state.total }} results found</span>
        <div v-if="state.total > 1" class="flex gap-1">
          <button
            @click="provides?.previousResult()"
            class="rounded p-1 text-gray-600 hover:bg-gray-100"
            aria-label="Previous result"
          >
            <ChevronLeftIcon class="h-4 w-4" />
          </button>
          <button
            @click="provides?.nextResult()"
            class="rounded p-1 text-gray-600 hover:bg-gray-100"
            aria-label="Next result"
          >
            <ChevronRightIcon class="h-4 w-4" />
          </button>
        </div>
      </div>
    </div>

    <!-- Results -->
    <div class="flex-1 overflow-auto p-4">
      <div v-if="state.loading" class="flex h-full items-center justify-center">
        <div class="h-6 w-6 animate-spin rounded-full border-2 border-gray-300 border-t-blue-600" />
      </div>
      <div v-else class="space-y-4">
        <div v-for="(hits, page) in grouped" :key="page">
          <div class="mb-2 text-xs font-semibold text-gray-500">Page {{ Number(page) + 1 }}</div>
          <div class="space-y-2">
            <button
              v-for="{ hit, index } in hits"
              :key="index"
              @click="handleHitClick(index)"
              :class="[
                'w-full rounded border p-2 text-left text-sm transition-colors',
                index === state.activeResultIndex
                  ? 'border-blue-500 bg-blue-50 text-blue-900'
                  : 'border-gray-200 bg-white text-gray-700 hover:bg-gray-50',
              ]"
            >
              <span>
                <template v-if="hit.context.truncatedLeft">… </template>
                {{ hit.context.before }}
                <span class="font-bold text-blue-600">{{ hit.context.match }}</span>
                {{ hit.context.after }}
                <template v-if="hit.context.truncatedRight"> …</template>
              </span>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, computed, onMounted, nextTick } from 'vue';
import { useSearch } from '@embedpdf/plugin-search/vue';
import { useScrollCapability } from '@embedpdf/plugin-scroll/vue';
import { MatchFlag } from '@embedpdf/models';
import { SearchIcon, CloseIcon, ChevronRightIcon, ChevronLeftIcon } from './icons';

const props = defineProps<{
  documentId: string;
  onClose: () => void;
}>();

const { state, provides } = useSearch(() => props.documentId);
const { provides: scroll } = useScrollCapability();
const inputRef = ref<HTMLInputElement | null>(null);
const inputValue = ref(state.value.query || '');

// Focus input when component mounts
onMounted(async () => {
  await nextTick();
  inputRef.value?.focus();
  inputValue.value = state.value.query || '';
});

// Watch for input changes and trigger search
watch(inputValue, (newValue) => {
  if (newValue === '') {
    provides.value?.stopSearch();
  } else {
    provides.value?.searchAllPages(newValue);
  }
});

// Auto-scroll to active result when it changes
watch(
  () => [state.value.activeResultIndex, state.value.loading, state.value.query, state.value.flags],
  ([activeIndex]) => {
    if (typeof activeIndex === 'number' && !state.value.loading) {
      scrollToItem(activeIndex);
    }
  },
);

const handleFlagChange = (flag: MatchFlag, checked: boolean) => {
  const currentFlags = state.value.flags;
  if (checked) {
    provides.value?.setFlags([...currentFlags, flag]);
  } else {
    provides.value?.setFlags(currentFlags.filter((f) => f !== flag));
  }
};

const clearInput = () => {
  inputValue.value = '';
  inputRef.value?.focus();
};

const scrollToItem = (index: number) => {
  const item = state.value.results[index];
  if (!item) return;

  const minCoordinates = item.rects.reduce(
    (min, rect) => ({
      x: Math.min(min.x, rect.origin.x),
      y: Math.min(min.y, rect.origin.y),
    }),
    { x: Infinity, y: Infinity },
  );

  scroll.value?.scrollToPage({
    pageNumber: item.pageIndex + 1,
    pageCoordinates: minCoordinates,
    center: true,
  });
};

const grouped = computed(() => {
  return state.value.results.reduce<
    Record<number, { hit: (typeof state.value.results)[0]; index: number }[]>
  >((map, r, i) => {
    (map[r.pageIndex] ??= []).push({ hit: r, index: i });
    return map;
  }, {});
});

const handleHitClick = (index: number) => {
  provides.value?.goToResult(index);
};

const isMatchCaseChecked = computed(() => state.value.flags.includes(MatchFlag.MatchCase));
const isWholeWordChecked = computed(() => state.value.flags.includes(MatchFlag.MatchWholeWord));
</script>
