// packages/plugin-viewport/src/svelte/components/Viewport.svelte
<script lang="ts">
  import { useIsViewportGated, useViewportCapability, useViewportRef } from '../hooks';
  import type { HTMLAttributes } from 'svelte/elements';
  import type { Snippet } from 'svelte';

  type ViewportProps = HTMLAttributes<HTMLDivElement> & {
    /**
     * The ID of the document that this viewport displays
     */
    documentId: string;
    children: Snippet;
    class?: string;
  };

  let { documentId, children, class: propsClass, ...restProps }: ViewportProps = $props();

  let viewportGap = $state(0);

  const viewportRef = useViewportRef(() => documentId);
  const viewportCapability = useViewportCapability();
  const isGated = useIsViewportGated(() => documentId);

  $effect(() => {
    if (viewportCapability.provides) {
      viewportGap = viewportCapability.provides.getViewportGap();
    }
  });
</script>

<div
  {...restProps}
  bind:this={viewportRef.containerRef}
  style:width="100%"
  style:height="100%"
  style:overflow="auto"
  style:padding={`${viewportGap}px`}
  class={propsClass}
>
  {#if !isGated.current}
    {@render children()}
  {/if}
</div>

// packages/plugin-viewport/src/shared/components/viewport.tsx
import { ReactNode, useEffect, useState, HTMLAttributes } from '@framework';
import { useIsViewportGated, useViewportCapability } from '../hooks';
import { useViewportRef } from '../hooks/use-viewport-ref';

type ViewportProps = HTMLAttributes<HTMLDivElement> & {
  children: ReactNode;
  /**
   * The ID of the document that this viewport displays
   */
  documentId: string;
};

export function Viewport({ children, documentId, ...props }: ViewportProps) {
  const [viewportGap, setViewportGap] = useState(0);
  const viewportRef = useViewportRef(documentId);
  const { provides: viewportProvides } = useViewportCapability();
  const isGated = useIsViewportGated(documentId);

  useEffect(() => {
    if (viewportProvides) {
      setViewportGap(viewportProvides.getViewportGap());
    }
  }, [viewportProvides]);

  const { style, ...restProps } = props;
  return (
    <div
      {...restProps}
      ref={viewportRef}
      style={{
        width: '100%',
        height: '100%',
        overflow: 'auto',
        ...(typeof style === 'object' ? style : {}),
        padding: `${viewportGap}px`,
      }}
    >
      {!isGated && children}
    </div>
  );
}
