// examples/vue-tailwind/src/ui/SchemaSelectionMenu.vue
<template>
  <div v-bind="props.menuWrapperProps">
    <div :style="menuStyle" class="rounded-lg border border-gray-200 bg-white shadow-lg">
      <div class="flex items-center gap-1 px-2 py-1">
        <template v-for="item in schema.items" :key="item.id">
          <SelectionMenuItemRenderer :item="item" :documentId="documentId" :props="props" />
        </template>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, type CSSProperties } from 'vue';
import type { SelectionMenuRendererProps } from '@embedpdf/plugin-ui/vue';
import SelectionMenuItemRenderer from './SelectionMenuItemRenderer.vue';

const componentProps = defineProps<SelectionMenuRendererProps>();

const menuStyle = computed<CSSProperties>(() => {
  const style: CSSProperties = {
    position: 'absolute',
    pointerEvents: 'auto',
    cursor: 'default',
  };

  if (componentProps.props.placement?.suggestTop) {
    style.top = '-48px'; // -40 - 8
  } else {
    style.top = `${componentProps.props.rect.size.height + 8}px`;
  }

  return style;
});
</script>

// examples/react-tailwind/src/ui/schema-selection-menu.tsx
import {
  SelectionMenuRendererProps,
  SelectionMenuItem,
  SelectionMenuPropsBase,
} from '@embedpdf/plugin-ui/react';
import { CommandButton } from '../components/command-button';
import { ToolbarDivider } from '../components/ui';

export function SchemaSelectionMenu({ schema, documentId, props }: SelectionMenuRendererProps) {
  const { menuWrapperProps, rect, placement } = props;

  // Calculate position
  const menuStyle: React.CSSProperties = {
    position: 'absolute',
    pointerEvents: 'auto',
    cursor: 'default',
  };

  if (placement?.suggestTop) {
    menuStyle.top = -40 - 8;
  } else {
    menuStyle.top = rect.size.height + 8;
  }

  return (
    <div {...menuWrapperProps}>
      <div style={menuStyle} className="rounded-lg border border-gray-200 bg-white shadow-lg">
        <div className="flex items-center gap-1 px-2 py-1">
          {schema.items.map((item) => (
            <SelectionMenuItemRenderer
              key={item.id}
              item={item}
              documentId={documentId}
              props={props}
            />
          ))}
        </div>
      </div>
    </div>
  );
}

function SelectionMenuItemRenderer({
  item,
  documentId,
  props,
}: {
  item: SelectionMenuItem;
  documentId: string;
  props: SelectionMenuPropsBase;
}) {
  switch (item.type) {
    case 'command-button':
      return (
        <CommandButton commandId={item.commandId} documentId={documentId} variant={item.variant} />
      );

    case 'divider':
      return <ToolbarDivider orientation="vertical" />;

    case 'group':
      return (
        <div className={`flex items-center gap-${item.gap ?? 1}`}>
          {item.items.map((child) => (
            <SelectionMenuItemRenderer
              key={child.id}
              item={child}
              documentId={documentId}
              props={props}
            />
          ))}
        </div>
      );

    default:
      return null;
  }
}
