// packages/plugin-annotation/src/shared/components/preview-renderer.tsx
import { AnyPreviewState } from '@embedpdf/plugin-annotation';
import { Circle } from './annotations/circle';
import { Square } from './annotations/square';
import { Polygon } from './annotations/polygon';
import { blendModeToCss, PdfAnnotationSubtype, PdfBlendMode } from '@embedpdf/models';
import { Polyline } from './annotations/polyline';
import { Line } from './annotations/line';
import { Ink } from './annotations/ink';

interface Props {
  preview: AnyPreviewState;
  scale: number;
}

export function PreviewRenderer({ preview, scale }: Props) {
  const { bounds } = preview;

  const style = {
    position: 'absolute' as const,
    left: bounds.origin.x * scale,
    top: bounds.origin.y * scale,
    width: bounds.size.width * scale,
    height: bounds.size.height * scale,
    pointerEvents: 'none' as const,
    zIndex: 10,
  };

  // Use type guards for proper type narrowing
  if (preview.type === PdfAnnotationSubtype.CIRCLE) {
    return (
      <div style={style}>
        <Circle isSelected={false} scale={scale} {...preview.data} />
      </div>
    );
  }

  if (preview.type === PdfAnnotationSubtype.SQUARE) {
    return (
      <div style={style}>
        <Square isSelected={false} scale={scale} {...preview.data} />
      </div>
    );
  }

  if (preview.type === PdfAnnotationSubtype.POLYGON) {
    return (
      <div style={style}>
        <Polygon isSelected={false} scale={scale} {...preview.data} />
      </div>
    );
  }

  if (preview.type === PdfAnnotationSubtype.POLYLINE) {
    return (
      <div style={style}>
        <Polyline isSelected={false} scale={scale} {...preview.data} />
      </div>
    );
  }

  if (preview.type === PdfAnnotationSubtype.LINE) {
    return (
      <div style={style}>
        <Line isSelected={false} scale={scale} {...preview.data} />
      </div>
    );
  }

  if (preview.type === PdfAnnotationSubtype.INK) {
    return (
      <div
        style={{
          ...style,
          mixBlendMode: blendModeToCss(preview.data.blendMode ?? PdfBlendMode.Normal),
        }}
      >
        <Ink isSelected={false} scale={scale} {...preview.data} />
      </div>
    );
  }

  if (preview.type === PdfAnnotationSubtype.FREETEXT) {
    return (
      <div style={style}>
        {/* Render a simple dashed border preview */}
        <div
          style={{
            width: '100%',
            height: '100%',
            border: `1px dashed ${preview.data.fontColor || '#000000'}`,
            backgroundColor: 'transparent',
          }}
        />
      </div>
    );
  }

  return null;
}

// packages/plugin-annotation/src/svelte/components/PreviewRenderer.svelte
<script lang="ts">
  import type { AnyPreviewState } from '@embedpdf/plugin-annotation';
  import { blendModeToCss, PdfAnnotationSubtype, PdfBlendMode } from '@embedpdf/models';
  import Circle from './annotations/Circle.svelte';
  import Square from './annotations/Square.svelte';
  import Polygon from './annotations/Polygon.svelte';
  import Polyline from './annotations/Polyline.svelte';
  import Line from './annotations/Line.svelte';
  import Ink from './annotations/Ink.svelte';

  interface PreviewRendererProps {
    preview: AnyPreviewState;
    scale: number;
  }

  let { preview, scale }: PreviewRendererProps = $props();

  const bounds = $derived(preview.bounds);

  const style = $derived({
    left: bounds.origin.x * scale,
    top: bounds.origin.y * scale,
    width: bounds.size.width * scale,
    height: bounds.size.height * scale,
  });
</script>

{#if preview.type === PdfAnnotationSubtype.CIRCLE}
  <div
    style:position="absolute"
    style:left="{style.left}px"
    style:top="{style.top}px"
    style:width="{style.width}px"
    style:height="{style.height}px"
    style:pointer-events="none"
    style:z-index="10"
  >
    <Circle isSelected={false} {scale} {...preview.data} />
  </div>
{:else if preview.type === PdfAnnotationSubtype.SQUARE}
  <div
    style:position="absolute"
    style:left="{style.left}px"
    style:top="{style.top}px"
    style:width="{style.width}px"
    style:height="{style.height}px"
    style:pointer-events="none"
    style:z-index="10"
  >
    <Square isSelected={false} {scale} {...preview.data} />
  </div>
{:else if preview.type === PdfAnnotationSubtype.POLYGON}
  <div
    style:position="absolute"
    style:left="{style.left}px"
    style:top="{style.top}px"
    style:width="{style.width}px"
    style:height="{style.height}px"
    style:pointer-events="none"
    style:z-index="10"
  >
    <Polygon isSelected={false} {scale} {...preview.data} />
  </div>
{:else if preview.type === PdfAnnotationSubtype.POLYLINE}
  <div
    style:position="absolute"
    style:left="{style.left}px"
    style:top="{style.top}px"
    style:width="{style.width}px"
    style:height="{style.height}px"
    style:pointer-events="none"
    style:z-index="10"
  >
    <Polyline isSelected={false} {scale} {...preview.data} />
  </div>
{:else if preview.type === PdfAnnotationSubtype.LINE}
  <div
    style:position="absolute"
    style:left="{style.left}px"
    style:top="{style.top}px"
    style:width="{style.width}px"
    style:height="{style.height}px"
    style:pointer-events="none"
    style:z-index="10"
  >
    <Line isSelected={false} {scale} {...preview.data} />
  </div>
{:else if preview.type === PdfAnnotationSubtype.INK}
  <div
    style:position="absolute"
    style:left="{style.left}px"
    style:top="{style.top}px"
    style:width="{style.width}px"
    style:height="{style.height}px"
    style:pointer-events="none"
    style:z-index="10"
    style:mix-blend-mode={blendModeToCss(preview.data.blendMode ?? PdfBlendMode.Normal)}
  >
    <Ink isSelected={false} {scale} {...preview.data} />
  </div>
{:else if preview.type === PdfAnnotationSubtype.FREETEXT}
  <div
    style:position="absolute"
    style:left="{style.left}px"
    style:top="{style.top}px"
    style:width="{style.width}px"
    style:height="{style.height}px"
    style:pointer-events="none"
    style:z-index="10"
  >
    <!-- Render a simple dashed border preview -->
    <div
      style:width="100%"
      style:height="100%"
      style:border="1px dashed {preview.data.fontColor || '#000000'}"
      style:background-color="transparent"
    ></div>
  </div>
{/if}
