// cloudpdf/website/src/samples/snippets/start/overview-cloud.vue.vue
<script setup lang="ts">
import { DocumentGate, Viewer } from '@embedpdf/vue/runtime';
import { Stage, stagePlugin } from '@embedpdf/vue/stage';
import { RenderLayer, renderPlugin } from '@embedpdf/vue/render';
import { cloudEngine } from '@cloudpdf/engine';
import { fetchDocumentToken } from './api';

const engine = cloudEngine({ baseUrl: 'https://pdf.example.com' });
const plugins = [stagePlugin(), renderPlugin()];
</script>

<template>
  <Viewer
    :engine="engine"
    :plugins="plugins"
    :initial-documents="[{ source: { kind: 'token', token: () => fetchDocumentToken('contract') } }]"
  >
    <DocumentGate>
      <template #fallback><p>Opening…</p></template>
      <Stage style="height: 600px">
        <template #page><RenderLayer /></template>
      </Stage>
    </DocumentGate>
  </Viewer>
</template>

// cloudpdf/website/src/samples/snippets/start/overview-cloud.svelte.svelte
<script lang="ts">
  import { DocumentGate, Viewer } from '@embedpdf/svelte/runtime';
  import { Stage, stagePlugin } from '@embedpdf/svelte/stage';
  import { RenderLayer, renderPlugin } from '@embedpdf/svelte/render';
  import { cloudEngine } from '@cloudpdf/engine';
  import { fetchDocumentToken } from './api';

  const engine = cloudEngine({ baseUrl: 'https://pdf.example.com' });
  const plugins = [stagePlugin(), renderPlugin()];
</script>

<Viewer
  {engine}
  {plugins}
  initialDocuments={[{ source: { kind: 'token', token: () => fetchDocumentToken('contract') } }]}
>
  <DocumentGate>
    {#snippet fallback()}
      <p>Opening…</p>
    {/snippet}
    <Stage style="height: 600px">
      {#snippet page()}
        <RenderLayer />
      {/snippet}
    </Stage>
  </DocumentGate>
</Viewer>
