// docs/content/snippets/viewer/start/ready.vue.vue
<script setup lang="ts">
import { PDFViewer, type Viewer } from '@embedpdf/viewer-vue';

function onReady(viewer: Viewer) {
  viewer.documents.onOpened(() => viewer.get('search').search({ text: 'total' }));
}
</script>

<template>
  <PDFViewer src="/report.pdf" style="height: 100vh" @ready="onReady" />
</template>

// website/src/samples/snippets/viewer/start/ready.react.tsx
import { PDFViewer, type Viewer } from '@embedpdf/viewer-react';

function onReady(viewer: Viewer) {
  viewer.documents.onOpened(() => viewer.get('search').search({ text: 'total' }));
}

export function App() {
  return <PDFViewer src="/report.pdf" onReady={onReady} style={{ height: '100vh' }} />;
}
