// examples/vue-vuetify/src/components/AnnotationSelectionMenu.vue
<script setup lang="ts">
import {
  useAnnotationCapability,
  type AnnotationSelectionContext,
  type AnnotationSelectionMenuProps,
} from '@embedpdf/plugin-annotation/vue';
import type { Rect } from '@embedpdf/models';

const props = defineProps<{
  documentId: string;
  context: AnnotationSelectionContext;
  selected: boolean;
  rect: Rect;
  placement: AnnotationSelectionMenuProps['placement'];
  menuWrapperProps: AnnotationSelectionMenuProps['menuWrapperProps'];
}>();

const { provides: annotation } = useAnnotationCapability();

const handleDelete = (e: Event) => {
  e.stopPropagation();
  if (!annotation.value) return;
  const { pageIndex, id } = props.context.annotation.object;
  annotation.value.deleteAnnotation(pageIndex, id);
};
</script>

<template>
  <span v-bind="menuWrapperProps">
    <v-card
      elevation="2"
      class="pa-1"
      :style="{
        position: 'absolute',
        top: `${rect.size.height + 8}px`,
        left: '0',
        zIndex: 1000,
        cursor: 'default',
        pointerEvents: 'auto',
      }"
    >
      <div class="d-flex align-center ga-1">
        <v-btn
          icon="mdi-delete-outline"
          size="small"
          variant="text"
          @click="handleDelete"
          aria-label="Delete annotation"
        />
      </div>
    </v-card>
  </span>
</template>

<style scoped>
.d-flex {
  display: flex;
}
.align-center {
  align-items: center;
}
.ga-1 {
  gap: 0.25rem;
}
</style>

// examples/react-mui/src/components/annotation-selection-menu.tsx
import { Paper, IconButton, Popper } from '@mui/material';
import DeleteOutlineOutlinedIcon from '@mui/icons-material/DeleteOutlineOutlined';
import { TrackedAnnotation } from '@embedpdf/plugin-annotation';
import { useAnnotationCapability } from '@embedpdf/plugin-annotation/react';
import { MenuWrapperProps } from '@embedpdf/utils/react';
import { useState } from 'react';

interface AnnotationSelectionMenuProps {
  menuWrapperProps: MenuWrapperProps;
  selected: TrackedAnnotation;
  documentId: string;
  container?: HTMLElement | null;
}

export function AnnotationSelectionMenu({
  selected,
  documentId,
  container,
  menuWrapperProps,
}: AnnotationSelectionMenuProps) {
  const { provides: annotationCapability } = useAnnotationCapability();
  const [anchorEl, setAnchorEl] = useState<HTMLSpanElement | null>(null);

  // Get document-scoped API
  const annotation = annotationCapability?.forDocument(documentId);

  const handleDelete = () => {
    if (!annotation) return;
    const { pageIndex, id } = selected.object;
    annotation.deleteAnnotation(pageIndex, id);
  };

  return (
    <>
      <span {...menuWrapperProps} ref={setAnchorEl} />
      <Popper
        open={Boolean(anchorEl)}
        anchorEl={anchorEl}
        placement="bottom"
        modifiers={[{ name: 'offset', options: { offset: [0, 8] } }]}
        container={container ?? undefined}
      >
        <Paper
          elevation={2}
          sx={{
            px: 0.5,
            py: 0.25,
            display: 'flex',
            alignItems: 'center',
            gap: 0.25,
            borderRadius: 1,
            cursor: 'default',
          }}
        >
          <IconButton size="small" onClick={handleDelete} aria-label="Delete annotation">
            <DeleteOutlineOutlinedIcon fontSize="small" />
          </IconButton>
        </Paper>
      </Popper>
    </>
  );
}
