// examples/vue-tailwind/src/components/RedactionSelectionMenu.vue
<template>
  <div v-bind="menuWrapperProps">
    <div :style="menuStyle" class="rounded-lg border border-gray-200 bg-white shadow-lg">
      <div class="flex items-center gap-1 px-2 py-1">
        <button
          @click="handleDelete"
          class="flex items-center justify-center rounded p-1.5 text-gray-600 transition-colors hover:bg-gray-100 hover:text-red-600"
          aria-label="Delete redaction"
          title="Delete redaction"
        >
          <TrashIcon class="h-4 w-4" />
        </button>
        <button
          @click="handleCommit"
          class="flex items-center justify-center rounded p-1.5 text-gray-600 transition-colors hover:bg-gray-100 hover:text-green-600"
          aria-label="Apply redaction"
          title="Apply redaction"
        >
          <CheckIcon class="h-4 w-4" />
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, type CSSProperties } from 'vue';
import type {
  RedactionSelectionContext,
  RedactionSelectionMenuProps,
} from '@embedpdf/plugin-redaction/vue';
import { useRedactionCapability } from '@embedpdf/plugin-redaction/vue';
import TrashIcon from './icons/TrashIcon.vue';
import CheckIcon from './icons/CheckIcon.vue';
import { Rect } from '@embedpdf/models';

const props = defineProps<{
  documentId: string;
  context: RedactionSelectionContext;
  selected: boolean;
  rect: Rect;
  placement: RedactionSelectionMenuProps['placement'];
  menuWrapperProps: RedactionSelectionMenuProps['menuWrapperProps'];
}>();

const { provides: redactionCapability } = useRedactionCapability();

const menuStyle = computed<CSSProperties>(() => ({
  position: 'absolute',
  pointerEvents: 'auto',
  cursor: 'default',
  top: `${props.rect.size.height + 8}px`,
}));

const handleDelete = () => {
  const scope = redactionCapability.value?.forDocument(props.documentId);
  if (!scope) return;

  const { item, pageIndex } = props.context;
  scope.removePending(pageIndex, item.id);
};

const handleCommit = () => {
  const scope = redactionCapability.value?.forDocument(props.documentId);
  if (!scope) return;

  const { item, pageIndex } = props.context;
  scope.commitPending(pageIndex, item.id);
};
</script>

// examples/react-mui/src/components/redaction-selection-menu.tsx
import { Paper, IconButton, Popper } from '@mui/material';
import DeleteOutlineOutlinedIcon from '@mui/icons-material/DeleteOutlineOutlined';
import DoneIcon from '@mui/icons-material/Done';
import { MenuWrapperProps } from '@embedpdf/utils/react';
import { useState } from 'react';
import { RedactionItem, useRedactionCapability } from '@embedpdf/plugin-redaction/react';

interface RedactionSelectionMenuProps {
  menuWrapperProps: MenuWrapperProps;
  selected: RedactionItem;
  documentId: string;
  container?: HTMLElement | null;
}

export function RedactionSelectionMenu({
  selected,
  documentId,
  container,
  menuWrapperProps,
}: RedactionSelectionMenuProps) {
  const { provides: redactionCapability } = useRedactionCapability();
  const [anchorEl, setAnchorEl] = useState<HTMLSpanElement | null>(null);

  // Get document-scoped API
  const redaction = redactionCapability?.forDocument(documentId);

  const handleDelete = () => {
    if (!redaction) return;
    const { page, id } = selected;
    redaction.removePending(page, id);
  };

  const handleCommit = () => {
    if (!redaction) return;
    const { page, id } = selected;
    redaction.commitPending(page, id);
  };

  return (
    <>
      <span {...menuWrapperProps} ref={setAnchorEl} />
      <Popper
        open={Boolean(anchorEl)}
        anchorEl={anchorEl}
        placement="bottom"
        modifiers={[{ name: 'offset', options: { offset: [0, 8] } }]}
        container={container ?? undefined}
      >
        <Paper
          elevation={2}
          sx={{
            px: 0.5,
            py: 0.25,
            display: 'flex',
            alignItems: 'center',
            gap: 0.25,
            borderRadius: 1,
            cursor: 'default',
          }}
        >
          <IconButton size="small" onClick={handleDelete} aria-label="Delete annotation">
            <DeleteOutlineOutlinedIcon fontSize="small" />
          </IconButton>
          <IconButton size="small" onClick={handleCommit} aria-label="Commit redaction">
            <DoneIcon fontSize="small" />
          </IconButton>
        </Paper>
      </Popper>
    </>
  );
}
