// packages/framework/svelte/src/annotation/AnnotationScene.svelte
<!--
  An annotation's vector drawing, filling its frame: drawn upright in it, the frame turns it. The
  core computes the box and the painted scene; `@embedpdf/web` describes each scene node as one
  SVG element, so there is no per-kind logic and no bounds math here.
-->
<script lang="ts">
  import { MITER_LIMIT, scene, type RenderItem } from '@embedpdf/core-annotation';
  import { ghostOpacity, sceneViewBox, svgShapesOf } from '@embedpdf/web';

  let { item }: { item: RenderItem } = $props();

  // Nothing to draw until the annotation has area (the 0×0 drawing at the first press).
  const viewBox = $derived(sceneViewBox(item.box));
  const shapes = $derived(viewBox ? svgShapesOf(scene(item), { miterLimit: MITER_LIMIT }) : []);
</script>

{#if viewBox}
  <!-- A ghost is see-through as a whole, so its fill and stroke don't stack. -->
  <svg
    {viewBox}
    style="position: absolute; left: 0; top: 0; width: 100%; height: 100%; overflow: visible; pointer-events: none"
    style:opacity={item.source === 'ghost' ? ghostOpacity(item.ghostOpacity ?? 0.5) : undefined}
  >
    {#each shapes as shape, index (index)}
      <!-- An SVG element: Svelte takes the namespace from the `<svg>` around it. -->
      <svelte:element this={shape.tag} {...shape.attributes} style:mix-blend-mode={shape.blend}>
        {#if shape.text !== undefined}{shape.text}{/if}
      </svelte:element>
    {/each}
  </svg>
{/if}

// packages/framework/vue/src/annotation/AnnotationScene.vue
<!--
  An annotation's scene, filling its frame: drawn upright in it, the frame
  turns it. The core computed the box and the painted scene; `@embedpdf/web`
  describes each scene node as one SVG element (its tag, its attributes under
  their SVG names, its text), so there is no per-kind logic and no bounds math
  here: one loop draws every kind.
-->
<script setup lang="ts">
import { computed } from 'vue';
import type { CSSProperties } from 'vue';
import { MITER_LIMIT, scene } from '@embedpdf/core-annotation';
import type { RenderItem } from '@embedpdf/core-annotation';
import { ghostOpacity, sceneViewBox, svgShapesOf } from '@embedpdf/web';

const props = defineProps<{ item: RenderItem }>();

// Nothing to draw until the annotation has area (the 0×0 draft at mouse-down).
const viewBox = computed(() => sceneViewBox(props.item.box));
const shapes = computed(() => svgShapesOf(scene(props.item), { miterLimit: MITER_LIMIT }));
const style = computed(
  (): CSSProperties => ({
    position: 'absolute',
    left: 0,
    top: 0,
    width: '100%',
    height: '100%',
    overflow: 'visible',
    pointerEvents: 'none',
    // A ghost is see-through as a whole, so its fill and stroke don't stack.
    ...(props.item.source === 'ghost'
      ? { opacity: ghostOpacity(props.item.ghostOpacity ?? 0.5) }
      : {}),
  }),
);
/** A shape's blend is CSS, never an attribute. */
const blendOf = (blend: string | undefined): CSSProperties | undefined =>
  blend ? { mixBlendMode: blend as CSSProperties['mixBlendMode'] } : undefined;
</script>

<template>
  <svg v-if="viewBox" :viewBox="viewBox" :style="style">
    <component
      :is="shape.tag"
      v-for="(shape, index) in shapes"
      :key="index"
      v-bind="shape.attributes"
      :style="blendOf(shape.blend)"
      >{{ shape.text }}</component
    >
  </svg>
</template>
