// packages/framework/angular/annotation/src/annotation-layer.ts
/**
 * `<epdf-annotation-layer>`: a page's annotations, the selection's outline and handles, the
 * tool's preview, and the text boxes being typed in. Put it in each page, above the rendered
 * page; while it's there, the render layer leaves the annotations out of the page's picture:
 *
 *   <ng-template epdfPage>
 *     <epdf-render-layer />
 *     <epdf-annotation-layer />
 *   </ng-template>
 *
 * Pure paint: it reads the plugin's items and chrome for the page and draws them. The pointer
 * reaches the plugin through the interaction hub (the Stage forwards it), and so does the
 * cursor. Each annotation is one drawing: its vector scene, the engine's baked picture, or a
 * look of yours from an `<ng-template [epdfAnnotation]>` inside the layer, which may keep the
 * layer's own drawing (`native`) and add to it. `<ng-template epdfHandle>` and
 * `<ng-template epdfRotationHandle>` draw the handles your way.
 *
 * What isn't Angular is `@embedpdf/web`'s, the same for every framework: which drawing each
 * annotation gets and the behaviors interactive looks register, the frames and chrome in
 * pixels, the scene as SVG elements, the text box editor, and the object URLs of baked pictures
 * and the stamp ghost.
 */
import { isPlatformBrowser, NgTemplateOutlet } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  contentChild,
  contentChildren,
  DestroyRef,
  effect,
  inject,
  Injector,
  PLATFORM_ID,
  signal,
  untracked,
} from '@angular/core';
import { annotationKey } from '@embedpdf/core';
import type { RenderItem } from '@embedpdf/core-annotation';
import {
  CapabilityBinding,
  injectKernelHost,
  injectPage,
  paintsPagePart,
} from '@embedpdf/angular/runtime';
import type { Annotation, TextItem } from '@embedpdf/plugin-annotation';
import { previewBucket } from '@embedpdf/plugin-annotation/contract/host';
import { InteractionToken } from '@embedpdf/plugin-interaction/contract';
import {
  annotationChromePaint,
  annotationDrawingOf,
  bakedAppearanceOf,
  createShownUrls,
  editingTextKeyOf,
  frameInPixels,
  ghostOpacity,
  layerTextBoxesOf,
  loadAppearanceUrls,
  loadObjectUrl,
  lookFrameOf,
  rectInPixels,
  registerRendererBehaviors,
  type AppearanceUrl,
  type FramePixels,
} from '@embedpdf/web';
import { EpdfAnnotationChrome } from './chrome';
import { EpdfAnnotationFrame, EpdfAnnotationNative } from './drawing';
import { annotationHostOf, pagePixelsOf, pageViewOf } from './page-reads';
import { injectChromeSettings } from './settings';
import {
  EpdfAnnotationBehaviorTemplate,
  EpdfAnnotationTemplate,
  EpdfHandleTemplate,
  EpdfRotationHandleTemplate,
  type AnnotationFrame,
  type AnnotationRendererEntry,
} from './templates';
import { EPDF_LOOK_SCALE, EpdfFreeTextBox } from './text-box';

const NO_ITEMS: readonly RenderItem[] = Object.freeze([]);
const NO_TEXTS: readonly TextItem[] = Object.freeze([]);
const NO_URLS: Readonly<Record<string, AppearanceUrl>> = Object.freeze({});

/** Your look of one annotation, with what its template gets. */
interface DrawnLook {
  readonly template: EpdfAnnotationTemplate;
  readonly annotation: Annotation;
  readonly frame: AnnotationFrame;
  /** Drawn at the annotation's 100% size, and scaled by the layer. */
  readonly scaled: boolean;
  /** Tells a rich text editor in the look how much the look is scaled. */
  readonly injector: Injector;
}

/** One annotation as the template draws it. */
interface Drawn {
  readonly item: RenderItem;
  /** Its frame in the layer's pixels. */
  readonly frame: FramePixels;
  /** The engine's picture of it, once loaded. */
  readonly url: string | null;
  /** The same picture as a look gets it: its `appearance`. */
  readonly appearance: { url: string } | null;
  /** Your look that draws it, when one does. */
  readonly look: DrawnLook | null;
  /** A sibling plugin's template that owns it while its behavior is engaged. */
  readonly owner: {
    readonly template: EpdfAnnotationBehaviorTemplate;
    readonly annotation: Annotation;
  } | null;
  /** The look takes the pointer. */
  readonly interactive: boolean;
  /** Keep the pointer and the focus out: a look that only draws, or a plugin's own input. */
  readonly inert: boolean;
}

@Component({
  selector: 'epdf-annotation-layer',
  imports: [
    NgTemplateOutlet,
    EpdfAnnotationFrame,
    EpdfAnnotationNative,
    EpdfAnnotationChrome,
    EpdfFreeTextBox,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'position: absolute; inset: 0; display: block; pointer-events: none' },
  template: `
    @for (drawn of drawings(); track drawn.item.id) {
      <!-- The layer's own drawing of it, which a look may keep: its \`native\`. -->
      <ng-template #native>
        <epdf-annotation-native [item]="drawn.item" [url]="drawn.url" />
      </ng-template>
      @if (drawn.owner; as owner) {
        <!-- A sibling plugin's controls place themselves in the layer and take the input;
             the annotation's own drawing keeps its frame. -->
        <ng-template #framedNative>
          <div [epdfAnnotationFrame]="drawn.frame" [frameBlend]="drawn.item.blend">
            <ng-container [ngTemplateOutlet]="native" />
          </div>
        </ng-template>
        <ng-container
          [ngTemplateOutlet]="owner.template.template"
          [ngTemplateOutletContext]="{
            $implicit: owner.annotation,
            annotation: owner.annotation,
            item: drawn.item,
            page: page,
            native: framedNative,
            hovered: drawn.item.hovered ?? false,
            selected: drawn.item.selected,
            interactive: true
          }"
        />
      } @else {
        @if (drawn.look; as look) {
          <div
            [epdfAnnotationFrame]="drawn.frame"
            [frameBlend]="drawn.item.blend"
            [frameInteractive]="drawn.interactive"
            [frameInert]="drawn.inert"
          >
            <ng-template #lookTemplate>
              <ng-container
                [ngTemplateOutlet]="look.template.template"
                [ngTemplateOutletInjector]="look.injector"
                [ngTemplateOutletContext]="{
                  $implicit: look.annotation,
                  annotation: look.annotation,
                  frame: look.frame,
                  native: native,
                  appearance: drawn.appearance,
                  hovered: drawn.item.hovered ?? false,
                  selected: drawn.item.selected,
                  interactive: drawn.interactive
                }"
              />
            </ng-template>
            @if (look.scaled) {
              <!-- Drawn at the annotation's 100% size, scaled with the page as a whole. -->
              <div
                style="position: absolute; left: 0; top: 0; transform-origin: 0 0"
                [style.width.px]="drawn.frame.design.width"
                [style.height.px]="drawn.frame.design.height"
                [style.transform]="'scale(' + drawn.frame.scale + ')'"
              >
                <ng-container [ngTemplateOutlet]="lookTemplate" />
              </div>
            } @else {
              <ng-container [ngTemplateOutlet]="lookTemplate" />
            }
          </div>
        } @else {
          <!-- Inert when an engaged behavior has no template of yours: its plugin owns the
               input (a link's anchor takes the click), and the annotation keeps its own look. -->
          <div
            [epdfAnnotationFrame]="drawn.frame"
            [frameBlend]="drawn.item.blend"
            [frameInert]="drawn.inert"
          >
            <ng-container [ngTemplateOutlet]="native" />
          </div>
        }
      }
    }
    @for (text of texts(); track text.id) {
      <div [epdfFreeTextBox]="text" [outline]="textOutline()"></div>
    }
    @if (ghost(); as ghost) {
      <!-- The armed stamp, see-through, in the box a click would place it in. -->
      <img
        alt=""
        draggable="false"
        style="position: absolute; max-width: none; max-height: none; pointer-events: none; transform-origin: center"
        [attr.src]="ghost.url"
        [style.left.px]="ghost.box.left"
        [style.top.px]="ghost.box.top"
        [style.width.px]="ghost.box.width"
        [style.height.px]="ghost.box.height"
        [style.opacity]="ghost.opacity"
        [style.transform]="ghost.rotation ? 'rotate(' + ghost.rotation + 'deg)' : null"
      />
    }
    <epdf-annotation-chrome
      [handle]="handleTemplate()?.template ?? null"
      [rotationHandle]="rotationHandleTemplate()?.template ?? null"
    />
  `,
})
export class EpdfAnnotationLayer {
  protected readonly page = injectPage('<epdf-annotation-layer>');
  private readonly injector = inject(Injector);
  private readonly annotation = annotationHostOf(this.page, '<epdf-annotation-layer>');
  private readonly interaction = new CapabilityBinding(
    injectKernelHost('<epdf-annotation-layer>'),
    () => InteractionToken,
    () => this.page.documentId,
  );
  private readonly chrome = injectChromeSettings();

  // ── your templates ───────────────────────────────────────────────────────────

  private readonly looks = contentChildren(EpdfAnnotationTemplate, { descendants: true });
  private readonly behaviors = contentChildren(EpdfAnnotationBehaviorTemplate, {
    descendants: true,
  });
  protected readonly handleTemplate = contentChild(EpdfHandleTemplate, { descendants: true });
  protected readonly rotationHandleTemplate = contentChild(EpdfRotationHandleTemplate, {
    descendants: true,
  });

  /**
   * The renderer entries, in the order the templates are written: the first look that matches
   * wins. The same array while every entry stays the same.
   */
  private readonly renderers = computed(
    (): readonly AnnotationRendererEntry[] =>
      [
        ...this.behaviors().map((template) => template.renderer()),
        ...this.looks().map((template) => template.renderer()),
      ].filter((entry) => entry !== null),
    {
      equal: (left, right) =>
        left.length === right.length && left.every((entry, index) => entry === right[index]),
    },
  );
  /** Goes up when the behaviors register again, so each drawing is decided again. */
  private readonly registrations = signal(0);

  // ── what the page shows ──────────────────────────────────────────────────────

  private readonly view = pageViewOf(this.page);
  private readonly pixels = pagePixelsOf(this.page);

  private readonly items = this.annotation.select(
    (annotation) => annotation.listPageItems(this.page.ref, this.view()),
    NO_ITEMS,
  );
  private readonly allTexts = this.annotation.select(
    (annotation) => annotation.listTextItems(this.page.ref, this.view()),
    NO_TEXTS,
  );
  /** The active tool: an interactive look's function is asked about it, so a tool change redraws. */
  private readonly activeToolId = this.interaction.select(
    (interaction) => interaction.getActiveToolId() ?? '',
    '',
  );

  /** The baked pictures' URLs, by annotation key, for the page's appearance epoch and bake scale. */
  private readonly urls = signal<Readonly<Record<string, AppearanceUrl>>>(NO_URLS);
  /** The pictures shown stay valid until the next ones are shown. */
  private readonly shown = createShownUrls();
  // A move or a turn leaves the epoch as it is (the same pixels, placed elsewhere), and live
  // gestures don't touch it: nothing loads mid-drag.
  private readonly appearanceEpoch = this.annotation.select(
    (annotation) => annotation.getAppearanceEpoch(this.page.ref),
    '',
  );
  // Zoom steps inside one rung of the document's appearance lattice bake nothing again.
  private readonly bakeScale = this.annotation.select(
    (annotation) => annotation.getBakeScale(this.page.transform().renderScale),
    0,
  );

  /** The text box being typed in, by key: while it is, a look's editor takes the keys. */
  private readonly editingKey = computed(() => editingTextKeyOf(this.allTexts(), annotationKey));

  /** One injector per look, by item: kept while the item is drawn, so the look is never made again. */
  private readonly lookInjectors = new Map<string, Injector>();

  protected readonly drawings = computed((): readonly Drawn[] => {
    this.activeToolId();
    this.registrations();
    const annotation = this.annotation.capability();
    const renderers = this.renderers();
    const looks = this.looks();
    const behaviors = this.behaviors();
    const pixels = this.pixels();
    const urls = this.urls();
    const editingKey = this.editingKey();
    const drawings = this.items().map((item): Drawn => {
      const frame = frameInPixels(item.frame, pixels);
      const drawn: Drawn = {
        item,
        frame,
        url: urls[item.id]?.url ?? null,
        appearance: bakedAppearanceOf(urls, item.id),
        look: null,
        owner: null,
        interactive: false,
        inert: false,
      };
      const record = item.annotation;
      if (!record || !annotation) return drawn;
      // Ownership beats looks: an engaged behavior's template is authoritative (a form
      // plugin's controls own their DOM); looks apply only to what the layer owns, and draw
      // without the pointer. While its text box is typed in, a look's editor takes the keys.
      const typing = editingKey !== null && annotationKey(record.ref) === editingKey;
      const drawing = annotationDrawingOf(record, annotation, renderers, typing);
      switch (drawing.kind) {
        case 'native':
          return { ...drawn, inert: drawing.inert };
        case 'owned': {
          const template = behaviors.find((behavior) => behavior.renderer() === drawing.entry);
          return template ? { ...drawn, owner: { template, annotation: record } } : drawn;
        }
        case 'look': {
          const template = looks.find((look) => look.renderer() === drawing.entry);
          if (!template) return drawn;
          const scaled = drawing.entry.scale !== false;
          return {
            ...drawn,
            look: {
              template,
              annotation: record,
              frame: lookFrameOf(frame, scaled),
              scaled,
              injector: this.lookInjectorOf(item.id),
            },
            interactive: drawing.interactive,
            inert: drawing.inert,
          };
        }
      }
    });
    // Forget the injectors of looks no longer drawn: a look drawn again starts afresh.
    const drawnLooks = new Set(drawings.flatMap((drawn) => (drawn.look ? [drawn.item.id] : [])));
    for (const id of this.lookInjectors.keys()) {
      if (!drawnLooks.has(id)) this.lookInjectors.delete(id);
    }
    return drawings;
  });

  /** How much the layer scales each look, by item: 1 for a look drawn at its size on screen. */
  private readonly lookScales = computed(() => {
    const scales = new Map<string, number>();
    for (const drawn of this.drawings()) {
      if (drawn.look) scales.set(drawn.item.id, drawn.look.scaled ? drawn.frame.scale : 1);
    }
    return scales;
  });

  /** The text boxes the layer draws: not the ones a look of yours draws, which edits them there. */
  protected readonly texts = computed((): readonly TextItem[] =>
    layerTextBoxesOf(this.allTexts(), this.items(), this.renderers(), annotationKey),
  );

  protected readonly textOutline = computed(
    () => annotationChromePaint(this.chrome.chrome(), this.chrome.accent()).textOutline,
  );

  // ── the armed stamp's ghost ──────────────────────────────────────────────────

  private readonly imageGhost = this.annotation.select(
    (annotation) => annotation.getImageGhost(this.page.ref),
    null,
  );
  private readonly armedStamp = this.annotation.select(
    (annotation) => annotation.getArmedStamp(),
    null,
    Object.is,
  );
  /**
   * The ghost is a picture of vector artwork, sharp at one size: the size class that covers the
   * box's device width. The plugin keeps one picture per class, so a zoom never renders per frame.
   */
  private readonly ghostBucket = computed(() => {
    const ghost = this.imageGhost();
    return ghost ? previewBucket(ghost.box.width * this.page.transform().renderScale) : 0;
  });
  private readonly ghostUrl = signal<string | null>(null);
  protected readonly ghost = computed(() => {
    const ghost = this.imageGhost();
    const url = this.ghostUrl();
    if (!ghost || !url) return null;
    return {
      url,
      box: rectInPixels(ghost.box, this.pixels()),
      opacity: ghostOpacity(ghost.opacity),
      rotation: ghost.rot,
    };
  });

  constructor() {
    // While it's here, the page's picture leaves the annotations to it.
    paintsPagePart(() => this.page.ref, 'annotations');
    this.registerBehaviors();
    if (!isPlatformBrowser(inject(PLATFORM_ID))) return;
    inject(DestroyRef).onDestroy(() => this.shown.release());
    this.loadAppearances();
    this.loadGhost();
  }

  /** The injector a look's template gets for one item: the look's scale, followed live. */
  private lookInjectorOf(id: string): Injector {
    let injector = this.lookInjectors.get(id);
    if (!injector) {
      const scale = computed(() => this.lookScales().get(id) ?? 1);
      injector = Injector.create({
        providers: [{ provide: EPDF_LOOK_SCALE, useValue: scale }],
        parent: this.injector,
      });
      this.lookInjectors.set(id, injector);
    }
    return injector;
  }

  /**
   * An interactive look takes the pointer through a behavior the plugin knows, registered once
   * per document and look however many pages show the layer (`@embedpdf/web` counts them). The
   * looks are the same entries on every page, so keep the functions you give `epdfAnnotation`
   * and `epdfAnnotationInteractive` in fields: a function made anew registers again.
   */
  private registerBehaviors(): void {
    effect((onCleanup) => {
      const annotation = this.annotation.capability();
      const renderers = this.renderers();
      if (annotation && renderers.length > 0) {
        onCleanup(
          untracked(() =>
            registerRendererBehaviors(annotation, renderers, () => untracked(this.activeToolId)),
          ),
        );
      }
      this.registrations.update((count) => count + 1);
    });
  }

  /**
   * The baked pictures, loaded again when the page's appearance epoch or the bake scale changes;
   * the ones shown stay valid until the next are shown.
   */
  private loadAppearances(): void {
    effect((onCleanup) => {
      const annotation = this.annotation.capability();
      const scale = this.bakeScale();
      this.appearanceEpoch();
      if (!annotation || !scale) return;
      const page = this.page.ref;
      onCleanup(
        untracked(() =>
          loadAppearanceUrls(
            this.shown,
            (abort) => annotation.renderAppearances(page, scale, abort),
            annotationKey,
            (urls) => this.urls.set(urls),
          ),
        ),
      );
    });
  }

  /**
   * The armed stamp's ghost picture, for its size class. The previous class's picture stays up
   * until this one is there, so a zoom across a class boundary never flickers; a disarm drops it.
   */
  private loadGhost(): void {
    effect((onCleanup) => {
      const annotation = this.annotation.capability();
      const bucket = this.ghostBucket();
      this.armedStamp();
      if (!annotation || !bucket) {
        this.ghostUrl.set(null);
        return;
      }
      onCleanup(
        untracked(() =>
          loadObjectUrl(
            () => annotation.renderArmedStampPreview(bucket),
            (url) => this.ghostUrl.set(url),
          ),
        ),
      );
    });
  }
}

// packages/framework/vue/src/annotation/AnnotationLayer.vue
<!--
  <AnnotationLayer>: a page's annotations, the selection's outline and
  handles, the tool's preview and the text boxes being typed in. Put it in the
  Stage's #page slot above the rendered page: while it's there, the render
  layer leaves the annotations out of the page's picture.

  Pure paint: it reads the plugin's per-page render items and chrome and draws
  them. Pointer events reach the plugin through the interaction hub (the
  Stage forwards them), and so does the cursor. Each annotation is one drawing:
  its vector scene, the engine's baked appearance, or a look of yours from
  `renderers`, which may keep the layer's own drawing (`native`) and add to it.
  The `#handle` and `#rotation-handle` slots draw the handles your way.
-->
<script setup lang="ts">
import { computed, h, markRaw, onUnmounted, shallowRef, toRaw, watch } from 'vue';
import type { Component } from 'vue';
import { annotationKey, shallowEqual } from '@embedpdf/core';
import type { RenderItem } from '@embedpdf/core-annotation';
import type { Annotation, TextItem } from '@embedpdf/plugin-annotation';
// The layer is framework code, so it resolves the full host lens (page items,
// chrome, appearances…): the same runtime token as the public one, typed wider.
import { AnnotationToken as AnnotationHostToken } from '@embedpdf/plugin-annotation/contract/host';
import { InteractionToken } from '@embedpdf/plugin-interaction/contract';
import {
  annotationDrawingOf,
  bakedAppearanceOf,
  createShownUrls,
  editingTextKeyOf,
  layerTextBoxesOf,
  loadAppearanceUrls,
  registerRendererBehaviors,
} from '@embedpdf/web';
import type { AnnotationDrawing, AppearanceUrl } from '@embedpdf/web';
import { devWarn } from '../dev';
import { usePaintsPagePart } from '../page-layers';
import { useOptionalCapability, useOptionalSelector } from '../runtime/capabilities';
import { usePage } from '../runtime/page';
import AnnotationChrome from './AnnotationChrome.vue';
import AnnotationFrame from './AnnotationFrame.vue';
import AnnotationLook from './AnnotationLook.vue';
import FreeTextBox from './FreeTextBox.vue';
import NativeDrawing from './NativeDrawing.vue';
import StampGhost from './StampGhost.vue';
import type { AnnotationRenderer, HandleProps, RotationHandleProps } from './types';

const props = defineProps<{
  /**
   * Your own look for some annotations: each renderer says which ones (`for`)
   * and with which component. Define the list once, in `<script setup>`.
   */
  renderers?: AnnotationRenderer[];
}>();

const slots = defineSlots<{
  /** Draw each handle yourself, in place of the layer's: it gets {@link HandleProps}. */
  handle?(props: HandleProps): unknown;
  /** Draw the rotation handle yourself: it gets {@link RotationHandleProps}. */
  'rotation-handle'?(props: RotationHandleProps): unknown;
}>();

type Drawing = AnnotationDrawing<AnnotationRenderer>;

const NO_ITEMS: readonly RenderItem[] = Object.freeze([]);
const NO_TEXTS: readonly TextItem[] = Object.freeze([]);

const page = usePage();
// While it's here, the page's picture leaves the annotations to it.
usePaintsPagePart(
  computed(() => page.value.ref),
  'annotations',
);
const annotation = useOptionalCapability(AnnotationHostToken);
const interaction = useOptionalCapability(InteractionToken);
// The active tool decides which interactive renderers take the pointer, so a
// tool change draws the layer again (`interactive` functions read it live).
const activeToolId = useOptionalSelector(
  InteractionToken,
  (hub) => hub.getActiveToolId() as string,
  '',
);

// The page's view (its zoom and turn) projects annotations that keep their
// size or stay upright on screen (`noZoom`, `noRotate`) inside the plugin: no
// flag logic lives here. `zoom`, not `viewScale`: 1 is the page's 100%.
const items = useOptionalSelector(
  AnnotationHostToken,
  (host) => {
    const { transform, ref } = page.value;
    return host.listPageItems(ref, { zoom: transform.zoom, rotation: transform.rotation });
  },
  NO_ITEMS,
  shallowEqual,
);
const texts = useOptionalSelector(
  AnnotationHostToken,
  (host) => {
    const { transform, ref } = page.value;
    return host.listTextItems(ref, { zoom: transform.zoom, rotation: transform.rotation });
  },
  NO_TEXTS,
  shallowEqual,
);

// ── your renderers ───────────────────────────────────────────────────────────

/** Bumped when the renderers' behaviors register again, so the drawings are read again. */
const registrations = shallowRef(0);
// An `interactive` renderer takes the pointer through a behavior the plugin
// knows, registered once per capability and entry however many pages mount
// the layer. Entry identity is the key, so a list written inline in the
// template (a new array on every render) registers again each time: say so.
watch(
  [annotation, () => props.renderers],
  ([host, renderers], previous, onCleanup) => {
    const before = previous?.[1];
    if (renderers && before && renderers !== before && shallowEqual(renderers, before)) {
      devWarn(
        'annotation-renderers-inline',
        '<AnnotationLayer :renderers> was given a new array with the same entries — define it ' +
          'once in <script setup>, because entry identity keys the behavior registration.',
      );
    }
    if (host && renderers) {
      onCleanup(
        registerRendererBehaviors(host, renderers, () =>
          String(interaction.value?.getActiveToolId() ?? ''),
        ),
      );
    }
    registrations.value += 1;
  },
  { immediate: true },
);

// ── baked appearances ────────────────────────────────────────────────────────

const urls = shallowRef<Record<string, AppearanceUrl>>({});
// The pictures shown stay valid until the next ones are shown.
const shown = createShownUrls();
onUnmounted(() => shown.release());
// Baked annotations draw from engine rasters: load them again when the page's
// baked set or an appearance version changes (a stamp just placed, a resize
// whose new appearance arrived), and when the bake scale does. A move or a
// turn leaves the epoch as it is (the same pixels, placed elsewhere), and live
// gestures don't touch it: nothing loads mid-drag.
const bakedKey = useOptionalSelector(
  AnnotationHostToken,
  (host) => host.getAppearanceEpoch(page.value.ref),
  '',
);
// The bake scale follows the document's render policy: zoom steps inside one
// rung of the appearance lattice bake nothing again.
const bakeScale = useOptionalSelector(
  AnnotationHostToken,
  (host) => host.getBakeScale(page.value.transform.renderScale),
  0,
);
watch(
  [annotation, () => page.value.ref, bakeScale, bakedKey],
  ([host, pageRef, scale], _previous, onCleanup) => {
    if (!host || !scale) return;
    onCleanup(
      loadAppearanceUrls(
        shown,
        (signal) => host.renderAppearances(pageRef, scale, signal),
        annotationKey,
        (loaded) => (urls.value = loaded),
      ),
    );
  },
  { immediate: true },
);

// ── what each annotation draws ───────────────────────────────────────────────

/** The text box being typed in, by key: while it is, a look's editor takes the keys. */
const editingKey = computed(() => editingTextKeyOf(texts.value, annotationKey));

interface Drawn {
  item: RenderItem;
  annotation: Annotation | null;
  drawing: Drawing;
}

/** The layer's own drawing, for what isn't an annotation yet (a drawing in progress, a ghost). */
const NATIVE: Drawing = { kind: 'native', inert: false };

// Ownership beats looks: an engaged behavior's renderer is authoritative (the
// form plugin's controls own their DOM); `for` rules apply only to what the
// layer owns, and draw without the pointer. Read whenever the items, the
// active tool or the registrations change: `interactive` functions and the
// plugin's behaviors are asked here.
const drawn = computed((): Drawn[] => {
  void activeToolId.value;
  void registrations.value;
  const host = annotation.value;
  const renderers = props.renderers;
  return items.value.map((item): Drawn => {
    const record = item.annotation ?? null;
    if (!record || !host) return { item, annotation: null, drawing: NATIVE };
    const typing = editingKey.value !== null && annotationKey(record.ref) === editingKey.value;
    return { item, annotation: record, drawing: annotationDrawingOf(record, host, renderers, typing) };
  });
});

/** The text boxes the layer draws itself: one your renderer draws is edited there (`useRichTextEditor()`). */
const ownTexts = computed(() =>
  layerTextBoxesOf(texts.value, items.value, props.renderers, annotationKey),
);

// `native` for a renderer: one component per annotation, kept by its id, that
// draws the layer's current drawing of it. The same component across renders,
// so a drag moves the drawing instead of replacing it.
const itemsById = computed(() => new Map(items.value.map((item) => [item.id, item])));
const natives = new Map<string, Component>();
const framedNatives = new Map<string, Component>();
function nativeOf(id: string): Component {
  let native = natives.get(id);
  if (!native) {
    native = markRaw(() => {
      const item = itemsById.value.get(id);
      return item ? h(NativeDrawing, { item, url: urls.value[id]?.url ?? null }) : null;
    });
    natives.set(id, native);
  }
  return native;
}
/** The native drawing in its frame: what a sibling plugin's renderer keeps where the layer draws it. */
function framedNativeOf(id: string): Component {
  let native = framedNatives.get(id);
  if (!native) {
    native = markRaw(() => {
      const item = itemsById.value.get(id);
      return item
        ? h(AnnotationFrame, { item, page: page.value }, () => h(nativeOf(id)))
        : null;
    });
    framedNatives.set(id, native);
  }
  return native;
}
// Forget the drawings of annotations that are gone.
watch(itemsById, (shown) => {
  for (const id of natives.keys()) if (!shown.has(id)) natives.delete(id);
  for (const id of framedNatives.keys()) if (!shown.has(id)) framedNatives.delete(id);
});

/** A renderer's component, never a reactive proxy of it (a list kept in a `ref`). */
const componentOf = (component: Component): Component => toRaw(component);
</script>

<template>
  <div :style="{ position: 'absolute', inset: 0, pointerEvents: 'none' }">
    <template v-for="{ item, annotation: record, drawing } in drawn" :key="item.id">
      <component
        :is="componentOf(drawing.entry.component)"
        v-if="drawing.kind === 'owned' && record"
        :annotation="record"
        :item="item"
        :page="page"
        :native="framedNativeOf(item.id)"
        :hovered="item.hovered ?? false"
        :selected="item.selected"
        :interactive="true"
      />
      <AnnotationFrame
        v-else-if="drawing.kind === 'look' && record"
        :item="item"
        :page="page"
        :interactive="drawing.interactive"
        :inert="drawing.inert"
      >
        <AnnotationLook
          :component="componentOf(drawing.entry.component)"
          :scaled="drawing.entry.scale !== false"
          :annotation="record"
          :item="item"
          :page="page"
          :native="nativeOf(item.id)"
          :appearance="bakedAppearanceOf(urls, item.id)"
          :interactive="drawing.interactive"
        />
      </AnnotationFrame>
      <!-- Inert when an engaged behavior has no renderer of yours: its plugin
           owns the input (a link's anchor takes the click), and the annotation
           keeps its own look. -->
      <AnnotationFrame
        v-else
        :item="item"
        :page="page"
        :inert="drawing.kind === 'native' && drawing.inert"
      >
        <NativeDrawing :item="item" :url="urls[item.id]?.url ?? null" />
      </AnnotationFrame>
    </template>
    <FreeTextBox v-for="text in ownTexts" :key="text.id" :item="text" :page="page" />
    <StampGhost :page="page" />
    <AnnotationChrome :page="page">
      <template v-if="slots.handle" #handle="handle">
        <slot name="handle" v-bind="handle" />
      </template>
      <template v-if="slots['rotation-handle']" #rotation-handle="handle">
        <slot name="rotation-handle" v-bind="handle" />
      </template>
    </AnnotationChrome>
  </div>
</template>
