// packages/framework/vue/src/form/FieldPictures.vue
<!--
  The pictures of a page's fields, as the engine draws them, from the render
  plugin's shared field pictures. Every state is loaded, so a check box shows
  its new state as soon as its value changes; hidden widgets aren't drawn.
-->
<script setup lang="ts">
import { computed, onUnmounted, shallowRef, watch } from 'vue';
import { annotationKey, shallowEqual } from '@embedpdf/core';
import { FormToken as FormHostToken } from '@embedpdf/plugin-form/contract/host';
import type { ShownWidget } from '@embedpdf/plugin-form/contract/host';
import { RenderToken } from '@embedpdf/plugin-render/contract/host';
import {
  createShownUrls,
  loadFieldPictureUrls,
  rectInPixels,
  shownFieldPicture,
  type AppearanceUrl,
} from '@embedpdf/web';
import { useOptionalCapability, useOptionalSelector } from '../runtime/capabilities';
import { usePage } from '../runtime/page';

const NO_WIDGETS: readonly ShownWidget[] = Object.freeze([]);

const page = usePage();
const render = useOptionalCapability(RenderToken);
// The same list until a widget on this page changes.
const widgets = useOptionalSelector(
  FormHostToken,
  (form) => form.listShownWidgets(page.value.ref),
  NO_WIDGETS,
  shallowEqual,
);
// Loaded again when the page's fields change, and at appearance-scale crossings.
const epoch = useOptionalSelector(
  RenderToken,
  (lens) => lens.getFieldAppearanceEpoch(page.value.ref),
  0,
);
const scale = useOptionalSelector(
  RenderToken,
  (lens) => lens.getAppearanceScale(page.value.transform.renderScale),
  0,
);

const urls = shallowRef<Record<string, AppearanceUrl>>({});
// The pictures shown stay valid until the next ones are shown.
const shown = createShownUrls();
onUnmounted(() => shown.release());
watch(
  [render, () => page.value.ref, scale, epoch],
  ([lens, pageRef, at], _previous, onCleanup) => {
    if (!lens || !at) return;
    onCleanup(
      loadFieldPictureUrls(
        shown,
        (signal) => lens.renderFieldAppearances(pageRef, { scale: at, signal }),
        annotationKey,
        (loaded) => (urls.value = loaded),
      ),
    );
  },
  { immediate: true },
);

const pictures = computed(() =>
  widgets.value.flatMap((widget) => {
    const key = annotationKey(widget.ref);
    const picture = shownFieldPicture(urls.value, key, widget.appearanceState);
    return picture
      ? [{ key, url: picture.url, frame: rectInPixels(picture.box, page.value.transform) }]
      : [];
  }),
);
</script>

<template>
  <img
    v-for="picture in pictures"
    :key="picture.key"
    :src="picture.url"
    alt=""
    draggable="false"
    :style="{
      position: 'absolute',
      left: `${picture.frame.left}px`,
      top: `${picture.frame.top}px`,
      width: `${picture.frame.width}px`,
      height: `${picture.frame.height}px`,
      // A global `img { max-width: 100% }` reset would clamp it.
      maxWidth: 'none',
      maxHeight: 'none',
      pointerEvents: 'none',
    }"
  />
</template>

// packages/framework/svelte/src/form/FieldPictures.svelte
<!--
  The pictures of a page's fields, as the engine draws them, from the render plugin's shared field
  pictures. Every state is loaded, so a check box shows its new state as soon as its value
  changes; hidden widgets aren't drawn.
-->
<script lang="ts">
  import { untrack } from 'svelte';
  import { annotationKey } from '@embedpdf/core';
  import {
    FormToken as FormHostToken,
    type ShownWidget,
  } from '@embedpdf/plugin-form/contract/host';
  import { RenderToken } from '@embedpdf/plugin-render/contract/host';
  import {
    createShownUrls,
    loadFieldPictureUrls,
    rectInPixels,
    shownFieldPicture,
    type AppearanceUrl,
  } from '@embedpdf/web';
  import { usePage } from '../runtime/page';
  import {
    shallowArray,
    useOptionalCapability,
    useOptionalSelector,
  } from '../runtime/readers.svelte';

  const NO_WIDGETS: readonly ShownWidget[] = Object.freeze([]);

  const page = usePage();
  const render = useOptionalCapability(RenderToken);
  // The same list until a widget on this page changes.
  const widgets = useOptionalSelector(
    FormHostToken,
    (form) => form.listShownWidgets(page.ref),
    NO_WIDGETS,
    shallowArray,
  );
  // Loaded again when the page's fields change, and at appearance-scale crossings.
  const epoch = useOptionalSelector(
    RenderToken,
    (renderer) => renderer.getFieldAppearanceEpoch(page.ref),
    0,
  );
  const scale = useOptionalSelector(
    RenderToken,
    (renderer) => renderer.getAppearanceScale(page.transform.renderScale),
    0,
  );

  let urls = $state.raw<Record<string, AppearanceUrl>>({});
  // The pictures shown stay valid until the next ones are shown.
  const shown = createShownUrls();
  $effect(() => () => shown.release());
  $effect(() => {
    const renderer = render.current;
    const ref = page.ref;
    const at = scale.current;
    void epoch.current;
    if (!renderer || !at) return;
    return untrack(() =>
      loadFieldPictureUrls(
        shown,
        (signal) => renderer.renderFieldAppearances(ref, { scale: at, signal }),
        annotationKey,
        (loaded) => (urls = loaded),
      ),
    );
  });

  const pictures = $derived(
    widgets.current.flatMap((widget) => {
      const key = annotationKey(widget.ref);
      const picture = shownFieldPicture(urls, key, widget.appearanceState);
      return picture
        ? [{ key, url: picture.url, frame: rectInPixels(picture.box, page.transform) }]
        : [];
    }),
  );
</script>

<!-- A global `img { max-width: 100% }` reset would clamp a picture: the sizes are explicit. -->
{#each pictures as picture (picture.key)}
  <img
    src={picture.url}
    alt=""
    draggable="false"
    style="position: absolute; max-width: none; max-height: none; pointer-events: none"
    style:left="{picture.frame.left}px"
    style:top="{picture.frame.top}px"
    style:width="{picture.frame.width}px"
    style:height="{picture.frame.height}px"
  />
{/each}
