// docs/content/samples/annotation/download.vue/SaveBar.vue
<!-- The annotations are part of the document: the downloaded PDF has every one. -->
<script setup lang="ts">
import { saveFile, useDocument, useDocuments } from '@embedpdf/vue/runtime';
import { useInteraction, useInteractionState } from '@embedpdf/vue/interaction';

const documents = useDocuments();
const interaction = useInteraction();
const { activeToolId } = useInteractionState();
const { hasUnsavedChanges } = useDocument();

async function download() {
  saveFile(await documents.download(), 'ebook-annotated.pdf');
}
</script>

<template>
  <div class="toolbar">
    <button
      type="button"
      class="button"
      :aria-pressed="activeToolId === 'ink'"
      @click="interaction.activateTool(activeToolId === 'ink' ? 'pointer' : 'ink')"
    >
      Pen
    </button>
    <button type="button" class="button" @click="download">Download the PDF</button>
    <span class="spacer" />
    <output class="readout">{{ hasUnsavedChanges ? 'Unsaved changes' : 'All saved' }}</output>
  </div>
</template>

// cloudpdf/website/src/samples/annotation/download.svelte/SaveBar.svelte
<!-- The annotations are part of the document: the downloaded PDF has every one. -->
<script lang="ts">
  import { saveFile, useDocument, useDocuments } from '@embedpdf/svelte/runtime';
  import { useInteraction, useInteractionState } from '@embedpdf/svelte/interaction';

  const documents = useDocuments();
  const interaction = useInteraction();
  const activeToolId = useInteractionState((state) => state.activeToolId);
  const hasUnsavedChanges = useDocument((document) => document.hasUnsavedChanges);

  async function download() {
    saveFile(await documents.download(), 'ebook-annotated.pdf');
  }
</script>

<div class="toolbar">
  <button
    type="button"
    class="button"
    aria-pressed={activeToolId.current === 'ink'}
    onclick={() => interaction.activateTool(activeToolId.current === 'ink' ? 'pointer' : 'ink')}
  >
    Pen
  </button>
  <button type="button" class="button" onclick={download}>Download the PDF</button>
  <span class="spacer"></span>
  <output class="readout">{hasUnsavedChanges.current ? 'Unsaved changes' : 'All saved'}</output>
</div>
