// website/src/samples/snippets/concepts/branded-text-box.vue.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useRichTextEditor, type AnnotationRendererProps } from '@embedpdf/vue/annotation';

const props = defineProps<AnnotationRendererProps>();

const { ref: editorRef, editing, style } = useRichTextEditor(
  () => props.annotation,
  () => props.page,
);
const rect = computed(() => props.page.transform.pageToViewRect(props.box));
</script>

<template>
  <div
    :ref="editorRef"
    :class="['text-box', { editing }]"
    :style="[
      {
        position: 'absolute',
        left: `${rect.x}px`,
        top: `${rect.y}px`,
        width: `${rect.width}px`,
        height: `${rect.height}px`,
      },
      style,
    ]"
  />
</template>

// docs/content/snippets/concepts/branded-text-box.svelte.svelte
<script lang="ts">
  import { useRichTextEditor, type AnnotationRendererProps } from '@embedpdf/svelte/annotation';

  let { annotation, box, page }: AnnotationRendererProps = $props();

  const editor = useRichTextEditor(
    () => annotation,
    () => page,
  );
  const rect = $derived(page.transform.pageToViewRect(box));
</script>

<div
  {@attach editor.attach}
  class={['text-box', editor.editing && 'editing']}
  style="position: absolute; left: {rect.x}px; top: {rect.y}px; width: {rect.width}px; height: {rect.height}px; {editor.style}"
></div>
