// cloudpdf/website/src/samples/snippets/concepts/layers.react.tsx
import { AnnotationLayer } from '@embedpdf/react/annotation';
import { RenderLayer } from '@embedpdf/react/render';
import { SearchLayer } from '@embedpdf/react/search';
import { SelectionLayer } from '@embedpdf/react/selection';
import { Stage } from '@embedpdf/react/stage';

export function Pages() {
  return (
    <Stage>
      {() => (
        <>
          <RenderLayer annotations={false} />
          <SearchLayer />
          <SelectionLayer />
          <AnnotationLayer />
        </>
      )}
    </Stage>
  );
}

// docs/content/snippets/concepts/layers.svelte.svelte
<script lang="ts">
  import { AnnotationLayer } from '@embedpdf/svelte/annotation';
  import { RenderLayer } from '@embedpdf/svelte/render';
  import { SearchLayer } from '@embedpdf/svelte/search';
  import { SelectionLayer } from '@embedpdf/svelte/selection';
  import { Stage } from '@embedpdf/svelte/stage';
</script>

<Stage>
  <RenderLayer annotations={false} />
  <SearchLayer />
  <SelectionLayer />
  <AnnotationLayer />
</Stage>
