// website/src/samples/snippets/concepts/layers.vue.vue
<script setup lang="ts">
import { AnnotationLayer } from '@embedpdf/vue/annotation';
import { RenderLayer } from '@embedpdf/vue/render';
import { SearchLayer } from '@embedpdf/vue/search';
import { SelectionLayer } from '@embedpdf/vue/selection';
import { Stage } from '@embedpdf/vue/stage';
</script>

<template>
  <Stage>
    <template #page>
      <RenderLayer />
      <SearchLayer />
      <SelectionLayer />
      <AnnotationLayer />
    </template>
  </Stage>
</template>

// docs/content/snippets/concepts/layers.svelte.svelte
<script lang="ts">
  import { AnnotationLayer } from '@embedpdf/svelte/annotation';
  import { RenderLayer } from '@embedpdf/svelte/render';
  import { SearchLayer } from '@embedpdf/svelte/search';
  import { SelectionLayer } from '@embedpdf/svelte/selection';
  import { Stage } from '@embedpdf/svelte/stage';
</script>

<Stage>
  <RenderLayer />
  <SearchLayer />
  <SelectionLayer />
  <AnnotationLayer />
</Stage>
