// docs/content/samples/documents/scope.vue/SideBySide.vue
<script setup lang="ts">
import { DocumentGate, DocumentScope, useDocumentsState } from '@embedpdf/vue/runtime';
import { Stage } from '@embedpdf/vue/stage';
import { RenderLayer } from '@embedpdf/vue/render';
import Header from './Header.vue';

const { documents } = useDocumentsState();
</script>

<template>
  <div class="split">
    <section v-for="document in documents" :key="document.id" class="pane">
      <DocumentScope :id="document.id">
        <DocumentGate>
          <template #fallback><p class="loading">Opening…</p></template>
          <Header />
          <Stage class="stage">
            <template #page><RenderLayer /></template>
          </Stage>
        </DocumentGate>
      </DocumentScope>
    </section>
  </div>
</template>

// website/src/samples/documents/scope.svelte/SideBySide.svelte
<script lang="ts">
  import { DocumentGate, DocumentScope, useDocumentsState } from '@embedpdf/svelte/runtime';
  import { RenderLayer } from '@embedpdf/svelte/render';
  import { Stage } from '@embedpdf/svelte/stage';
  import Header from './Header.svelte';

  const open = useDocumentsState();
</script>

<div class="split">
  {#each open.documents as document (document.id)}
    <section class="pane">
      <DocumentScope id={document.id}>
        <DocumentGate>
          {#snippet fallback()}
            <p class="loading">Opening…</p>
          {/snippet}
          <Header />
          <Stage class="stage">
            <RenderLayer />
          </Stage>
        </DocumentGate>
      </DocumentScope>
    </section>
  {/each}
</div>
