// packages/plugin-document-manager/src/shared/components/file-picker.tsx
import { ChangeEvent, useEffect, useRef } from '@framework';
import { useDocumentManagerCapability, useDocumentManagerPlugin } from '../hooks';
import { PdfErrorReason, Task } from '@embedpdf/models';
import { OpenDocumentResponse, OpenFileDialogOptions } from '@embedpdf/plugin-document-manager';

export function FilePicker() {
  const { plugin } = useDocumentManagerPlugin();
  const { provides } = useDocumentManagerCapability();
  const inputRef = useRef<HTMLInputElement>(null);
  const taskRef = useRef<Task<OpenDocumentResponse, PdfErrorReason> | null>(null);
  const optionsRef = useRef<OpenFileDialogOptions | undefined>(undefined);

  useEffect(() => {
    if (!plugin?.onOpenFileRequest) return;
    const unsub = plugin.onOpenFileRequest(({ task, options }) => {
      taskRef.current = task;
      optionsRef.current = options;
      inputRef.current?.click();
    });
    return unsub;
  }, [plugin]);

  const onChange = async (e: ChangeEvent<HTMLInputElement>) => {
    const file = (e.currentTarget as HTMLInputElement).files?.[0];
    if (!file || !provides) return;
    const buffer = await file.arrayBuffer();
    const openTask = provides.openDocumentBuffer({
      name: file.name,
      buffer,
      documentId: optionsRef.current?.documentId,
      scale: optionsRef.current?.scale,
      rotation: optionsRef.current?.rotation,
      autoActivate: optionsRef.current?.autoActivate,
    });
    openTask.wait(
      (result) => {
        taskRef.current?.resolve(result);
      },
      (error) => {
        taskRef.current?.fail(error);
      },
    );
  };

  return (
    <input
      ref={inputRef}
      type="file"
      accept="application/pdf"
      style={{ display: 'none' }}
      onChange={onChange}
    />
  );
}

// packages/plugin-document-manager/src/svelte/components/FilePicker.svelte
<script lang="ts">
  import { useDocumentManagerCapability, useDocumentManagerPlugin } from '../hooks';
  import type { Task } from '@embedpdf/models';
  import type { PdfErrorReason } from '@embedpdf/models';
  import type {
    OpenDocumentResponse,
    OpenFileDialogOptions,
  } from '@embedpdf/plugin-document-manager';

  const documentManagerPlugin = useDocumentManagerPlugin();
  const documentManagerCapability = useDocumentManagerCapability();

  let inputRef = $state<HTMLInputElement | null>(null);
  let taskRef = $state<Task<OpenDocumentResponse, PdfErrorReason> | null>(null);
  let optionsRef = $state<OpenFileDialogOptions | undefined>(undefined);

  $effect(() => {
    if (!documentManagerPlugin.plugin?.onOpenFileRequest) return;

    const unsubscribe = documentManagerPlugin.plugin.onOpenFileRequest(({ task, options }) => {
      taskRef = task;
      optionsRef = options;
      inputRef?.click();
    });

    return unsubscribe;
  });

  const onChange = async (event: Event) => {
    const target = event.target as HTMLInputElement;
    const file = target.files?.[0];
    if (!file || !documentManagerCapability.provides) return;

    const buffer = await file.arrayBuffer();
    const openTask = documentManagerCapability.provides.openDocumentBuffer({
      name: file.name,
      buffer,
      documentId: optionsRef?.documentId,
      scale: optionsRef?.scale,
      rotation: optionsRef?.rotation,
      autoActivate: optionsRef?.autoActivate,
    });

    openTask.wait(
      (result) => {
        taskRef?.resolve(result);
      },
      (error) => {
        taskRef?.fail(error);
      },
    );
  };
</script>

<input
  bind:this={inputRef}
  type="file"
  accept="application/pdf"
  style:display="none"
  onchange={onChange}
/>
