// cloudpdf/website/src/samples/tools/pin.svelte/PinLayer.svelte
<script lang="ts" module>
  import type { PageRef } from '@embedpdf/svelte/runtime';

  export interface Pin {
    readonly id: number;
    readonly page: PageRef;
    readonly point: { readonly x: number; readonly y: number };
  }
</script>

<!-- The pins on one page, placed in its pixels at the last moment. -->
<script lang="ts">
  import { pageRefsEqual, type PageContextValue } from '@embedpdf/svelte/runtime';

  let { page, pins }: { page: PageContextValue; pins: readonly Pin[] } = $props();
</script>

{#each pins.filter((pin) => pageRefsEqual(pin.page, page.ref)) as pin (pin.id)}
  {@const { x, y } = page.transform.toPixels(pin.point)}
  <span class="pin" style:left="{x}px" style:top="{y}px">{pin.id}</span>
{/each}

// website/src/samples/tools/pin.vue/PinLayer.vue
<script setup lang="ts">
import { computed } from 'vue';
import { pageRefsEqual } from '@embedpdf/vue/runtime';
import type { PageContextValue } from '@embedpdf/vue/runtime';
import type { Pin } from './pins';

// The pins on one page, placed in its pixels at the last moment.
const props = defineProps<{ page: PageContextValue; pins: readonly Pin[] }>();

const placed = computed(() =>
  props.pins
    .filter((pin) => pageRefsEqual(pin.page, props.page.ref))
    .map((pin) => ({ id: pin.id, at: props.page.transform.toPixels(pin.point) })),
);
</script>

<template>
  <span
    v-for="pin in placed"
    :key="pin.id"
    class="pin"
    :style="{ left: `${pin.at.x}px`, top: `${pin.at.y}px` }"
  >
    {{ pin.id }}
  </span>
</template>
