// packages/framework/vue/src/stage/Scrollbar.vue
<!--
  <Scrollbar>: a headless scrollbar for a Stage lens, a view of the lens's
  scroll metrics (the native scroller contract: scrollTop, scrollHeight,
  clientHeight, in screen px). Thumb drag with pointer capture and a kept grab
  point, track paging with press-and-hold repeat that stops at the pointer, a
  minimum thumb length on long documents, and overlay auto-hide. On an unbounded
  stage the range is the union of content and view, so the bar shrinks as you
  pan away; the mapping is frozen during a thumb drag so the thumb never chases
  itself.

  Geometry and behavior live here; looks live in your CSS, against
    [data-embedpdf-scrollbar][data-axis="y"][data-state="visible|hidden"]
    [data-embedpdf-scrollbar][data-dragging]
    [data-embedpdf-scrollbar-thumb]
  `class` and `style` go on the track, `thumb-class` and `thumb-style` on the
  thumb. Unstyled, it is a transparent track pinned to the view's edge with a
  `var(--epdf-scrollbar-thumb, …)` pill.
-->
<script setup lang="ts">
import { computed, onUnmounted, ref, watch } from 'vue';
import type { CSSProperties, StyleValue } from 'vue';
import { createScrollbarPresses, paintDefault, scrollbarLayout } from '@embedpdf/web';
import type { ScrollbarTrack } from '@embedpdf/web';
import { useCapabilityRef } from '../runtime/capabilities';
import { asHost, useScrollMetricsValue } from './composables';
import { useStageToken } from './scope';
import type { StageTokenProp } from './scope';

const props = withDefaults(
  defineProps<{
    axis: 'x' | 'y';
    /** The stage lens to scroll: the nearest `<StageScope>` / `<Stage>`'s, else the main StageToken. */
    token?: StageTokenProp;
    /**
     * Overlay auto-hide: fade this many ms after the view stops moving (drags
     * and hover keep it visible; a hidden bar ignores the pointer, like macOS).
     * `false` keeps it visible. Published as `data-state="visible|hidden"`.
     */
    autoHide?: number | false;
    /** Minimum thumb length in px, so the bar never vanishes on long documents. */
    minThumbSize?: number;
    /**
     * Pressing the track: 'page' steps by 90% of a view toward the pointer,
     * repeats while held, and stops when the thumb reaches the pointer; 'jump'
     * centres the thumb at the pointer and hands off to a drag.
     */
    trackPress?: 'page' | 'jump';
    /** The thumb's class. */
    thumbClass?: string;
    /** The thumb's style, over its defaults. */
    thumbStyle?: StyleValue;
  }>(),
  { autoHide: 1200, minThumbSize: 24, trackPress: 'page' },
);

const token = useStageToken(() => props.token);
const stage = useCapabilityRef(computed(() => asHost(token.value)));
const metrics = useScrollMetricsValue(token);
const vertical = computed(() => props.axis === 'y');
const scrollable = computed(() =>
  vertical.value ? metrics.value.scrollableY : metrics.value.scrollableX,
);

const track = ref<HTMLDivElement | null>(null);
const trackPx = ref(0);
const dragging = ref(false);
const hovered = ref(false);
// The view moved recently.
const active = ref(true);

// The thumb along the track: one formula for drawing, dragging and paging, shared with every framework.
const layout = computed(() =>
  scrollbarLayout(metrics.value, vertical.value, trackPx.value, props.minThumbSize),
);

// ── overlay auto-hide: any metrics change re-arms the fade ─────────────────
const hideAfter = computed(() => (props.autoHide === false ? 0 : props.autoHide));
watch(
  [metrics, hideAfter],
  ([, delay], _previous, onCleanup) => {
    if (!delay) return;
    active.value = true;
    const timer = setTimeout(() => (active.value = false), delay);
    onCleanup(() => clearTimeout(timer));
  },
  { immediate: true },
);
const shown = computed(() => !hideAfter.value || active.value || hovered.value || dragging.value);

// ── track measurement: the px mapping needs real geometry ─────────────────
watch(
  [track, vertical],
  ([element, isVertical], _previous, onCleanup) => {
    if (!element) return;
    const measure = () => {
      trackPx.value = isVertical ? element.clientHeight : element.clientWidth;
    };
    const observer = new ResizeObserver(measure);
    observer.observe(element);
    measure();
    onCleanup(() => observer.disconnect());
  },
  { immediate: true, flush: 'post' },
);

// ── interactions: `@embedpdf/web`'s press handling (thumb drags, track paging
//    and jumps), handed the bar as it is now on every event. ──────────────────
const presses = createScrollbarPresses((value) => (dragging.value = value));
const pressedTrack = (): ScrollbarTrack => ({
  stage: stage.value,
  vertical: vertical.value,
  element: track.value!,
  layout: layout.value,
  // Fresh geometry for paging steps: read from the capability, never a stale render.
  liveLayout: () =>
    scrollbarLayout(
      stage.value.getScrollMetrics(),
      vertical.value,
      trackPx.value,
      props.minThumbSize,
    ),
});

// No repeat timer outlives the bar.
onUnmounted(() => presses.release());

const trackStyle = computed(
  (): CSSProperties => ({
    ...(vertical.value
      ? { position: 'absolute', top: 0, right: 0, bottom: 0, width: '12px' }
      : { position: 'absolute', left: 0, right: 0, bottom: 0, height: '12px' }),
    touchAction: 'none',
    userSelect: 'none',
    opacity: shown.value ? 1 : 0,
    transition: 'opacity 200ms',
    // A hidden overlay bar must not eat the clicks under it.
    pointerEvents: shown.value ? 'auto' : 'none',
  }),
);
const thumbDefaults = computed((): CSSProperties => {
  const { thumbPosition, thumbLength } = layout.value;
  return {
    ...(vertical.value
      ? {
          position: 'absolute',
          left: '2px',
          right: '2px',
          top: `${thumbPosition}px`,
          height: `${thumbLength}px`,
        }
      : {
          position: 'absolute',
          top: '2px',
          bottom: '2px',
          left: `${thumbPosition}px`,
          width: `${thumbLength}px`,
        }),
    borderRadius: '6px',
    background: paintDefault('scrollbar-thumb'),
  };
});
</script>

<template>
  <div
    v-if="scrollable"
    ref="track"
    role="scrollbar"
    :aria-orientation="vertical ? 'vertical' : 'horizontal'"
    :aria-valuemin="0"
    :aria-valuemax="Math.round(layout.maxOffset)"
    :aria-valuenow="Math.round(layout.offset)"
    data-embedpdf-scrollbar=""
    :data-axis="axis"
    :data-state="shown ? 'visible' : 'hidden'"
    :data-dragging="dragging ? '' : undefined"
    :style="trackStyle"
    @pointerdown="presses.pressTrack($event, pressedTrack(), trackPress)"
    @pointermove="presses.move($event, pressedTrack())"
    @pointerup="presses.release()"
    @pointercancel="presses.release()"
    @pointerenter="hovered = true"
    @pointerleave="hovered = false"
  >
    <div
      data-embedpdf-scrollbar-thumb=""
      :class="thumbClass"
      :style="[thumbDefaults, thumbStyle]"
      @pointerdown="presses.pressThumb($event, pressedTrack())"
    />
  </div>
</template>

// packages/framework/angular/stage/src/scrollbar.ts
/**
 * `<epdf-scrollbar>`: a scrollbar for the Stage it's in, that you style yourself. Put it inside
 * `<epdf-stage>`; it reads the Stage's `scrollMetrics()` (the numbers a scrolling element has)
 * and scrolls through its calls.
 *
 * It behaves like a native bar: drag the thumb (the point you grabbed stays under the pointer),
 * press the track to page toward the pointer (repeating while held, stopping at the pointer),
 * a minimum thumb length on long documents, and macOS-style hiding when nothing moves. On an
 * unbounded Stage the metrics already cover the content and the view together, so the bar
 * shrinks as you pan away; the mapping is frozen while the thumb is dragged, so the thumb never
 * chases itself.
 *
 * The element is the track; style it with your own class and these attributes:
 *   [data-embedpdf-scrollbar][data-axis="y"][data-state="visible|hidden"]
 *   [data-embedpdf-scrollbar][data-dragging]
 *   [data-embedpdf-scrollbar-thumb]          (or `thumbClass`)
 * Until you style the thumb, its color is `--epdf-scrollbar-thumb`.
 */
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  DestroyRef,
  effect,
  ElementRef,
  inject,
  input,
  signal,
} from '@angular/core';
import {
  createScrollbarPresses,
  paintDefault,
  scrollbarLayout,
  type ScrollbarTrack,
} from '@embedpdf/web';
import { outsideStageError } from '@embedpdf/angular/runtime';
import { EpdfStage } from './stage';

export type ScrollbarAxis = 'x' | 'y';

@Component({
  selector: 'epdf-scrollbar',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    role: 'scrollbar',
    'data-embedpdf-scrollbar': '',
    style: 'position: absolute; touch-action: none; user-select: none; transition: opacity 200ms',
    '[attr.aria-orientation]': "vertical() ? 'vertical' : 'horizontal'",
    '[attr.aria-valuemin]': '0',
    '[attr.aria-valuemax]': 'round(layout().maxOffset)',
    '[attr.aria-valuenow]': 'round(layout().offset)',
    '[attr.data-axis]': 'axis()',
    '[attr.data-state]': "shown() ? 'visible' : 'hidden'",
    '[attr.data-dragging]': "dragging() ? '' : null",
    // Pinned to the right (y) or bottom (x) edge of the Stage; nothing to scroll, no bar.
    '[style.display]': "scrollable() ? 'block' : 'none'",
    '[style.top.px]': 'vertical() ? 0 : null',
    '[style.left.px]': 'vertical() ? null : 0',
    '[style.right.px]': '0',
    '[style.bottom.px]': '0',
    '[style.width.px]': 'vertical() ? 12 : null',
    '[style.height.px]': 'vertical() ? null : 12',
    '[style.opacity]': 'shown() ? 1 : 0',
    // A hidden bar must not take the clicks meant for the pages under it.
    '[style.pointer-events]': "shown() ? 'auto' : 'none'",
    '(pointerdown)': 'onTrackDown($event)',
    '(pointermove)': 'onMove($event)',
    '(pointerup)': 'endDrag()',
    '(pointercancel)': 'endDrag()',
    '(pointerenter)': 'hovered.set(true)',
    '(pointerleave)': 'hovered.set(false)',
  },
  template: `
    <div
      data-embedpdf-scrollbar-thumb=""
      [class]="thumbClass()"
      style="position: absolute; border-radius: 6px"
      [style.background]="thumbColor"
      [style.left.px]="vertical() ? 2 : layout().thumbPosition"
      [style.right.px]="vertical() ? 2 : null"
      [style.top.px]="vertical() ? layout().thumbPosition : 2"
      [style.bottom.px]="vertical() ? null : 2"
      [style.width.px]="vertical() ? null : layout().thumbLength"
      [style.height.px]="vertical() ? layout().thumbLength : null"
      (pointerdown)="onThumbDown($event)"
    ></div>
  `,
})
export class EpdfScrollbar {
  /** `'y'` for a vertical bar, `'x'` for a horizontal one. */
  readonly axis = input.required<ScrollbarAxis>();
  /**
   * Hide this many milliseconds after the view stops moving (hover and dragging keep it shown;
   * a hidden bar ignores the pointer, like macOS), or `false` to always show it.
   */
  readonly autoHide = input<number | false, number | false | string>(1200, {
    transform: (value) => (value === false || value === 'false' ? false : Number(value)),
  });
  /** The shortest thumb, in pixels, so it never vanishes on a long document. */
  readonly minThumbSize = input(24);
  /**
   * Pressing the track: `'page'` steps 90% of a view toward the pointer and repeats while held;
   * `'jump'` puts the thumb under the pointer and goes on as a drag.
   */
  readonly trackPress = input<'page' | 'jump'>('page');
  /** The thumb's class. */
  readonly thumbClass = input<string | null>(null);

  private readonly stage: EpdfStage;
  private readonly element = inject<ElementRef<HTMLElement>>(ElementRef).nativeElement;
  private readonly trackPx = signal(0);
  protected readonly dragging = signal(false);
  protected readonly hovered = signal(false);
  /** The view moved a moment ago. */
  private readonly active = signal(true);

  protected readonly vertical = computed(() => this.axis() === 'y');
  protected readonly scrollable = computed(() => {
    const metrics = this.stage.scrollMetrics();
    return this.vertical() ? metrics.scrollableY : metrics.scrollableX;
  });
  /** The thumb along the track: one formula for drawing, dragging and paging, in every framework. */
  protected readonly layout = computed(() =>
    scrollbarLayout(
      this.stage.scrollMetrics(),
      this.vertical(),
      this.trackPx(),
      this.minThumbSize(),
    ),
  );
  protected readonly shown = computed(
    () =>
      this.autoHide() === false ||
      this.autoHide() === 0 ||
      this.active() ||
      this.hovered() ||
      this.dragging(),
  );
  protected readonly thumbColor = paintDefault('scrollbar-thumb');
  protected readonly round = Math.round;

  /** Thumb drags, track paging and jumps: `@embedpdf/web`'s, shared by every framework. */
  private readonly presses = createScrollbarPresses((dragging) => this.dragging.set(dragging));

  constructor() {
    const stage = inject(EpdfStage, { optional: true });
    if (!stage) throw outsideStageError('<epdf-scrollbar>');
    this.stage = stage;

    // Any move of the view shows the bar again and starts the countdown to hiding it.
    effect((onCleanup) => {
      this.stage.scrollMetrics();
      const hideAfter = this.autoHide();
      if (hideAfter === false || hideAfter === 0) return;
      this.active.set(true);
      const timer = setTimeout(() => this.active.set(false), hideAfter);
      onCleanup(() => clearTimeout(timer));
    });

    // The track's length, which the thumb maps onto; again whenever the bar appears or resizes.
    effect((onCleanup) => {
      const vertical = this.vertical();
      if (!this.scrollable() || typeof ResizeObserver === 'undefined') return;
      const measure = () =>
        this.trackPx.set(vertical ? this.element.clientHeight : this.element.clientWidth);
      const observer = new ResizeObserver(measure);
      observer.observe(this.element);
      measure();
      onCleanup(() => observer.disconnect());
    });

    inject(DestroyRef).onDestroy(() => this.endDrag());
  }

  /** The bar as it is now, for `@embedpdf/web`'s press handling. */
  private track(): ScrollbarTrack {
    const vertical = this.vertical();
    return {
      stage: this.stage,
      vertical,
      element: this.element,
      layout: this.layout(),
      // Fresh geometry for paging steps, from the metrics as they are now.
      liveLayout: () =>
        scrollbarLayout(this.stage.scrollMetrics(), vertical, this.trackPx(), this.minThumbSize()),
    };
  }

  protected onThumbDown(event: PointerEvent): void {
    this.presses.pressThumb(event, this.track());
  }

  protected onTrackDown(event: PointerEvent): void {
    this.presses.pressTrack(event, this.track(), this.trackPress());
  }

  /** Pointer capture sends the moves here, for thumb drags, jump drags and paging alike. */
  protected onMove(event: PointerEvent): void {
    this.presses.move(event, this.track());
  }

  protected endDrag(): void {
    this.presses.release();
  }
}
