// packages/plugin-annotation/src/shared/components/annotations/stamp.tsx
import { MouseEvent, TouchEvent } from '@framework';
import { PdfStampAnnoObject } from '@embedpdf/models';
import { TrackedAnnotation } from '@embedpdf/plugin-annotation';
import { RenderAnnotation } from '../render-annotation';

interface StampProps {
  isSelected: boolean;
  annotation: TrackedAnnotation<PdfStampAnnoObject>;
  documentId: string;
  pageIndex: number;
  scale: number;
  onClick: (e: MouseEvent<HTMLDivElement> | TouchEvent<HTMLDivElement>) => void;
}

export function Stamp({
  isSelected,
  annotation,
  documentId,
  pageIndex,
  scale,
  onClick,
}: StampProps) {
  return (
    <div
      style={{
        position: 'absolute',
        width: '100%',
        height: '100%',
        zIndex: 2,
        pointerEvents: isSelected ? 'none' : 'auto',
        cursor: 'pointer',
      }}
      onPointerDown={onClick}
      onTouchStart={onClick}
    >
      <RenderAnnotation
        documentId={documentId}
        pageIndex={pageIndex}
        annotation={{ ...annotation.object, id: annotation.object.id }}
        scaleFactor={scale}
      />
    </div>
  );
}

// packages/plugin-annotation/src/svelte/components/annotations/Stamp.svelte
<script lang="ts">
  import type { PdfStampAnnoObject } from '@embedpdf/models';
  import type { TrackedAnnotation } from '@embedpdf/plugin-annotation';
  import RenderAnnotation from '../RenderAnnotation.svelte';

  interface StampProps {
    documentId: string;
    isSelected: boolean;
    annotation: TrackedAnnotation<PdfStampAnnoObject>;
    pageIndex: number;
    scale: number;
    onClick: (e: MouseEvent | TouchEvent) => void;
  }

  let { documentId, isSelected, annotation, pageIndex, scale, onClick }: StampProps = $props();

  let annotationProp = $derived({ ...annotation.object, id: annotation.object.id });
</script>

<div
  style="position: absolute; width: 100%; height: 100%; z-index: 2;"
  style:pointer-events={isSelected ? 'none' : 'auto'}
  style:cursor="pointer"
  onpointerdown={onClick}
  ontouchstart={onClick}
>
  <RenderAnnotation {documentId} {pageIndex} annotation={annotationProp} scaleFactor={scale} />
</div>
