// packages/plugin-zoom/src/vue/components/zoom-gesture-wrapper.vue
<template>
  <div
    ref="elementRef"
    :style="{
      display: 'block',
      width: 'fit-content',
      marginLeft: 'auto',
      marginRight: 'auto',
      overflow: 'visible',
      boxSizing: 'border-box',
    }"
    v-bind="$attrs"
  >
    <slot />
  </div>
</template>

<script setup lang="ts">
import { toRef } from 'vue';
import { useZoomGesture } from '../hooks/use-zoom-gesture';

interface Props {
  documentId: string;
  /** Enable pinch-to-zoom gesture (default: true) */
  enablePinch?: boolean;
  /** Enable wheel zoom with ctrl/cmd key (default: true) */
  enableWheel?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  enablePinch: true,
  enableWheel: true,
});

const { elementRef } = useZoomGesture(() => props.documentId, {
  enablePinch: toRef(() => props.enablePinch),
  enableWheel: toRef(() => props.enableWheel),
});
</script>

// packages/plugin-zoom/src/shared/components/zoom-gesture-wrapper.tsx
import { ReactNode, HTMLAttributes, CSSProperties, useMemo } from '@framework';
import { useZoomGesture, ZoomGestureOptions } from '../hooks';

type ZoomGestureWrapperProps = Omit<HTMLAttributes<HTMLDivElement>, 'style'> & {
  children: ReactNode;
  documentId: string;
  style?: CSSProperties;
  /** Enable pinch-to-zoom gesture (default: true) */
  enablePinch?: boolean;
  /** Enable wheel zoom with ctrl/cmd key (default: true) */
  enableWheel?: boolean;
};

export function ZoomGestureWrapper({
  children,
  documentId,
  style,
  enablePinch = true,
  enableWheel = true,
  ...props
}: ZoomGestureWrapperProps) {
  const options = useMemo<ZoomGestureOptions>(
    () => ({ enablePinch, enableWheel }),
    [enablePinch, enableWheel],
  );
  const { elementRef } = useZoomGesture(documentId, options);

  return (
    <div
      ref={elementRef}
      {...props}
      style={{
        ...style,
        display: 'block',
        width: 'fit-content',
        marginLeft: 'auto',
        marginRight: 'auto',
        overflow: 'visible',
        boxSizing: 'border-box',
      }}
    >
      {children}
    </div>
  );
}
