// cloudpdf/website/src/samples/toolbar/basic.svelte.svelte
<script lang="ts" module>
  import { DocumentGate, Viewer, type OpenInput } from '@embedpdf/svelte/runtime';
  import { Stage, stagePlugin } from '@embedpdf/svelte/stage';
  import { RenderLayer, renderPlugin } from '@embedpdf/svelte/render';
  import { interactionPlugin } from '@embedpdf/svelte/interaction';
  import { SelectionLayer, selectionPlugin } from '@embedpdf/svelte/selection';
  import { AnnotationLayer, annotationPlugin } from '@embedpdf/svelte/annotation';
  import { commandsPlugin, standardCommands } from '@embedpdf/svelte/commands';
  import { Toolbar, group, item, type BarSchema } from '@embedpdf/svelte/toolbar';
  import { cloudEngine } from '@cloudpdf/engine';

  import './basic.css';

  const engine = cloudEngine({ baseUrl: 'https://engine.cloudpdf.com' });
  const plugins = [
    stagePlugin(),
    renderPlugin(),
    interactionPlugin(),
    selectionPlugin(),
    annotationPlugin(),
    commandsPlugin({ commands: standardCommands }),
  ];

  const ebook: OpenInput = { kind: 'share', shareToken: 'shr_WGj1goAtlNN_fQ5OswPrbJQM' };

  // Your icons, by the names the standard commands give them.
  const ICONS: Record<string, string> = {
    'previous-page': '‹',
    'next-page': '›',
    'zoom-out': '−',
    'zoom-in': '+',
    'fit-width': '↔',
    pointer: '↖',
    pan: '✥',
    highlight: '▍',
    underline: 'U̲',
    ink: '〰',
    download: '↓',
    print: '⎙',
  };

  const bar: BarSchema = {
    id: 'main',
    sections: {
      start: [group('pages', ['page:previous', 'page:next'])],
      center: [
        group('zoom', [
          'zoom:out',
          item('zoom:in', { variants: ['icon+label', 'icon'] }),
          item('zoom:fit-width', { variants: ['icon+label', 'icon'], importance: 2 }),
        ]),
      ],
      end: [
        group('tools', ['tool:pointer', 'tool:pan', 'tool:highlight', 'tool:underline', 'tool:ink'], {
          collapse: 'menu',
        }),
        group('document', [item('document:download', { importance: 5 }), 'document:print']),
      ],
    },
  };
</script>

<script lang="ts">
  // Narrow the toolbar to watch it make room: labels go first, then the tools fold, then "More".
  let width = $state(100);
</script>

<Viewer {engine} {plugins} initialDocuments={[{ source: ebook }]}>
  <DocumentGate>
    {#snippet fallback()}
      <p class="loading">Loading…</p>
    {/snippet}
    <label class="width">
      Toolbar width
      <input type="range" min={30} max={100} bind:value={width} />
      <output>{width}%</output>
    </label>
    <div class="frame" style:width="{width}%">
      <Toolbar {bar} class="toolbar">
        {#snippet command(cmd, variant, run)}
          <button
            type="button"
            class="button"
            title={cmd.label}
            aria-label={cmd.label}
            disabled={!cmd.enabled}
            aria-pressed={cmd.active}
            onclick={run}
          >
            <span class="icon" aria-hidden="true">
              {ICONS[cmd.icon ?? ''] ?? cmd.label.charAt(0)}
            </span>
            {#if variant === 'icon+label'}<span>{cmd.label}</span>{/if}
          </button>
        {/snippet}
      </Toolbar>
    </div>
    <Stage class="stage">
      <RenderLayer annotations={false} />
      <SelectionLayer />
      <AnnotationLayer />
    </Stage>
  </DocumentGate>
</Viewer>

// cloudpdf/website/src/samples/redaction/basic.react.tsx
import { useEffect, useRef } from 'react';
import { Viewer, DocumentGate } from '@embedpdf/react/runtime';
import type { OpenInput } from '@embedpdf/react/runtime';
import { Stage, stagePlugin, useStage } from '@embedpdf/react/stage';
import { RenderLayer, renderPlugin } from '@embedpdf/react/render';
import {
  interactionPlugin,
  useInteraction,
  useInteractionState,
} from '@embedpdf/react/interaction';
import { SelectionLayer, selectionPlugin } from '@embedpdf/react/selection';
import { AnnotationLayer, annotationPlugin, useAnnotationState } from '@embedpdf/react/annotation';
import { redactionPlugin, useRedaction, useRedactionState } from '@embedpdf/react/redaction';
import { cloudEngine } from '@cloudpdf/engine';

import './basic.css';

const engine = cloudEngine({ baseUrl: 'https://engine.cloudpdf.com' });
// The selection plugin lets the redact tool mark the text you select.
const plugins = [
  stagePlugin(),
  renderPlugin(),
  interactionPlugin(),
  selectionPlugin(),
  annotationPlugin(),
  redactionPlugin(),
];

const ebook: OpenInput = { kind: 'share', shareToken: 'shr_WGj1goAtlNN_fQ5OswPrbJQM' };

// The author's name on the cover, in page coordinates.
const AUTHOR = { x: 100, y: 508, width: 172, height: 50 };

function RedactBar() {
  const interaction = useInteraction();
  const { activeToolId } = useInteractionState();
  const stage = useStage();
  const redaction = useRedaction();
  const { pendingCount, applying } = useRedactionState();
  const ready = useAnnotationState((state) => state.status === 'ready');
  const started = useRef(false);

  // On load: the author's name marked, and the redact tool on.
  useEffect(() => {
    if (!ready || started.current) return;
    started.current = true;
    void redaction.markArea(0, AUTHOR).then(() => stage.reveal(0, { rect: AUTHOR }));
    interaction.activateTool('redact');
  }, [redaction, interaction, stage, ready]);

  const marking = activeToolId === 'redact';

  return (
    <div className="toolbar">
      <button
        type="button"
        className="button"
        aria-pressed={marking}
        onClick={() => interaction.activateTool(marking ? 'pointer' : 'redact')}
      >
        Mark for redaction
      </button>
      <button
        type="button"
        className="button danger"
        disabled={!pendingCount || applying}
        onClick={() => void redaction.applyAll()}
      >
        Redact {pendingCount} {pendingCount === 1 ? 'mark' : 'marks'}
      </button>
      <span className="spacer" />
      <output className="readout">
        {marking ? 'Select text, or drag over an area' : 'Click a mark to move it'}
      </output>
    </div>
  );
}

export default function App() {
  return (
    <Viewer engine={engine} plugins={plugins} initialDocuments={[{ source: ebook }]}>
      <DocumentGate fallback={<p className="loading">Loading…</p>}>
        <RedactBar />
        <Stage className="stage">
          {() => (
            <>
              <RenderLayer annotations={false} />
              <SelectionLayer />
              <AnnotationLayer />
            </>
          )}
        </Stage>
      </DocumentGate>
    </Viewer>
  );
}
