// docs/content/snippets/concepts/branded-text-box.svelte.svelte
<script lang="ts">
  import { useRichTextEditor, type AnnotationRendererProps } from '@embedpdf/svelte/annotation';

  let { annotation, box, page }: AnnotationRendererProps = $props();

  const editor = useRichTextEditor(
    () => annotation,
    () => page,
  );
  const rect = $derived(page.transform.pageToViewRect(box));
</script>

<div
  {@attach editor.attach}
  class={['text-box', editor.editing && 'editing']}
  style="position: absolute; left: {rect.x}px; top: {rect.y}px; width: {rect.width}px; height: {rect.height}px; {editor.style}"
></div>

// website/src/samples/snippets/concepts/branded-text-box.react.tsx
import { useRichTextEditor, type AnnotationRendererProps } from '@embedpdf/react/annotation';

export function BrandedTextBox({ annotation, box, page }: AnnotationRendererProps) {
  const editor = useRichTextEditor(annotation, page);
  const { x, y, width, height } = page.transform.pageToViewRect(box);

  return (
    <div
      ref={editor.ref}
      className={editor.editing ? 'text-box editing' : 'text-box'}
      style={{ position: 'absolute', left: x, top: y, width, height, ...editor.style }}
    />
  );
}
