// docs/content/samples/how-it-works/layers.vue/OnLoad.vue
<script setup lang="ts">
import { computed, watch } from 'vue';
import { usePageList } from '@embedpdf/vue/runtime';
import { useSearch } from '@embedpdf/vue/search';
import { useSelection } from '@embedpdf/vue/selection';

// Something on every layer on load: the matches of a search, and the title selected.
const search = useSearch();
const selection = useSelection();
const pages = usePageList();
const cover = computed(() => pages.value[0]?.ref);

void search.search({ text: 'PDF' });
watch(
  cover,
  (page) => {
    if (page) selection.select({ page, start: 10, count: 52 });
  },
  { immediate: true },
);
</script>

<template></template>

// docs/content/samples/how-it-works/layers.svelte/OnLoad.svelte
<!-- Something on every layer on load: the matches of a search, and the title selected. -->
<script lang="ts">
  import { usePageList } from '@embedpdf/svelte/runtime';
  import { useSearch } from '@embedpdf/svelte/search';
  import { useSelection } from '@embedpdf/svelte/selection';

  const search = useSearch();
  const selection = useSelection();
  const pages = usePageList();
  const cover = $derived(pages.current[0]?.ref);

  $effect(() => {
    void search.search({ text: 'PDF' });
  });
  $effect(() => {
    if (cover) selection.select({ page: cover, start: 10, count: 52 });
  });
</script>
