// docs/content/samples/documents/states.svelte/PasswordForm.svelte
<script lang="ts">
  import { useDocuments, type DocumentInfo } from '@embedpdf/svelte/runtime';

  let { document }: { document: DocumentInfo } = $props();

  const documents = useDocuments();
  let password = $state('');
  let wrong = $state(false);

  async function unlock() {
    try {
      await documents.unlock(document.id, { password });
    } catch {
      wrong = true; // it stays locked; ask again
    }
  }
</script>

<div class="panel">
  <h3>{document.name} needs a password</h3>
  <!-- A password given before (when the file was opened) was wrong too. -->
  {#if wrong || document.passwordProvided}
    <p>That password isn’t right. Try again.</p>
  {/if}
  <div class="actions">
    <input class="field" type="password" aria-label="Password" bind:value={password} />
    <button type="button" class="button" onclick={unlock}>Unlock</button>
  </div>
</div>

// docs/content/samples/documents/states.vue/PasswordForm.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useDocuments } from '@embedpdf/vue/runtime';
import type { DocumentInfo } from '@embedpdf/vue/runtime';

const props = defineProps<{ document: DocumentInfo }>();

const documents = useDocuments();
const password = ref('');
const wrong = ref(props.document.passwordProvided ?? false);

async function unlock() {
  try {
    await documents.unlock(props.document.id, { password: password.value });
  } catch {
    wrong.value = true; // it stays locked; ask again
  }
}
</script>

<template>
  <div class="panel">
    <h3>{{ document.name }} needs a password</h3>
    <p v-if="wrong">That password isn’t right. Try again.</p>
    <div class="actions">
      <input v-model="password" class="field" type="password" aria-label="Password" />
      <button type="button" class="button" @click="unlock">Unlock</button>
    </div>
  </div>
</template>
