// packages/plugin-annotation/src/vue/components/render-annotation.vue
<template>
  <img
    v-if="imageUrl"
    :src="imageUrl"
    @load="handleImageLoad"
    :style="{
      width: '100%',
      height: '100%',
      display: 'block',
      ...style,
    }"
  />
</template>

<script setup lang="ts">
import { ref, watch, onUnmounted, CSSProperties, computed } from 'vue';
import { ignore, PdfAnnotationObject, PdfErrorCode } from '@embedpdf/models';
import { useAnnotationCapability } from '../hooks';
import { deepToRaw } from '@embedpdf/utils/vue';

const props = withDefaults(
  defineProps<{
    documentId: string;
    pageIndex: number;
    annotation: PdfAnnotationObject;
    scaleFactor?: number;
    style?: CSSProperties;
  }>(),
  {
    scaleFactor: 1,
  },
);

const { provides: annotationProvides } = useAnnotationCapability();
const imageUrl = ref<string | null>(null);
const urlRef = ref<string | null>(null);
const currentTask = ref<any>(null);

// Extract primitive values to avoid unnecessary re-renders
const annotationId = computed(() => props.annotation.id);
const rectWidth = computed(() => props.annotation.rect.size.width);
const rectHeight = computed(() => props.annotation.rect.size.height);

watch(
  () => [
    props.pageIndex,
    props.scaleFactor,
    props.documentId,
    annotationId.value,
    rectWidth.value,
    rectHeight.value,
    annotationProvides.value,
  ],
  (_, __, onCleanup) => {
    if (annotationProvides.value) {
      if (urlRef.value) {
        URL.revokeObjectURL(urlRef.value);
        urlRef.value = null;
      }

      const task = annotationProvides.value.forDocument(props.documentId).renderAnnotation({
        pageIndex: props.pageIndex,
        annotation: deepToRaw(props.annotation),
        options: {
          scaleFactor: props.scaleFactor,
          dpr: window.devicePixelRatio,
        },
      });

      currentTask.value = task;

      task.wait((blob) => {
        const url = URL.createObjectURL(blob);
        imageUrl.value = url;
        urlRef.value = url;
      }, ignore);

      onCleanup(() => {
        if (urlRef.value) {
          URL.revokeObjectURL(urlRef.value);
          urlRef.value = null;
        } else {
          task.abort({
            code: PdfErrorCode.Cancelled,
            message: 'canceled render task',
          });
        }
      });
    }
  },
  { immediate: true },
);

onUnmounted(() => {
  if (urlRef.value) {
    URL.revokeObjectURL(urlRef.value);
    urlRef.value = null;
  }
  if (currentTask.value) {
    currentTask.value.abort({
      code: PdfErrorCode.Cancelled,
      message: 'canceled render task on unmount',
    });
  }
});

const handleImageLoad = () => {
  if (urlRef.value) {
    URL.revokeObjectURL(urlRef.value);
    urlRef.value = null;
  }
};
</script>

// packages/plugin-annotation/src/shared/components/render-annotation.tsx
import { Fragment, HTMLAttributes, CSSProperties, useEffect, useRef, useState } from '@framework';
import { AppearanceMode, ignore, PdfAnnotationObject, PdfErrorCode } from '@embedpdf/models';

import { useAnnotationCapability } from '../hooks/use-annotation';

type RenderAnnotationProps = Omit<HTMLAttributes<HTMLImageElement>, 'style'> & {
  documentId: string;
  pageIndex: number;
  annotation: PdfAnnotationObject;
  scaleFactor?: number;
  dpr?: number;
  style?: CSSProperties;
};

export function RenderAnnotation({
  documentId,
  pageIndex,
  annotation,
  scaleFactor = 1,
  style,
  ...props
}: RenderAnnotationProps) {
  const { provides: annotationProvides } = useAnnotationCapability();
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const urlRef = useRef<string | null>(null);

  const { width, height } = annotation.rect.size;

  useEffect(() => {
    if (annotationProvides) {
      const task = annotationProvides.forDocument(documentId).renderAnnotation({
        pageIndex,
        annotation,
        options: {
          scaleFactor,
          dpr: window.devicePixelRatio,
        },
      });
      task.wait((blob) => {
        const url = URL.createObjectURL(blob);
        setImageUrl(url);
        urlRef.current = url;
      }, ignore);

      return () => {
        if (urlRef.current) {
          URL.revokeObjectURL(urlRef.current);
          urlRef.current = null;
        } else {
          task.abort({
            code: PdfErrorCode.Cancelled,
            message: 'canceled render task',
          });
        }
      };
    }
  }, [pageIndex, scaleFactor, annotationProvides, documentId, annotation.id, width, height]);

  const handleImageLoad = () => {
    if (urlRef.current) {
      URL.revokeObjectURL(urlRef.current);
      urlRef.current = null;
    }
  };

  return (
    <Fragment>
      {imageUrl && (
        <img
          src={imageUrl}
          onLoad={handleImageLoad}
          {...props}
          style={{
            width: '100%',
            height: '100%',
            display: 'block',
            ...(style || {}),
          }}
        />
      )}
    </Fragment>
  );
}
