// packages/plugin-i18n/src/svelte/components/Translate.svelte
<script lang="ts">
  import { useTranslation } from '../hooks/use-i18n.svelte';

  interface TranslateProps {
    k: string;
    params?: Record<string, string | number>;
    fallback?: string;
    documentId?: string;
  }

  let { k, params, fallback, documentId }: TranslateProps = $props();

  const translation = useTranslation(
    () => k,
    () => ({ params, fallback }),
    () => documentId,
  );
</script>

{translation.current}

// packages/plugin-i18n/src/vue/components/translate.vue
<script setup lang="ts">
import { useTranslation } from '../hooks/use-i18n';

interface TranslateProps {
  k: string;
  params?: Record<string, string | number>;
  fallback?: string;
  documentId?: string;
}

const props = defineProps<TranslateProps>();
const translation = useTranslation(
  props.k,
  { params: props.params, fallback: props.fallback },
  () => props.documentId,
);
</script>

<template>
  <span>{{ translation }}</span>
</template>
