// packages/plugin-document-manager/src/svelte/components/FilePicker.svelte
<script lang="ts">
  import { useDocumentManagerCapability, useDocumentManagerPlugin } from '../hooks';
  import type { Task } from '@embedpdf/models';
  import type { PdfErrorReason } from '@embedpdf/models';
  import type { OpenDocumentResponse } from '@embedpdf/plugin-document-manager';

  const { plugin } = useDocumentManagerPlugin();
  const { provides } = useDocumentManagerCapability();

  let inputRef = $state<HTMLInputElement | null>(null);
  let taskRef = $state<Task<OpenDocumentResponse, PdfErrorReason> | null>(null);

  $effect(() => {
    if (!plugin?.onOpenFileRequest) return;

    const unsubscribe = plugin.onOpenFileRequest((task) => {
      taskRef = task;
      inputRef?.click();
    });

    return unsubscribe;
  });

  const onChange = async (event: Event) => {
    const target = event.target as HTMLInputElement;
    const file = target.files?.[0];
    if (!file || !provides) return;

    const buffer = await file.arrayBuffer();
    const openTask = provides.openDocumentBuffer({
      name: file.name,
      buffer,
    });

    openTask.wait(
      (result) => {
        taskRef?.resolve(result);
      },
      (error) => {
        taskRef?.fail(error);
      },
    );
  };
</script>

<input
  bind:this={inputRef}
  type="file"
  accept="application/pdf"
  style:display="none"
  onchange={onChange}
/>

// packages/plugin-document-manager/src/vue/components/file-picker.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import { useDocumentManagerCapability, useDocumentManagerPlugin } from '../hooks';
import type { Task } from '@embedpdf/models';
import type { PdfErrorReason } from '@embedpdf/models';
import type { OpenDocumentResponse } from '@embedpdf/plugin-document-manager';

const { plugin } = useDocumentManagerPlugin();
const { provides } = useDocumentManagerCapability();
const inputRef = ref<HTMLInputElement | null>(null);
const taskRef = ref<Task<OpenDocumentResponse, PdfErrorReason> | null>(null);

watch(
  plugin,
  (pluginValue, _, onCleanup) => {
    if (!pluginValue?.onOpenFileRequest) return;

    const unsubscribe = pluginValue.onOpenFileRequest((task) => {
      taskRef.value = task;
      inputRef.value?.click();
    });

    onCleanup(unsubscribe);
  },
  { immediate: true },
);

const onChange = async (event: Event) => {
  const target = event.target as HTMLInputElement;
  const file = target.files?.[0];
  const cap = provides.value;
  if (!file || !cap) return;

  const buffer = await file.arrayBuffer();
  const openTask = cap.openDocumentBuffer({
    name: file.name,
    buffer,
  });

  openTask.wait(
    (result) => {
      taskRef.value?.resolve(result);
    },
    (error) => {
      taskRef.value?.fail(error);
    },
  );
};
</script>

<template>
  <input
    ref="inputRef"
    type="file"
    accept="application/pdf"
    style="display: none"
    @change="onChange"
  />
</template>
