// packages/plugin-tiling/src/shared/components/tiling-layer.tsx
import { Tile } from '@embedpdf/plugin-tiling';
import { useEffect, useState, HTMLAttributes, CSSProperties, useMemo } from '@framework';

import { TileImg } from './tile-img';
import { useTilingCapability } from '../hooks/use-tiling';
import { useDocumentState } from '@embedpdf/core/@framework';

type TilingLayoutProps = Omit<HTMLAttributes<HTMLDivElement>, 'style'> & {
  documentId: string;
  pageIndex: number;
  scale?: number;
  style?: CSSProperties;
};

export function TilingLayer({
  documentId,
  pageIndex,
  scale: scaleOverride,
  style,
  ...props
}: TilingLayoutProps) {
  const { provides: tilingProvides } = useTilingCapability();
  const documentState = useDocumentState(documentId);
  const [tiles, setTiles] = useState<Tile[]>([]);

  useEffect(() => {
    if (tilingProvides) {
      return tilingProvides.onTileRendering((event) => {
        if (event.documentId === documentId) {
          setTiles(event.tiles[pageIndex] ?? []);
        }
      });
    }
  }, [tilingProvides, documentId, pageIndex]);

  const actualScale = useMemo(() => {
    if (scaleOverride !== undefined) return scaleOverride;
    return documentState?.scale ?? 1;
  }, [scaleOverride, documentState?.scale]);

  return (
    <div
      style={{
        ...style,
      }}
      {...props}
    >
      {tiles?.map((tile) => (
        <TileImg
          key={tile.id}
          documentId={documentId}
          pageIndex={pageIndex}
          tile={tile}
          dpr={window.devicePixelRatio}
          scale={actualScale}
        />
      ))}
    </div>
  );
}

// packages/plugin-tiling/src/svelte/components/TilingLayer.svelte
<script lang="ts">
  import type { Tile } from '@embedpdf/plugin-tiling';
  import { useDocumentState } from '@embedpdf/core/svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import TileImg from './TileImg.svelte';
  import { useTilingCapability } from '../hooks';

  type TilingLayoutProps = HTMLAttributes<HTMLDivElement> & {
    documentId: string;
    pageIndex: number;
    scale?: number;
    class?: string;
  };

  let {
    documentId,
    pageIndex,
    scale: scaleOverride,
    class: propsClass,
    ...restProps
  }: TilingLayoutProps = $props();

  const tilingCapability = useTilingCapability();
  const documentState = useDocumentState(documentId);

  let tiles = $state<Tile[]>([]);

  const actualScale = $derived(
    scaleOverride !== undefined ? scaleOverride : (documentState.current?.scale ?? 1),
  );

  $effect(() => {
    if (!tilingCapability.provides) return;
    return tilingCapability.provides.onTileRendering((event) => {
      if (event.documentId === documentId) {
        tiles = event.tiles[pageIndex] ?? [];
      }
    });
  });
</script>

<div class={propsClass} {...restProps}>
  {#each tiles as tile (tile.id)}
    <TileImg {documentId} {pageIndex} {tile} dpr={window.devicePixelRatio} scale={actualScale} />
  {/each}
</div>
