// docs/content/samples/documents/panes.vue/Panes.vue
<script setup lang="ts">
import { watch } from 'vue';
import { useViewManager, useViewManagerState } from '@embedpdf/vue/view-manager';
import Pane from './Pane.vue';

const views = useViewManager();
const { panes } = useViewManagerState();

// On load, both documents land in the first pane: put the second one beside it, once.
let splitOnLoad = true;
watch(
  panes,
  (current) => {
    if (splitOnLoad && current.length === 1 && current[0].documentIds.length === 2) {
      splitOnLoad = false;
      views.splitPane(current[0].documentIds[1]);
    }
  },
  { immediate: true },
);
</script>

<template>
  <div class="panes">
    <Pane v-for="pane in panes" :key="pane.id" :pane="pane" :can-remove="panes.length > 1" />
  </div>
</template>

// website/src/samples/documents/panes.svelte/Panes.svelte
<script lang="ts">
  import { useViewManager, useViewManagerState } from '@embedpdf/svelte/view-manager';
  import Pane from './Pane.svelte';

  const views = useViewManager();
  const layout = useViewManagerState();

  // On load, both documents land in the first pane: put the second one beside it, once.
  let splitOnLoad = true;
  $effect(() => {
    const panes = layout.panes;
    if (splitOnLoad && panes.length === 1 && panes[0].documentIds.length === 2) {
      splitOnLoad = false;
      views.splitPane(panes[0].documentIds[1]);
    }
  });
</script>

<div class="panes">
  {#each layout.panes as pane (pane.id)}
    <Pane {pane} canRemove={layout.panes.length > 1} />
  {/each}
</div>
