// packages/plugin-tiling/src/vue/components/tiling-layer.vue
<script setup lang="ts">
import { ref, watch, computed } from 'vue';
import { useDocumentState } from '@embedpdf/core/vue';
import type { Tile } from '@embedpdf/plugin-tiling';

import { useTilingCapability } from '../hooks';
import TileImg from './tile-img.vue';

interface TilingLayerProps {
  documentId: string;
  pageIndex: number;
  scale?: number;
}

const props = defineProps<TilingLayerProps>();

const { provides: tilingProvides } = useTilingCapability();
const documentState = useDocumentState(() => props.documentId);
const tiles = ref<Tile[]>([]);

const actualScale = computed(() => {
  if (props.scale !== undefined) return props.scale;
  return documentState.value?.scale ?? 1;
});

watch(
  [tilingProvides, () => props.documentId, () => props.pageIndex],
  ([provides, docId, pageIdx], _, onCleanup) => {
    if (!provides) {
      tiles.value = [];
      return;
    }

    const unsubscribe = provides.onTileRendering((event) => {
      if (event.documentId === docId) {
        tiles.value = event.tiles[pageIdx] ?? [];
      }
    });

    onCleanup(unsubscribe);
  },
  { immediate: true },
);
</script>

<template>
  <div v-bind="$attrs">
    <TileImg
      v-for="tile in tiles"
      :key="tile.id"
      :documentId="documentId"
      :pageIndex="pageIndex"
      :tile="tile"
      :scale="actualScale"
    />
  </div>
</template>

// packages/plugin-tiling/src/shared/components/tiling-layer.tsx
import { Tile } from '@embedpdf/plugin-tiling';
import { useEffect, useState, HTMLAttributes, CSSProperties, useMemo } from '@framework';

import { TileImg } from './tile-img';
import { useTilingCapability } from '../hooks/use-tiling';
import { useDocumentState } from '@embedpdf/core/@framework';

type TilingLayoutProps = Omit<HTMLAttributes<HTMLDivElement>, 'style'> & {
  documentId: string;
  pageIndex: number;
  scale?: number;
  style?: CSSProperties;
};

export function TilingLayer({
  documentId,
  pageIndex,
  scale: scaleOverride,
  style,
  ...props
}: TilingLayoutProps) {
  const { provides: tilingProvides } = useTilingCapability();
  const documentState = useDocumentState(documentId);
  const [tiles, setTiles] = useState<Tile[]>([]);

  useEffect(() => {
    if (tilingProvides) {
      return tilingProvides.onTileRendering((event) => {
        if (event.documentId === documentId) {
          setTiles(event.tiles[pageIndex] ?? []);
        }
      });
    }
  }, [tilingProvides, documentId, pageIndex]);

  const actualScale = useMemo(() => {
    if (scaleOverride !== undefined) return scaleOverride;
    return documentState?.scale ?? 1;
  }, [scaleOverride, documentState?.scale]);

  return (
    <div
      style={{
        ...style,
      }}
      {...props}
    >
      {tiles?.map((tile) => (
        <TileImg
          key={tile.id}
          documentId={documentId}
          pageIndex={pageIndex}
          tile={tile}
          dpr={window.devicePixelRatio}
          scale={actualScale}
        />
      ))}
    </div>
  );
}
