// cloudpdf/website/src/samples/search/basic.svelte/SearchBox.svelte
<script lang="ts">
  import { useSearch, useSearchState } from '@embedpdf/svelte/search';

  const search = useSearch();
  const searchState = useSearchState();
  let text = $state('PDF');

  // Every change searches again, replacing the last search. An empty text clears it.
  $effect(() => {
    void search.search({ text });
  });

  const count = $derived.by(() => {
    if (searchState.hitCount > 0)
      return `${searchState.activeHitIndex + 1} of ${searchState.hitCount}`;
    if (searchState.status === 'searching') return 'Searching…';
    if (searchState.status === 'complete') return 'No matches';
    return '';
  });

  function onKeyDown(event: KeyboardEvent) {
    if (event.key !== 'Enter') return;
    if (event.shiftKey) search.previousHit();
    else search.nextHit();
  }
</script>

<div class="toolbar">
  <input
    class="field"
    type="search"
    aria-label="Search"
    placeholder="Search…"
    bind:value={text}
    onkeydown={onKeyDown}
  />
  <output class="readout">{count}</output>
  <button
    type="button"
    class="button"
    aria-label="Previous match"
    disabled={searchState.hitCount === 0}
    onclick={() => search.previousHit()}
  >
    ↑
  </button>
  <button
    type="button"
    class="button"
    aria-label="Next match"
    disabled={searchState.hitCount === 0}
    onclick={() => search.nextHit()}
  >
    ↓
  </button>
</div>

// cloudpdf/website/src/samples/search/basic.vue/SearchBox.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { useSearch, useSearchState } from '@embedpdf/vue/search';

const search = useSearch();
const { hitCount, activeHitIndex, status } = useSearchState();
const text = ref('PDF');

// Every change searches again, replacing the last search. An empty text clears it.
watch(text, (value) => void search.search({ text: value }), { immediate: true });

const count = computed(() => {
  if (hitCount.value > 0) return `${activeHitIndex.value + 1} of ${hitCount.value}`;
  if (status.value === 'searching') return 'Searching…';
  if (status.value === 'complete') return 'No matches';
  return '';
});

function onKeydown(event: KeyboardEvent) {
  if (event.key !== 'Enter') return;
  if (event.shiftKey) search.previousHit();
  else search.nextHit();
}
</script>

<template>
  <div class="toolbar">
    <input
      v-model="text"
      class="field"
      type="search"
      aria-label="Search"
      placeholder="Search…"
      @keydown="onKeydown"
    />
    <output class="readout">{{ count }}</output>
    <button
      type="button"
      class="button"
      aria-label="Previous match"
      :disabled="hitCount === 0"
      @click="search.previousHit()"
    >
      ↑
    </button>
    <button
      type="button"
      class="button"
      aria-label="Next match"
      :disabled="hitCount === 0"
      @click="search.nextHit()"
    >
      ↓
    </button>
  </div>
</template>
